### ISSUE TITLE
Data entry in the WB from specimen images

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1153] opened 2022-02-04 14:36 UTC
**Is your feature request related to a problem? Please describe.**
UMich uses Specify 6 to enter its main herbarium specimen data into the workbench directly from specimen images linked to the workbench.

**Describe the solution you'd like**
Specify 7 should replicate this capability that 6 currently offers.

**Reported By**
UMich

**Comment by maxxxxxdlp** [comment] 2022-02-04 15:54
Possible duplicate of https://github.com/specify/specify7/issues/764

**Closed** 2022-06-15 04:19 UTC
Labels: type:enhance, pri:unknown
