### ISSUE TITLE
Some scriptlets are not working in Specify 7 (GetByLoanAgentRole)

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1577] opened 2022-05-12 20:45 UTC
Some scriptlets (namely, GetByLoanAgentRole) don't function in SP7 and prevent us from being able to generate loan reports that include names of people involved with shipping, prepping, and receiving the loans. (see attached loan invoice header generated in SP6).
My request is that these be made to work in SP7.

![image](https://user-images.githubusercontent.com/37256050/168164764-126890e2-0a29-431f-8045-daf8a512299c.png)

**Requested By:** [Plarson on the Specify Forum](https://discourse.specifysoftware.org/t/scriptlets-for-reports-in-sp7/496)

**Comment by maxxxxxdlp** [comment] 2022-05-12 20:50
Duplicate of https://github.com/specify/specify7/issues/557
I will close this one, but reference it in there

**Closed by maxxxxxdlp** 2022-05-12 20:50 UTC
Labels: type:bug, pri:unknown
