### ISSUE TITLE
Polygon not mapped in GEOLocate after save

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3242] opened 2023-03-22 18:46 UTC
After creating a polygon in GEOLocate, I save it to the form. When I use GEOLocate again, it is not mapped.

https://user-images.githubusercontent.com/37256050/227006388-5986e02f-c1e4-4195-b2dc-5efe78b2212e.mp4

**Comment by specifysoftware** [comment] 2023-03-22 19:03
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/creating-polygons-for-regions/1105/2

**Comment by grantfitzsimmons** [comment] 2023-08-07 03:29
Denmark has an issue on their repository about this problem. We should look into fixing this when we get some time to discuss upcoming issues!

**Comment by emenslin** [comment] 2024-08-05 13:05
Can recreate in edge (7.9.6)

**Comment by emenslin** [comment] 2024-08-06 14:41
Duplicate of #3957

**Closed by emenslin** 2024-08-06 14:41 UTC
Labels: 1 - Bug, 2 - Forms
