### ISSUE TITLE
Can't add a new locality record from saved collecting event record.

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4705] opened 2024-03-29 22:01 UTC
**Describe the bug**
Once a collecting event record has been saved, user cannot add a new locality record.

**To Reproduce**
1. Open new collecting event record.
2. Save collecting event record.
3. Click plus button to create a new locality record.
4. Save locality record.

Save button on the collecting event form turns red, sometimes takes a few seconds and then turns red. Does not happen if you add the new locality before the collecting event record is saved.

Did not happen in 7.9.3. Tested in fwri and KU Paleobotany

**Expected behavior**
To be able to save a collecting event after adding a new locality.

**Screenshots**

Uploading Screen Recording 2024-03-29 at 4.59.59 PM.mov…

**Comment by grantfitzsimmons** [comment] 2024-04-01 13:45
Hi @lexiclevenger –
Congratulations on your first issue!  :tada:

Some notes:

1. You must include the necessary contextual information when submitting an issue as is included in the "new issue" template:
   
   > - OS: [e.g. Windows 10]
   > - Browser: [e.g. Chrome, Safari]
   > - Specify 7 Version: [e.g. 7.6.1]
   > - Database Name: [e.g. kufish] (you can see this in the "About Specify 7" dialog)
   > - Collection name: [e.g. KU Fish Tissue]
   > - User Name: [e.g. SpAdmin]
   
   You should also include a copy of the [Specify 7 System Information](https://discourse.specifysoftware.org/t/download-specify-7-system-information/1614) if you are not also attaching a crash report to the issue.

2. Your screen recording upload did not complete. Make sure to preview your issue before submitting it to verify your video is viewable!

3. You should assign a relevant GitHub label to the issue in addition to "1 - Bug". For this issue, I would assign it "2 - Forms" as well, as this was an issue that prevented you from saving the record. Developers can reassess the labels you've assigned if it is incorrect, but it gives them and us a starting point when looking for issues in a specific category.

4. You should also include the web page URL along with the issue so that the developers can go directly to the page/form where you are encountering an issue.

We can further discuss this process this week! Great job covering almost everything on the first attempt!

**Comment by CarolineDenis** [comment] 2024-04-01 13:45
Probably a duplicate of https://github.com/specify/specify7/issues/4693

**Comment by lexiclevenger** [comment] 2024-04-01 19:11
https://github.com/specify/specify7/assets/164079735/8c3b38bf-d348-4a55-aa7a-508aba5bd7a1

**Closed** 2024-04-02 11:36 UTC
Labels: 1 - Bug
