### ISSUE TITLE
Creating a new record set leaves form reloading infinitely

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3123] opened 2023-03-08 20:09 UTC
https://coldfish-issue-729.test.specifysystems.org/specify/view/collectionobject/new/?recordsetid=138

**Steps to Recreate:**
1. Try to create a new record set on `coldfish` from scratch.
2. See infinite loading

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/37256050/223836649-cee49c95-04c7-49e4-b31c-5f0bad110048.png">

Present on `v7.8.7.1`

**Comment by maxxxxxdlp** [comment] 2023-03-08 20:14
This was supposedly fixed by https://github.com/specify/specify7/pull/3034
Can you make it happen on edge?

**Comment by melton-jason** [comment] 2023-06-12 22:37
@specify/ux-testing 
It has been awhile since this issue has been open, and there have been many changes to record sets since. 
Can this issue be reproduced?

**Comment by CarolineDenis** [comment] 2024-01-04 21:20
@melton-jason, reproducible on edge unfortunately

**Comment by CarolineDenis** [comment] 2024-01-04 21:22
fixed in xml-editor

**Closed by CarolineDenis** 2024-01-04 21:22 UTC
Labels: 1 - Bug, 2 - Record Sets
