### ISSUE TITLE
Add way to export Data Set Mappings in the UI

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4052] opened 2023-09-29 15:32 UTC
https://discourse.specifysoftware.org/t/export-data-set-mapping/809

https://github.com/specify/specify7/assets/37256050/92c86190-27ea-4a81-b33d-9267d7e53f70

The simplest solution is literally unhiding the `[DEV] Show Plan` button in the UI (removing DEV, of course).

I would like there to be a button to see the mapping, and it should include an **export** and an **import** button so that the plan can be shared between multiple users or modified manually outside of the WorkBench.

**Comment by maxxxxxdlp** [comment] 2023-09-30 02:11
Duplicate of #1363

**Closed by maxxxxxdlp** 2023-09-30 02:11 UTC
Labels: 1 - Request, 2 - WorkBench
