### ISSUE TITLE
[a11y] Cat # does not accept ######### value

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1629] opened 2022-05-17 16:50 UTC
![image](https://user-images.githubusercontent.com/37256050/168866768-b567aace-d10e-4a4d-b27b-64f17886cbf5.png)

`kufish`, default CO form

**Comment by maxxxxxdlp** [comment] 2022-05-17 16:56
Duplicate of #1554

**Closed by maxxxxxdlp** 2022-05-17 16:56 UTC
Labels: type:bug, pri:unknown
