### ISSUE TITLE
Workbench/Specify doesn't recognize certain characters from different alphabets

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#211] opened 2016-02-08 22:49 UTC
I haven't seen this happen much yet, but I can see it being a potential issue with foreign databases. For example, "ö" displays as "�". If I see more of these, I'll add them in the comments below.

**Comment by garrettgirard** [comment] 2016-02-08 22:50
"ç" and "ã" also aren't recognized. I assume this goes for all foreign characters.

**Comment by garrettgirard** [comment] 2016-02-08 22:55
"°" (degree) symbol also isn't recognized. Nor is "é", "í", or "á"

**Comment by benanhalt** [comment] 2016-02-08 23:36
Are these characters in imported csv files, or entered / copied into the workbench? If the former, this is probably a duplicate of #210, and you just need to select a different encoding when importing. UTF-8 and latin1 are the most common in the U.S. For files from Macs, there are also some Mac encodings you could try.

**Comment by garrettgirard** [comment] 2016-02-09 15:31
These were characters from imported csv files. For example, in the directory in the Specify drive with all the Workbench testing spreadsheets, if you try to import the INPA (I think it's ento, like 8,000 records or something) spreadsheet, you'll see numerous characters like these that are changed to question marks after you import it to workbench.

**Comment by benanhalt** [comment] 2016-02-09 19:17
Is it not working if you choose latin1 for the encoding?

**Comment by garrettgirard** [comment] 2016-02-09 20:54
Ahh, I didn't see that choosing the file encoding was a feature for workbench. Choosing latin1 fixes the issue above. So this is pretty much a duplicate of #210 
Verified using the INPA spreadsheet as a dataset and changing the encoding.

**Closed** 2016-02-09 20:57 UTC
Labels: pri:low, qa:passed, res:duplicate, type:bug
