### ISSUE TITLE
Trying to delete Collection Object Attachment record gives `AssertionError`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2590] opened 2022-12-12 21:35 UTC
https://user-images.githubusercontent.com/37256050/207159324-c238634e-fea5-4458-9e82-fa4e7a1f8f4b.mov

https://coldfish-testability.test.specifysystems.org/specify/view/collectionobject/61324/?recordsetid=115

<img width="912" alt="image" src="https://user-images.githubusercontent.com/37256050/207159474-f4df4e01-53ee-4d9e-9430-68564c1dd678.png">

Attempting to delete a Collection Object Attachment record directly results in an `AssertionError`. This is something that should either be forbidden or resolved.

```
Error occurred fetching from https://coldfish-testability.test.specifysystems.org/api/specify/collectionobjectattachment/7621/
```
```
AssertionError at /api/specify/collectionobjectattachment/7621/
attempt to add object with null id to audit log
```

**Comment by melton-jason** [comment] 2023-01-04 17:01
Duplicate of #2499. I will close this issue because this problem applies to all attachments

**Closed by melton-jason** 2023-01-04 17:01 UTC
Labels: type:bug, pri:unknown
