### ISSUE TITLE
`xml-editor`: Address default table formatter throws an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4401] opened 2024-01-13 16:48 UTC
This might be a duplicate of https://github.com/specify/specify7/issues/3564, so feel free to combine if so.

**Describe the bug**
```
HierarchyException at /api/specify/address/ queryset model Address has no hierarchy field
```

<img width="1136" alt="Screenshot 2024-01-13 at 10 48 10 AM" src="https://github.com/specify/specify7/assets/37256050/8192f133-e0d2-4f08-a17c-5d78f04152cb">

[Specify 7 Crash Report - 2024-01-13T16_48_26.826Z.txt](https://github.com/specify/specify7/files/13928889/Specify.7.Crash.Report.-.2024-01-13T16_48_26.826Z.txt)

**To Reproduce**
1. Create a new `DataObjFormatters` app resource
2. Go to Address
3. Click on the `Address` format
4. See error in toast

macOS, Arc, `xml-editor`

**Comment by melton-jason** [comment] 2024-01-13 17:03
Yes, this is a duplicate of #3564. 
To be explicit about which tables this would throw an error for currently, it will be any tables which do have any a field (or relationship) with a name in the HIERARCHY list:

https://github.com/specify/specify7/blob/28044671d26ac62409c0b557db0cd2668e3744d1/specifyweb/specify/filter_by_col.py#L12

**Closed by melton-jason** 2024-01-13 17:03 UTC
Labels: 1 - Bug, 2 - App Resources
