### ISSUE TITLE
Cannot save changes to user pref app resources

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3338] opened 2023-04-12 18:14 UTC
https://user-images.githubusercontent.com/103299204/231547303-9bc2a56c-888a-4154-b568-a9132c7c7456.mp4

branch: `edge`
https://coldfish-edge.test.specifysystems.org/specify/resources/app-resource/194/

**Comment by realVinayak** [comment] 2023-04-20 16:49
A bug which got introduced in refactoring preferences. Should be fixed on `use-dynamic-ranks` branch.

**Comment by melton-jason** [comment] 2023-06-13 02:18
Duplicate of #3411

**Closed by melton-jason** 2023-06-13 02:18 UTC
Labels: 1 - Bug, res:duplicate
