### ISSUE TITLE
When creating a record using a query combo box the entered value is deposited in the wrong field

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4512] opened 2024-02-09 21:49 UTC
**Describe the bug**
For example, when searching for a name of an agent, the user can 'Add' a new agent and the searched term is deposited in the `lastName` field of the form to make it easier to create a new agent. 

**Expected behavior**
On `edge`, it puts it in the `firstName` field, which is not desired.
On `v7.9.3`, it puts it in the `lastName` field, which is the desired behavior.

**To Reproduce**

1. Go to a data entry form
2. Type a value into an agent query combo box
3. Click "add"
4. See that it puts it in the `firstName` field instead of the `lastName` field

**Screen Recording**
`edge` left, `v7.9.3` right

https://github.com/specify/specify7/assets/37256050/4fbf374f-3b03-4991-8b20-73ac7e60b23d

**Comment by melton-jason** [comment] 2024-02-09 21:55
Changes were probably caused by #4293

**Comment by maxpatiiuk** [comment] 2024-02-10 03:29
While https://github.com/specify/specify7/pull/4293 caused the bug to become visible, the bug was actually introduced by me in https://github.com/specify/specify7/commit/a4df14e7ce4f6e31f3e691c308c5bfc17a73abf6#diff-3b457d223cb9746621c9711ecfa5491cd57e06789d385dfed3bde34b5f3a79cdR271-R272

It's such a silly little thing
Fixed in #4516

**Closed** 2024-02-12 19:17 UTC
Labels: 1 - Bug, 2 - Forms
