### ISSUE TITLE
Validation Error When Using 3 Figure Year in Dates

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3596] opened 2023-06-08 16:25 UTC
**Describe the bug**
Title

**To Reproduce**
1. Go to Data Entry and then any item that has Date in its form
2. Change format to `Year` and Enter a 3 figure value like `891`
3. Save

**Expected behavior**
2 Figures and less get automatically converted to a full 4 digit number. I don't know if Bio Diversity Institutions were operating between the years 100 and 999. Otherwise if not, then automatically converting should work too. You can see what I mean by the enter the years `12` or `4`

**Screenshots**

<img width="1208" alt="Screenshot 2023-06-08 at 11 19 09 AM" src="https://github.com/specify/specify7/assets/53784701/fefb2c3b-001b-401b-8a37-471d3648101c">
<img width="1785" alt="Screenshot 2023-06-08 at 10 58 41 AM" src="https://github.com/specify/specify7/assets/53784701/bbf7299a-3dc2-4d20-8030-701732860b1a">

Desktop:

OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.12

**Comment by emenslin** [comment] 2024-08-05 16:42
Can recreate in edge (7.9.6)

**Comment by emenslin** [comment] 2024-08-05 17:43
Duplicate of #3808

**Closed by emenslin** 2024-08-05 17:43 UTC
Labels: 1 - Bug, 2 - Forms
