### ISSUE TITLE
Collection object deletion blocker fails to load preparation references

### ISSUE THREAD

**Issue by Areyes42** [specify/specify7#5062] opened 2024-07-02 16:46 UTC
**Describe the bug**
The deletion blocker dialog for a collection object fails to correctly link to preparations associated with an interaction. Attempting to click on these referenced preparations results in an infinite loading dialog without displaying any data.

**To Reproduce**

1. Add CO preparations to an interaction (e.g. gift)
2. Go to the CO and try to delete
3. Click on the referenced preparations
4. See dialog box

**Expected behavior**
The deletion blocker should properly load the interaction preparation table. Also, I think it would be more helpful for the user if it referenced back to the entire interaction, not just the preparation table (e.g., referencing the gift itself rather than the gift preparation).

**Screenshots**

https://github.com/specify/specify7/assets/130881183/2ea5c00d-b1d3-484b-bb87-9c5fe5bee276

Please, also fill out the following information manually:

- OS: macOS 14.5
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: KUMammals_2024_06_06
- Collection name: Mammalogy
- User Name: spmamadmin

**Comment by melton-jason** [comment] 2024-07-02 17:37
Duplicate of #4592

**Closed by melton-jason** 2024-07-02 17:37 UTC
Labels: 1 - Bug, 2 - Interactions
