### ISSUE TITLE
Add record set merging

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3610] opened 2023-06-09 21:05 UTC
In Specify 6, record sets can be merged together by dragging and dropping on top of each other. There is no equivalent option in Specify 7. 

**Requested By:** Geneva

Related to #3609

**Comment by maxxxxxdlp** [comment] 2023-06-10 16:27
Duplicate of https://github.com/specify/specify7/issues/1665

**Closed by maxxxxxdlp** 2023-06-10 16:27 UTC
Labels: type:enhance, pri:unknown
