### ISSUE TITLE
Can't synonymize a parent with synonymized children

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1738] opened 2022-06-07 15:48 UTC
Reported by edinburgh in current external.  Confirmed in KUBirds in ally

Users should be able to synonymize a parent if the children are synonymized as well.  The only reason they shouldn't be able to synonymize is if there are unsynonymized children.

**Comment by maxxxxxdlp** [comment] 2022-09-27 12:57
Duplicate of #751

**Closed by maxxxxxdlp** 2022-09-27 12:57 UTC
Labels: type:bug, pri:unknown, Post 7.7.0, back-end
