### ISSUE TITLE
Tree viewer bouncing between two items due to local syncing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3655] opened 2023-06-21 21:41 UTC
I suspect this is caused by local storage syncing between tabs. We need to find a way to fix this, while still preserving localstorage sync.

See the user-submitted video:

https://github.com/specify/specify7/assets/37256050/908fa8cb-1f1f-4785-a139-fb37acc1d93e

This happens when there are multiple tabs open with different items selected. This has been reported a number of times.

**Reported By:** Robyn at RBGE
>One of our users has reported an issue with the selection box when in the taxon tree. She found that it was flickering , so tried to select a different taxon to move the box, in the hope of stopping the flickering. This resulted in two taxa being selected, and the boxes were still flickering. She tried refreshing the page, but this didn’t stop the flickering. The only way she found to stop it was to close and reopen the taxon tree.

**Comment by maxxxxxdlp** [comment] 2023-06-24 03:39
Duplicate of #3599, and that issue is also likely a duplicate

**Closed by maxxxxxdlp** 2023-06-24 03:39 UTC
Labels: type:bug, pri:unknown
