### ISSUE TITLE
[testability] Changing lat/long selection in query after running it does not allow new results to be returned

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2222] opened 2022-09-27 02:50 UTC
https://user-images.githubusercontent.com/37256050/192420504-242ba5f5-98f6-4496-9dfc-c4a8eb612f23.mov

**To Reproduce**
1. Go to this query: https://freshfish-testability.test.specifysystems.org/specify/query/124/
2. Run the query with the current configuration
3. After running the query, click on the 📍 icon on the query item
4. Change the selection
5. Run the query and see results do not change

user: `abentley`
db: `freshfish`

**Comment by maxxxxxdlp** [comment] 2022-09-29 16:12
Duplicate of #2040

**Closed by maxxxxxdlp** 2022-09-29 16:12 UTC
Labels: type:bug, pri:unknown
