### ISSUE TITLE
Query headings are stacked vertically 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4514] opened 2024-02-09 21:53 UTC
**Describe the bug**
Run a query and see that the column headings are stacked vertically

**To Reproduce**

1. Run this query (https://umherb11024-edge.test.specifysystems.org/specify/query/168/)
2. See problematic behavior

**Expected behavior**
Not that!

https://github.com/specify/specify7/assets/37256050/84d320fe-eb98-4ee7-9407-22771b9a3f6b

**Comment by CarolineDenis** [comment] 2024-02-13 15:41
Duplicate of: https://github.com/specify/specify7/issues/4467
Will close #4467
Describe the bug
A clear and concise description of what the bug is.

Styling problem when this query is made "distinct" and results are ran. Haven't replicated issue with other query mappings yet, so I'm unsure what the specific cause/reason is. Could be related to querying on ID field?

Screenshots
If applicable, add screenshots to help explain your problem.

Screenshot 2024-01-26 at 12 36 13 PM
Alternatively, please fill out the following information manually:

OS: macOS
Browser: Chrome
Specify 7 Version: edge(debug) (v7.9.4)
Database Name: gothenburg_12_07_03
Additional context
Database name or any other context about the problem here.

not in v7.9.3!

https://gothenburg120723-edge.test.specifysystems.org/specify/query/66/

user: gnmuser
collection: GeneralKatalogen

**Closed** 2024-02-21 14:37 UTC
Labels: 1 - Bug, 2 - Queries
