### ISSUE TITLE
Bad Tree Structure Renames Taxonomic Rank

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3577] opened 2023-06-05 20:20 UTC
**Describe the bug**
If you change the `Parent of Taxon` of a new Taxon to something that doesn't make sense in the context of `Taxonomic Rank` the Taxonomic Rank turns into something like this `/api/specify/taxontreedefitem/2/`

**Screen Recording**
<img width="859" alt="Screenshot 2023-06-05 at 3 14 57 PM" src="https://github.com/specify/specify7/assets/53784701/c88ba517-82ed-4eba-acb2-6a48b4f903d1">

https://github.com/specify/specify7/assets/53784701/45e58f5d-5b8c-4b91-81cb-bb63e6db56ae

**To Reproduce**
1. Go to a taxonomy tree
2. Click on Add Child
3. Make Parent of Child, `Life` and Taxonomic Rank, `Kingdom`
4. Change Parent of Child to something to that makes no sense. Like a child of Kingdom
5. See error

**Expected behavior**
Taxonomic Rank becomes empty or just something else that a non technical person can get

**Desktop:**
 - OS: Mac OSx Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.12 and 7.8.11

**Database Name:** Any

**Comment by melton-jason** [comment] 2023-06-06 00:48
Duplicate of #2637.

@grantfitzsimmons 
This is probably something that should be handled by business rules. 
The solution would be to set the rank of any tree node to null if its parent changed _and_ the old rank was invalid. 

I can push a fix for this in `v7.8.12-prerelease` if needed, but I will need to fix this on `xml-editor` as well, separately. 
Can we reevaluate how likely this issue is to happen in a production database? If still very unlikely, it may be safe to wait for `xml-editor` to be released.

**Comment by melton-jason** [comment] 2023-06-06 00:58
Nevermind, I was wrong! Specify specially renders the Taxonomic Rank pick list and has special logic in the function that renders it.
I will fix this on the `v7.8.12-prerelease` branch :partying_face:

**Comment by realVinayak** [comment] 2023-06-06 12:04
@melton-jason I think this is known issue with Taxonomic Rank showing as the url. 

Also, 

> The solution would be to set the rank of any tree node to null if its parent changed and the old rank was invalid.

Do you mean setting the rank to null in just the formUI or in the database? I hope the former lol.

**Comment by melton-jason** [comment] 2023-06-06 12:34
> @melton-jason I think this is known issue with Taxonomic Rank showing as the url.
> 
> Also,
> 
> > The solution would be to set the rank of any tree node to null if its parent changed and the old rank was invalid.
> 
> Do you mean setting the rank to null in just the formUI or in the database? I hope the former lol.

Just clearing the rank id in the form if the old rank was invalid. 
It was discussed as a proposed solution in https://github.com/specify/specify7/issues/2637#issuecomment-1349219586

**Comment by grantfitzsimmons** [comment] 2023-09-08 01:37
<img width="749" alt="image" src="https://github.com/specify/specify7/assets/37256050/caf15986-2a92-4173-8cb6-e59c0e16f664">

https://morpaleo2may-v79-dev.test.specifysystems.org/specify/tree/lithostrat/?conformation=%7E%7E1%7E3%7E5%7E12-%7E11%7E13------

This is happening in `v7.9-dev` in the Litho Strat tree

**Comment by grantfitzsimmons** [comment] 2024-02-08 16:11
Duplicate of #2637 unless @melton-jason says otherwise

**Closed by grantfitzsimmons** 2024-02-08 16:11 UTC
Labels: 1 - Bug, 2 - Trees
