### ISSUE TITLE
Attachment gallery not loading correctly 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4549] opened 2024-02-15 18:54 UTC
**Describe the bug**
When browsing in forms on in a record set when you initially click the attachment gallery icon it does not load properly. 

**To Reproduce**

1. Go to a record set without any attachments 
2. Click on attachment gallery
3. See the popup is the wrong size.

This also works with browsing in forms on a query which is shown in the video below. 

**Expected behavior**
The popup should show up smaller, like in 7.9.3

**Screenshots**

https://github.com/specify/specify7/assets/150940840/42ae499b-1513-430f-874f-391357cbf2c6

Alternatively, please fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823

**Comment by CarolineDenis** [comment] 2024-02-15 19:40
@maxpatiiuk , @grantfitzsimmons do you think it's link to https://github.com/specify/specify7/issues/4385?

**Comment by grantfitzsimmons** [comment] 2024-02-16 14:50
I believe it might be a duplicate of #4385. We should consider adding this as an issue to confirm it's resolved during testing of the PR that addresses that problem.

**Comment by maxpatiiuk** [comment] 2024-02-17 03:36
hmm, the issue description states:

> When browsing in forms on in a record set when you initially click the attachment gallery icon it does not load properly.

Attachment Gallery not loading seems unrelated to the dialog sizing issues?
Or am I misreading what this issue is about?

**Comment by CarolineDenis** [comment] 2024-02-18 16:44
@maxpatiiuk, from the video I thought it was the dialog not taking the proper size after the skeleton disappeared. 
As the description of the bug says: 

> See the popup is the wrong size.

**Comment by CarolineDenis** [comment] 2024-02-19 18:08
NOTES: 
https://github.com/specify/specify7/pull/4433 does not fix this issue

**Closed** 2024-02-23 16:40 UTC
Labels: 1 - Bug, 2 - Attachments
