### ISSUE TITLE
Cannot create new user with same name as a deleted user

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2269] opened 2022-09-30 20:34 UTC
**Describe the bug**
Error message appears when trying to create a new user with the same name as a deleted user.

**To Reproduce**
1. Create a user
2. Delete the user
3. Create a user with the same name as the deleted user
4. See error message: 
[Specify 7 Crash Report - 2022-09-30T20_23_39.324Z (1).txt](https://github.com/specify/specify7/files/9687428/Specify.7.Crash.Report.-.2022-09-30T20_23_39.324Z.1.txt)

**Expected behavior**
Expected to be able to create a new user with the same name as a deleted user

**Screenshots**
<img alt="image" width="600" src="https://user-images.githubusercontent.com/103299204/193351752-81ed3a53-6c5c-4da5-9153-141dc0dd1e13.png">

Console: <a href="https://user-images.githubusercontent.com/103299204/193351974-d7572b45-b821-4db6-a912-564a8fa3e4b6.png">Console</a>

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: 7.7.3

**Database Name:** `freshfish`

**Comment by grantfitzsimmons** [comment] 2023-08-06 19:44
Can we close this as a duplicate of #1702 @melton-jason ?

**Comment by melton-jason** [comment] 2023-08-06 19:51
Yes! The underlying cause between the two issues are most likely the same. 
The issue here is that the POST request to delete the user must not have been sent to the backend, but the resource was removed from the frontend's ORM, Backbone. 

> In regards to the ugly IntegrityError message, this is because Specifyuser name was not a uniqueness rule on either the front or backend, but is enforced at a database level.

And this issue has been resolved in v7.9-dev.

**Closed by melton-jason** 2023-08-06 19:51 UTC
Labels: 1 - Bug
