### ISSUE TITLE
Error when saving new agent 

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4188] opened 2023-11-02 15:31 UTC
**Describe the bug**
When saving a new Agent in Data Entry, an error is created. 

**To Reproduce**
1. Go to: Data Entry ⇒ Agent (https://archireef-edge.test.specifysystems.org/specify/view/agent/new/)
2. Add any inputs into any fields 
    - inputs in screenshot:
        - Agent Type: Person
        - Last Name: Issue
        - First Name: Testt
        - Middle Initial: T
        - Email: testissue@email.com
3. Click Save
[Specify 7 Crash Report - 2023-11-02T15_08_42.464Z.txt](https://github.com/specify/specify7/files/13241613/Specify.7.Crash.Report.-.2023-11-02T15_08_42.464Z.txt)

**Expected behavior**
Should save agent without error pop up

**Screenshots**
![Screen Shot 2023-11-02 at 10 14 18 AM](https://github.com/specify/specify7/assets/118556884/1e67721f-150c-4f80-aad7-37a3d3f00730)

**Desktop:**
- OS: macOS Monterey (12.6.5)
- Browser: Google Chrome
- Specify 7 Version: `edge`

**Database Name:** `archireef (6.8.03)`

**Comment by melton-jason** [comment] 2023-11-06 18:38
Duplicate of #3874 

> This issue should only be specific to the `archireef` database.
> 
> Looking at the server, their database has a malformed `spdataset` table:
> 
> ```sql
> MariaDB [archireef]> desc spdataset;
> +--------------------+--------------+------+-----+---------+----------------+
> | Field              | Type         | Null | Key | Default | Extra          |
> +--------------------+--------------+------+-----+---------+----------------+
> | id                 | int(11)      | NO   | PRI | NULL    | auto_increment |
> | name               | varchar(256) | NO   |     | NULL    |                |
> | columns            | longtext     | NO   |     | NULL    |                |
> | uploadplan         | longtext     | YES  |     | NULL    |                |
> | uploadresult       | longtext     | YES  |     | NULL    |                |
> | collection_id      | int(11)      | NO   | MUL | NULL    |                |
> | specifyuser_id     | int(11)      | NO   | MUL | NULL    |                |
> | visualorder        | longtext     | YES  |     | NULL    |                |
> | importedfilename   | longtext     | YES  |     | NULL    |                |
> | remarks            | longtext     | YES  |     | NULL    |                |
> | timestampcreated   | datetime(6)  | NO   |     | NULL    |                |
> | timestampmodified  | datetime(6)  | NO   |     | NULL    |                |
> | createdbyagent_id  | int(11)      | YES  | MUL | NULL    |                |
> | modifiedbyagent_id | int(11)      | YES  | MUL | NULL    |                |
> +--------------------+--------------+------+-----+---------+----------------+
> 14 rows in set (0.002 sec)
> ```
> 
> Compare this to the `spdataset` table on the `fwri` database:
> 
> ```sql
> MariaDB [fwri]> desc spdataset;
> +--------------------+--------------+------+-----+---------+----------------+
> | Field              | Type         | Null | Key | Default | Extra          |
> +--------------------+--------------+------+-----+---------+----------------+
> | id                 | int(11)      | NO   | PRI | NULL    | auto_increment |
> | name               | varchar(256) | NO   |     | NULL    |                |
> | columns            | longtext     | NO   |     | NULL    |                |
> | data               | longtext     | NO   |     | NULL    |                |
> | uploadplan         | longtext     | YES  |     | NULL    |                |
> | uploaderstatus     | longtext     | YES  |     | NULL    |                |
> | uploadresult       | longtext     | YES  |     | NULL    |                |
> | rowresults         | longtext     | YES  |     | NULL    |                |
> | collection_id      | int(11)      | NO   | MUL | NULL    |                |
> | specifyuser_id     | int(11)      | NO   | MUL | NULL    |                |
> | visualorder        | longtext     | YES  |     | NULL    |                |
> | importedfilename   | longtext     | YES  |     | NULL    |                |
> | remarks            | longtext     | YES  |     | NULL    |                |
> | timestampcreated   | datetime(6)  | NO   |     | NULL    |                |
> | timestampmodified  | datetime(6)  | NO   |     | NULL    |                |
> | createdbyagent_id  | int(11)      | YES  | MUL | NULL    |                |
> | modifiedbyagent_id | int(11)      | YES  | MUL | NULL    |                |
> +--------------------+--------------+------+-----+---------+----------------+
> 17 rows in set (0.001 sec)
> ```
> 
> `archireef` is missing three _very_ important columns in the spdataset table: data, uploaderstatus, and rowresults.
> 
> Even accessing the datasets via the Workbench button from the Navigation Menu results in an error ![archireef_spdataset](https://user-images.githubusercontent.com/64045831/257353704-9df15e9a-06c4-4cbc-b0c3-fb597ec6ccb3.png)
> 
> I made sure this was not a problem on databases that were configured as Specify expects. To test this you can:
> 
> * Create a WorkBench dataset (Any Base Table)
> * (should be optional) upload the dataset
> * Try and merge the agent who created the Dataset

From https://github.com/specify/specify7/issues/3874#issuecomment-1659219000

To prevent this issue from popping up again, I have added the three missing columns to the `spdataset` table: 
- data
- uploaderstatus
- rowresults

You should no longer receive this error from that database!

**Closed by melton-jason** 2023-11-06 18:38 UTC
Labels: 1 - Bug
