### ISSUE TITLE
[a11y] Saving a CO record with ######## in the formatter gives an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1564] opened 2022-05-12 17:21 UTC
![image](https://user-images.githubusercontent.com/37256050/168132599-8dc4ecaa-3194-4d41-a819-c5588715586b.png)

How it should appear:
![image](https://user-images.githubusercontent.com/37256050/168132687-e4c18beb-0a35-4e36-9917-0dee025c7886.png)

db: `kufish`

**Comment by maxxxxxdlp** [comment] 2022-05-20 02:39
Duplicate of #1554

**Closed by maxxxxxdlp** 2022-05-20 02:39 UTC
Labels: type:bug, pri:unknown
