### ISSUE TITLE
Unable to add field to pick list 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3695] opened 2023-06-27 19:54 UTC
**Describe the bug**
Not able to add an item to a picklist when I enter a value not in the list -- as described in this comment in [#3484](https://github.com/specify/specify7/pull/3484#issuecomment-1559810228). This is the case regardless of if the limit set in the form being is above or below the count of actual fields in the list. Instead, I get the 'Nothing found' message at the bottom. 

**To Reproduce**
1. Go to a pick list
2. Make sure read-only is off
3. Type something not already on list
5. See error

**Expected behavior**
Should be able to add a new field to the list from the form

**Screenshots**

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: 7.8.13-prerelease

**Database Name:** If applicable 
coloradopaleo

**Reported By**
Name of your institution

**Additional context**
Database name or any other context about the problem here.

See #3484

**Comment by melton-jason** [comment] 2023-06-27 21:21
I am not able to recreate this issue, both on a local instance of Specify7 (using fwri as a base) or in coloradopaleo on the test panel. 

The below screen recording exhibits the feature working as intended on a locally hosted instance of Specify 7 based from fwri on `v7.8.13-prerelease`. 

https://github.com/specify/specify7/assets/64045831/9bd5ad41-acfa-4eb7-9771-13422a12f5ea

Could you please provide a screen recording of a workflow which consistently reproduces the issue and/or attach a crash report?

**Comment by CarolineDenis** [comment] 2024-01-04 20:56
Fixed in xml-editor

**Closed by CarolineDenis** 2024-01-04 20:56 UTC
Labels: 1 - Bug, 2 - Forms
