### ISSUE TITLE
Form preview with invalid fields prevents saving edited form definition

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3357] opened 2023-04-17 18:03 UTC
Save button in form definition Visual Editor triggers business rules of embedded record.

https://user-images.githubusercontent.com/103299204/232571132-ff48c9d6-601b-4d51-8b30-921aa84ed8ce.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/view-set/4/Agent/Agent

**Comment by maxxxxxdlp** [comment] 2023-05-01 15:34
The issue is that if the form preview has errors, you are prevented from saving the edited form definition.
The contents of the form preview are not saved anywhere, so the real bug is that it prevents saving needlessly

**Comment by CarolineDenis** [comment] 2023-10-12 21:07
Fixed in xml-editor

**Closed by CarolineDenis** 2023-10-12 21:07 UTC
Labels: 1 - Bug, todo:verify, xml-editor
