### ISSUE TITLE
Parsing issue when selecting only a polygon in GEOLocate

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3880] opened 2023-08-01 14:28 UTC
<img width="990" alt="image" src="https://github.com/specify/specify7/assets/37256050/78d7780c-d5fa-47ed-8ca5-f455d4e15af1">

For instance, when you select a polygon and a point, you see the following in the preview within GEOLocate:

```
37.7749	-122.4194	Unavailable	37.77805,-122.488751,37.746294,-122.488751,37.768009,-122.455106,37.77805,-122.488751
```

You can see that the latitude, longitude, and uncertainty are separated by `	` characters.
The polygon is separated by `,` characters.

This doesn't cause a problem when you have a set of coordinates and an uncertainty radius, but when you only have a polygon, it causes errors to occur.

For example, if you have only this in your preview:

```
37.77805,-122.488751,37.746294,-122.488751,37.768009,-122.455106,37.77805,-122.488751
```

https://github.com/specify/specify7/assets/37256050/6d6b8135-b37d-4500-93db-8840bd4f5565

<img width="929" alt="image" src="https://github.com/specify/specify7/assets/37256050/a7263154-9e30-4330-8e8d-5f973ae8a1e1">

[console-export-2023-8-1_9-27-22.txt](https://github.com/specify/specify7/files/12230364/console-export-2023-8-1_9-27-22.txt)

@melton-jason was able to see this in action

My theory is that the comma separated polygon is trying to be interpreted as longitude, latitude, uncertainty, and then the polygon. Specify likely does not expect only a polygon, resulting in an error.

**Comment by emenslin** [comment] 2024-08-06 14:40
Duplicate of #3957

**Closed by emenslin** 2024-08-06 14:40 UTC
Labels: 1 - Bug
