### ISSUE TITLE
SHOW_INTERACTIONS should be replaced with Show Interactions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2229] opened 2022-09-27 20:08 UTC
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/192625300-fcb38e28-5eb3-44b6-a7c5-8f45658f4b18.png">

**Comment by maxxxxxdlp** [comment] 2022-09-29 16:30
Duplicate of #504

**Closed by maxxxxxdlp** 2022-09-29 16:30 UTC
Labels: type:bug, pri:unknown
