### ISSUE TITLE
Agent Merging- Minified React error #130

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3663] opened 2023-06-22 20:43 UTC
**Describe the bug**
In NHMD, I can not merge the `Stein Martin` Agent with another. I get this Error. Consult @melton-jason for a developer opinion on this Issue.

**To Reproduce**
1. Go to `NHMD` Open `NHMD Amber` Collection
2. Click on '`Query` and run `Agents for semantics`
3. Merge `Stein Martin` with any one else

**Expected behavior**
Agent Merging

**Beautiful Screen Recording**

https://github.com/specify/specify7/assets/53784701/8c68e6d3-3af7-462f-837c-48f53425d744

<img width="1792" alt="Screenshot 2023-06-22 at 3 42 59 PM" src="https://github.com/specify/specify7/assets/53784701/8cf3c002-ab1e-4dba-bca4-8e1b371e5dfe">

[Specify 7 Crash Report - 2023-06-22T20_43_33.185Z (1).txt](https://github.com/specify/specify7/files/11840318/Specify.7.Crash.Report.-.2023-06-22T20_43_33.185Z.1.txt)
[Specify 7 Crash Report - 2023-06-22T20_43_33.185Z.txt](https://github.com/specify/specify7/files/11840320/Specify.7.Crash.Report.-.2023-06-22T20_43_33.185Z.txt)

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Database Name:** NHMD

**Comment by carlosmbe** [comment] 2023-06-22 20:56
Recreated in UMich
Query is `AgentSelection11` and user is `HerbAdmin`

<img width="1593" alt="Screenshot 2023-06-22 at 3 55 53 PM" src="https://github.com/specify/specify7/assets/53784701/5a4ce8cc-57f7-4389-9910-089609ab553a">

**Comment by carlosmbe** [comment] 2023-06-23 21:42
Clearing cache causes Error to stop being thrown immediately.

Error will start happening again after interacting with
`Show conflicting fields only`

https://github.com/specify/specify7/assets/53784701/a3c83712-49c3-4bb2-a549-5b507dd8192f

**Comment by melton-jason** [comment] 2023-06-26 20:37
Here is the expanded (non-minified) error

![issue_3663](https://github.com/specify/specify7/assets/64045831/df2046c4-99bf-4d9d-bfda-8fb15791a8c2)

**Comment by melton-jason** [comment] 2023-07-03 20:39
This issue should now be fixed on the v7.9-dev branch as of 86c6319. 
Can you test this again?

**Comment by CarolineDenis** [comment] 2023-07-05 18:38
@melton-jason @carlosmbe  I cannot reproduce on v7.9-dev on test panel for the mentioned db and mentioned agent. Neither on another one. 
Bug seems fixed

**Closed** 2023-07-11 17:22 UTC
Labels: 1 - Bug
