### ISSUE TITLE
Gift preparations count can be set higher than the quantity

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1804] opened 2022-07-07 16:34 UTC
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/37256050/177824905-07d0a54d-a473-4bbc-ace6-f4d6c46eb505.png">

<img width="829" alt="image" src="https://user-images.githubusercontent.com/37256050/177825034-32b41fb5-d45d-429e-85ec-0da34b8a5045.png">

Gift preparations can have their quantity changed to be higher than their count.

https://a11y-2-2-2-2-2.test.specifysystems.org/specify/view/gift/585/

db: `cleanfish`

**Comment by maxxxxxdlp** [comment] 2022-07-07 16:36
Does this happen on `edge` too?

**Comment by grantfitzsimmons** [comment] 2022-07-07 16:41
Good news (I guess)- yes!

**Comment by maxxxxxdlp** [comment] 2022-09-12 17:40
Then it is a duplicate of https://github.com/specify/specify7/issues/108

**Closed by maxxxxxdlp** 2022-09-12 17:40 UTC
Labels: type:bug, pri:unknown
