### ISSUE TITLE
WorkBench data set properties shows incorrect timestamp created and modified

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#5103] opened 2024-07-15 20:59 UTC
**Describe the bug**
The 'Data Set Properties' form shows the correct time for 'timestamp uploaded,' but a different time for 'timestamp created' and 'timestamp modified' despite indicating the same time zone.

**To Reproduce**

1. Go to WorkBench
2. Create a new data set
3. Validate and upload the data set
5. Click on 'Meta Data'
6. See that 'Timestamp uploaded' and 'Timestamp created' are off by several hours
**Expected behavior**
All of the timestamp fields should show the correct time based on browser settings.

**Screenshots**

All of these actions were performed within minutes/seconds of each other.
<img width="1920" alt="Screenshot 2024-07-15 at 3 04 34 PM" src="https://github.com/user-attachments/assets/c2e15198-be7a-4a8a-84f1-c8b7c59d78a6">
The times should be:
Timestamp created: 2:59:57 CDT
Timestamp modified: 3:00:16 CDT
Timestamp uploaded: 3:00:33 CDT

[Specify 7 System Information - 2024-07-15T20_06_20.577Z.txt](https://github.com/user-attachments/files/16240055/Specify.7.System.Information.-.2024-07-15T20_06_20.577Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome, Safari
- Specify 7 Version: v7.6 through edge
- Database Name: Fitz_NHMA_Oct_2023
- Collection name: NHMA Vertebrate
- User Name: petrifiedroadkill

**Comment by emenslin** [comment] 2024-07-16 13:29
Duplicate of #641

**Closed by emenslin** 2024-07-16 13:29 UTC
Labels: 1 - Bug, 2 - WorkBench
