### ISSUE TITLE
[testability] Generate Invoice button takes up full form width

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2283] opened 2022-10-04 01:27 UTC
![image](https://user-images.githubusercontent.com/37256050/193714873-cceccf44-1478-422e-b75b-1ef7504df0ac.png)

https://herbrbge-testability.test.specifysystems.org/specify/view/gift/new/

https://herbrbge-v773.test.specifysystems.org/specify/view/gift/new/

**Comment by maxxxxxdlp** [comment] 2022-10-18 18:35
The one in v7.7.3 is incorrect. Caused by a bug (fixed in 5d569cad8. the bug where max width of a subview was limited as a side effect from me wanting to limit the field max-width in the security page for the user)

**Closed by maxxxxxdlp** 2022-10-18 18:35 UTC
Labels: type:bug, pri:unknown
