### ISSUE TITLE
Weblate tests fails in production after `xml-editor` merge

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4458] opened 2024-01-23 23:32 UTC
```
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/runner/work/specify7/specify7/specifyweb/frontend/js_src/lib/components/DataModel/resourceApi' imported from /home/runner/work/specify7/specify7/specifyweb/frontend/js_src/lib/components/DataModel/saveBlockers.tsx
```

[saveBlockers.tsx](https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/DataModel/saveBlockers.tsx) in `production`, [saveBlockers.ts](https://github.com/specify/specify7/blob/v7.9.3-copy/specifyweb/frontend/js_src/lib/components/DataModel/saveBlockers.ts) in `v7.9.3-copy`

<img width="1505" alt="image" src="https://github.com/specify/specify7/assets/37256050/a0d4a945-b1b3-4604-be23-763a8510d3c9">

We'll need to pick up on this and resolve it soon

**Comment by maxpatiiuk** [comment] 2024-01-24 03:09
This is a known bug in swc-node caused by node.js update
See https://github.com/swc-project/swc-node/issues/743
They merged the fix PR 4 days ago - https://github.com/swc-project/swc-node/pull/748
Now just to wait for them to release that

Hopefully that would be soon.
If we need solution either, we can either downgrade node.js to pre 20.6, or apply the fix manually locally

**Comment by grantfitzsimmons** [comment] 2024-01-26 15:07
We'll downgrade on next Wednesday if nothing is fixed by then

**Comment by maxpatiiuk** [comment] 2024-01-27 00:51
Yes, either downgrade node, or migrate from swc to tsx (yes I know we just migrated from ts-node to swc. from my limited experience, ts-node is very powerful but hard to use, swc is powerful, and tsx is the simplest to use)

**Closed** 2024-02-19 16:16 UTC
Labels: 1 - Bug
