### ISSUE TITLE
`IntegrityError` when trying to delete a user

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2784] opened 2023-01-11 15:24 UTC
(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`KUVertPaleo_1_11_23`.`spprincipal_sppermission`, CONSTRAINT `FK9DD8B2FA99A7381A` FOREIGN KEY (`SpPrincipalID`) REFERENCES `spprincipal` (`SpPrincipalID`))')

```
IntegrityError at /api/specify/specifyuser/10/
```

```
(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`KUVertPaleo_1_11_23`.`spprincipal_sppermission`, CONSTRAINT `FK9DD8B2FA99A7381A` FOREIGN KEY (`SpPrincipalID`) REFERENCES `spprincipal` (`SpPrincipalID`))')

```

https://kuvertpaleo11123-edge.test.specifysystems.org/specify/security/user/10/

current user: `spvertpaleoadmin`

[Specify 7 Crash Report - 2023-01-11T15_23_34.095Z.txt](https://github.com/specify/specify7/files/10393742/Specify.7.Crash.Report.-.2023-01-11T15_23_34.095Z.txt)

**Comment by grantfitzsimmons** [comment] 2023-01-11 15:26
See comment https://github.com/specify/specify7/issues/2783#issuecomment-1378944582

> So there were some layers to this issue–
> 
> When deleting a record that was blocking deletion, it would allow you to delete the record, and once that was done, it would immediately ask you whether you want to delete the user.
> 
> If you tried to delete the user and there was _another_ deletion blocker that was not visible initially, it would throw a 500 error.
> 
> Once you carefully deleted all blocking records and canceled the user delete in the subsequent dialog, you could try to delete the user once and for all.
> 
> Of course, once the blockers were removed, there is a new error: #2784

**Comment by melton-jason** [comment] 2023-01-12 15:51
I believe this is a duplicate of #1069. The issue occurs because Specify 7 does not also delete the Specify 6 permissions associated with that user. 
Will be fixed when #1694 is fixed.

**Comment by melton-jason** [comment] 2024-05-10 20:43
> **Describe the bug** Made a new guest user with no access to collections/etc. so no agent attached to it. Tried to delete it as an admin and got an integrity error.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Log in as an admin user
> 2. Go to Security and Accounts and create a new user. Don't give it collection access, only give it a username, password and put it in the Guest user group.
> 3. Save the new user.
> 4. After the page reloads after saving, try to delete the new user.
> 5. See crash.
> 
> **Expected behavior** User should've been deleted without any crashes.
> 
> **Screenshots**
> 
>  10_deleteuser.mp4 
> **Crash Report** [Specify 7 Crash Report - 2024-05-10T20 00 19.385Z.txt](https://github.com/specify/specify7/files/15279581/Specify.7.Crash.Report.-.2024-05-10T20.00.19.385Z.txt)
> 
> * OS: Windows 10
> * Browser: Firefox
> * Specify 7 Version: `edge` and `v7.9.3`
> * Database Name: `sdnhm_herps_2_8_24`
> * Collection name: `Herp-PC`
> * User Name: `testuser`, `sdnhmherp` (Both admin users)
> 
> [Specify 7 System Information - 2024-05-10T20 12 46.637Z.txt](https://github.com/specify/specify7/files/15279618/Specify.7.System.Information.-.2024-05-10T20.12.46.637Z.txt)

From @combs-a in https://github.com/specify/specify7/issues/4908#issue-2290353827

**Comment by emenslin** [comment] 2024-07-30 16:39
Fixed

**Closed by emenslin** 2024-07-30 16:39 UTC
Labels: 1 - Bug
