### ISSUE TITLE
Prompt to Replace Node with Preferred Node for all tables

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1773] opened 2022-06-27 16:31 UTC
**Is your feature request related to a problem? Please describe.**
We have synonymised nodes in our geography tree but when these are selected as the geography on the CO form there is no prompt to keep or change to the preferred value. I was expecting this to work like synonymy in the taxon tree. 

![image](https://user-images.githubusercontent.com/37256050/175990200-f1900c34-401e-4c44-9c56-35dfe10dadcc.png)

**Requested By:** Gillian Brown

**Comment by maxxxxxdlp** [comment] 2022-06-27 17:54
Duplicate of #1223

**Closed by maxxxxxdlp** 2022-06-27 17:54 UTC
Labels: type:enhance, pri:unknown

**Comment by grantfitzsimmons** [comment] 2022-06-27 18:16
Request is unique, encompasses all tables rather than only determinations.

**Comment by maxxxxxdlp** [comment] 2022-06-27 19:12
I see. Good idea.
Keep in mind those that this feature is not implemented even for the Taxon table in Specify 7

**Comment by grantfitzsimmons** [comment] 2023-08-24 14:55
> Hello,
> In Specify 6, within Preferences > Trees, there is an option to enable a 'Prompt to replace Taxon with Preferred Taxon'.
> 
> When enabled, if you select to add a taxon Synonym to a determination in Specify 6 (in single form entry), the system notifies you that you've selected a Synonym and gives you the ability to change your selection to the preferred taxon instead.
> 
> However, this prompt does not appear in Specify 7, should it? It is useful for users to be aware when they are selecting a synonym and be given the option to change to preferred  taxon at that point.

**Requested By:** Zoe W at CSIRO ([Asana](https://app.asana.com/0/1201972579963460/1205290033748588/f))

**Comment by grantfitzsimmons** [comment] 2023-08-24 14:57
See also https://github.com/specify/specify7/issues/3944
