### ISSUE TITLE
Nested Pick Lists

### ISSUE THREAD

**Issue by mc0822** [specify/specify7#2120] opened 2022-09-09 19:45 UTC
**Describe the solution you'd like**
Pick lists - Is it possible to have some filtering based on a field? (quote from the request: “‘Treatment undertaken’ : have a drop-down menu dependent on each prep type as the treatments will vary”)

**Reported By**
Zsuzsanna Papp of NHMD (Danish Natural History Museums)

**Additional context**
https://docs.google.com/document/d/1Yxmp64R9YWMlD__aosXa4XPn-duYe9ND/edit

Grant, Theresa, & Andy said other users have requested this as well.

**Comment by grantfitzsimmons** [comment] 2022-09-09 20:38
Duplicate of https://github.com/specify/specify7/issues/2107

**Closed by grantfitzsimmons** 2022-09-09 20:38 UTC
Labels: type:enhance, pri:unknown
