### ISSUE TITLE
Cannot delete corrupt app resource from the UI

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1919] opened 2022-08-01 00:01 UTC
<img width="841" alt="image" src="https://user-images.githubusercontent.com/37256050/182050828-a6a35599-2422-497d-bc68-10463ac4fa01.png">

In this case, I have an app resource that is throwing an error.

`'utf-8' codec can't decode byte 0x88 in position 10: invalid start byte`

I should be able to download a local copy and then delete the app resource from the UI. This error should (ideally) be friendly and allow those two options. 

db: `herb_rbge_0601`
user: britchie
branch: `issue-1872` (unrelated presumably)
`/specify/viewsets/1/`

**Comment by maxxxxxdlp** [comment] 2022-08-01 00:44
Duplicate of https://github.com/specify/specify7/issues/1202

I will repost your comment there

**Closed by maxxxxxdlp** 2022-08-01 00:44 UTC
Labels: type:bug, pri:unknown

**Comment by grantfitzsimmons** [comment] 2022-08-01 00:45
Thank you!
