### ISSUE TITLE
[testability] Cannot view associated loans with a preparation

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2238] opened 2022-09-28 02:47 UTC
https://user-images.githubusercontent.com/37256050/192675923-0fd15bf2-635a-471d-bda0-ae81b0fbb2b8.mov

**Steps to Recreate:**
1. Navigate to a CO record with preps (https://freshfish-testability.test.specifysystems.org/specify/view/collectionobject/29492/?recordsetid=72)
2. Expand a preparation to see the form view
3. Click on the "Show Loans" button

<img width="901" alt="image" src="https://user-images.githubusercontent.com/37256050/192675998-785970fa-7258-4751-a6e0-d6df156407cf.png">

db: `freshfish`
user: `abentley`

**Comment by maxxxxxdlp** [comment] 2022-10-07 18:28
Duplicate of #2042

**Closed by maxxxxxdlp** 2022-10-07 18:28 UTC
Labels: type:bug, pri:unknown
