### ISSUE TITLE
Add ability to bulk upload attachments

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#2106] opened 2022-09-07 17:47 UTC
Users have reported needing to bulk upload attachments to existing records due to digitation efforts.
PRI Paleo mentioned having around 1700 images to upload to existing records and North Carolina mentioned not having the ability as a reason they are not going to go into Specify 7 yet.

Specify 6 has a tool that allows users to bulk upload attachments either based on the name of the file, if the name matches a value in a record such as catalog number, field number, or a few other fields.  Or, it can use a mapping file which contains an identifying value for a record (such as catalog number) and the file name, to upload the records to the appropriate records.
Users can also upload multiple images to the same record in this tool by adding a suffix to the name such as a, b, c, or 1, 2, 3.

**Comment by maxxxxxdlp** [comment] 2022-09-09 18:26
Duplicate of https://github.com/specify/specify7/issues/764

**Closed by maxxxxxdlp** 2022-09-09 18:26 UTC
Labels: type:enhance, pri:unknown
