### ISSUE TITLE
Attempting to open formatter/aggregator editor for certain tables results in error

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3365] opened 2023-04-18 16:15 UTC
Also happens when attempting to add a new formatter/aggregator. Error happens for `AccessionAgent`, `AccessionAuthorization`, `AccessionCitation`, `Address`, among others.

https://user-images.githubusercontent.com/103299204/232839253-309c85e6-d39c-4562-9053-e72daeab1f9f.mp4

[Specify 7 Crash Report - 2023-04-18T16_11_42.821Z.txt](https://github.com/specify/specify7/files/11264022/Specify.7.Crash.Report.-.2023-04-18T16_11_42.821Z.txt)

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/190/formatter/AccessionAgent

**Comment by CarolineDenis** [comment] 2023-10-18 17:32
Duplicate of https://github.com/specify/specify7/issues/3564
@grantfitzsimmons  can we close this one?

**Comment by realVinayak** [comment] 2023-11-13 19:50
Closed, as this is duplicate of https://github.com/specify/specify7/issues/3564

**Closed by realVinayak** 2023-11-13 19:50 UTC
Labels: 1 - Bug, todo:verify, xml-editor
