### ISSUE TITLE
Error when saving after attaching file to exchange out

### ISSUE THREAD

**Issue by mc0822** [specify/specify7#2560] opened 2022-12-07 20:33 UTC
RBGE reports being unable to save when attaching files to Exchange Out.

](https://herbrbge6802-edge.test.specifysystems.org/specify/view/exchangeout/1045/)

Steps:
Add attachment to Exchange Out. The file attaches OK, but when trying to save the record, get error message (below).

**Expected behavior**
User should be able to save when attaching files to Exchange Out.

**Screenshots**
![120722 snip rbge 2](https://user-images.githubusercontent.com/111374878/206281934-945a405c-0053-47bd-b916-ad6a48735d3b.PNG)

**Desktop:**
 - OS: Windows 10
 - Browser: Safari
 - Specify 7 Version: edge

**Database Name:**
herb_rbge_6802 (6.8.02)
britchie
Herbarium

**Reported By**
Robyn Drinkwater, RBGE

**Additional context**
[Specify 7 Crash Report - 2022-12-07T19_49_58.319Z.txt](https://github.com/specify/specify7/files/10179527/Specify.7.Crash.Report.-.2022-12-07T19_49_58.319Z.txt)

**Comment by grantfitzsimmons** [comment] 2022-12-08 03:20
Duplicate of https://github.com/specify/specify7/issues/2525

**Closed by grantfitzsimmons** 2022-12-08 03:20 UTC
Labels: type:bug, pri:unknown

**Comment by mc0822** [comment] 2022-12-08 16:12
Just a note, the browser should state Edge, sorry for any confusion.
