### ISSUE TITLE
Need to bring back "Add" button

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#172] opened 2015-08-05 15:22 UTC
In cases such as adding associated collection objects to Accessions, the add button should be brought back. It was previously taken out because of how buggy it was, but it's kind of an important feature and it's probably a good idea to look into it.

**Comment by maxxxxxdlp** [comment] 2022-07-11 02:47
Duplicate of #114

**Closed by maxxxxxdlp** 2022-07-11 02:47 UTC
Labels: pri:normal, type:bug
