### ISSUE TITLE
Support uploading HostTaxon through the WorkBench

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#3282] opened 2023-03-31 21:13 UTC
> It will be tricky to implement and here is why:
> HostTaxon is a many-to-one relationship from the CollectingEventAttribute table to the Taxon table. 
> A HostTaxon inherently does not know anything about CollectionRelationships: it is not a CollectionRelationship and CollectionRelationship is not included anywhere in the key constraints.
> 
> Specify only knows which discipline to associate the Host Taxon to on the forms because the CollectionRelType name is defined _in the form definition_. 
> 
> This presents a dilemma for the WorkBench. 
> The WorkBench would need to access the form definition for Collecting Event Attribute (this would _have_ to be the form definition in the logged-in collection) to get the name of the CollectionRelType while evaluating the row. From the name, it can run a query and get the left-side/right-side collections. From the right-side collection it can get the discipline and its associated Taxon Tree, which it can evaluate the HostTaxon against.

From https://github.com/specify/specify7/pull/3240#issuecomment-1492001799 regarding this issue

Currently, uploading HostTaxon through the WorkBench is not supported (Specify 7 always assumes everything is in the current collection). 

This is part of a bigger issue that will inevitably spring up again. The WorkBench is heavily geared towards assuming everything that should be scoped to collection/discipline should do so with the logged-in collection. 
Preferably, we can improve the flexibility of the WorkBench and break this 'everything should in the logged-in collection' mindset rather than keep writing workarounds for issues/features. 
Of course this is no easy task and a gigantic can of worms which poses lots of questions about scoping/permissions/etc.

**Comment by maxxxxxdlp** [comment] 2023-03-31 21:48
Duplicate of #1335.
@melton-jason can you merge them and close either one of the two?

**Comment by melton-jason** [comment] 2023-04-03 21:51
I am closing this as a duplicate of #1335

**Closed** 2023-04-03 21:52 UTC
Labels: type:enhance, res:duplicate, pri:unknown
