### ISSUE TITLE
`xml-editor`: Improve UI

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3190] opened 2023-03-16 17:26 UTC
1. The UI for this component would be very confusing for a user, and it is difficult to tell which section you are editing (formatters or aggregators). This should be styled more similarly to the switcher at the top, potentially allowing you to select the type of editor by clicking on the gear on the right.
    <img width="531" alt="image" src="https://user-images.githubusercontent.com/37256050/225701680-945e3852-983f-47b9-b35b-b5c532ef4312.png">
2. You can see that the margins are really out of sorts, with the right side having much more space than the left.
     <img width="1460" alt="image" src="https://user-images.githubusercontent.com/37256050/225702276-c03435f0-c245-4c45-beef-8e3da172b94b.png">
3. Dialogs should not have an exclamation point in the top right
    <img width="430" alt="image" src="https://user-images.githubusercontent.com/37256050/225702702-8db28de6-fe27-4a72-b214-315164099e5b.png">

**Comment by maxxxxxdlp** [comment] 2023-04-15 03:03
> The UI for this component would be very confusing for a user, and it is difficult to tell which section you are editing (formatters or aggregators). This should be styled more similarly to the switcher at the top, potentially allowing you to select the type of editor by clicking on the gear on the right.

Fixed

> You can see that the margins are really out of sorts, with the right side having much more space than the left.

Unable to replicate. From the screenshot I can see that you are in firefox. I can also see that your screenshot includes scrollbars, which are not visible in my firefox until I try to scroll. By any chance, did you customize https://superuser.com/a/1763766 to force-enable scrollbars?

Are you still able to replicate it?

> Dialogs should not have an exclamation point in the top right

Duplicate of https://github.com/specify/specify7/issues/3323. Fixed

**Comment by grantfitzsimmons** [comment] 2023-04-17 16:35
> > You can see that the margins are really out of sorts, with the right side having much more space than the left.

This happens only in Firefox, and with default settings

**Closed** 2023-04-17 16:36 UTC
Labels: type:enhance, pri:unknown
