### ISSUE TITLE
Add preference to auto-focus to first editable field when new subview item is added

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3056] opened 2023-02-27 17:08 UTC
> We have recently implemented the use of the determiners table, which has increased the number of clicks needed to be able to enter a determiner (green plus and then click in the agent field). They were wondering if it would be possible for the cursor to automatically be in the agent field when they have clicked the green plus.

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/37256050/221631336-56b4e389-d7ae-49c5-b8e9-d92d5f188351.png">

**Expected Behavior:**
You click on the **+** icon and you are automatically entering text in the Agent query combo box

**Requested By:** RBGE

**Comment by maxxxxxdlp** [comment] 2023-02-27 17:20
Duplicate of #1543

**Closed by maxxxxxdlp** 2023-02-27 17:20 UTC
Labels: type:enhance, pri:unknown
