### ISSUE TITLE
Extend record merging

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4470] opened 2024-01-26 19:28 UTC
We should gradually expand the support tables throughout 2024. I recommend that we start with Locality. Testing can take place alongside our regular timeline.

- Locality
- Collecting Event
- Collection Object
- etc.

**Comment by maxpatiiuk** [comment] 2024-01-27 00:53
Duplicate of https://github.com/specify/specify7/issues/4046

**Closed by maxpatiiuk** 2024-01-27 00:53 UTC
Labels: 1 - Bug, 2 - Merging
