### ISSUE TITLE
[testability] Error Message Dialog Downloads Two Crash Reports 

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2288] opened 2022-10-04 21:19 UTC
**Bug Description**
When the download crash report button is clicked in the error message dialog, two crash reports are downloaded, one being a duplicate of the other. This bug occurs for every press of the download crash report button.

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: testability

**Database Name:** If applicable
`willem-catno`

**Comment by chanulee1** [comment] 2022-10-14 19:14
Also happens when exporting a data set through workbench.
os: Windows 11
Browser: Chrome
Specify 7 Version: `testability`

**Comment by maxxxxxdlp** [comment] 2022-10-18 19:10
Interesting. I am not able to replicate this. Tried in Chrome on Windows 10
Does this happen in `v7.7.5` too?

**Comment by melton-jason** [comment] 2022-10-18 20:13
> Interesting. I am not able to replicate this. Tried in Chrome on Windows 10 Does this happen in `v7.7.5` too? Does it happen in other browsers too?

I am not sure about other browser, but yes this issue also occurs in 7.7.5 in Chrome and Edge

**Comment by maxxxxxdlp** [comment] 2023-01-03 15:23
Duplicate of #2638

**Closed by maxxxxxdlp** 2023-01-03 15:23 UTC
Labels: type:bug, pri:unknown
