### ISSUE TITLE
Save button error 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4499] opened 2024-02-09 15:06 UTC
**Describe the bug**
When changing the accession number to an incorrect format the save button flashes red but then changes back to orange. 

**To Reproduce**

1. Go to 'accession'
2. Click on 'accession number'
3. Change to an incorrect format

**Expected behavior**
The save button should change to red immediately and stay that way like it does in 7.9.3

**Screenshots**
Edge behavior 

https://github.com/specify/specify7/assets/150940840/164666a4-ffc4-4cfb-829e-12a058d7dc9d

7.9.3.1 behavior 

https://github.com/specify/specify7/assets/150940840/5acca6c7-d6c9-4e63-b7e0-e48d1fa8af52

Alternatively, please fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823

**Comment by melton-jason** [comment] 2024-02-09 18:45
Might be related indirectly to #4501

**Comment by CarolineDenis** [comment] 2024-02-21 21:48
Duplicate of: https://github.com/specify/specify7/issues/4501

**Closed by CarolineDenis** 2024-02-21 21:48 UTC
Labels: 1 - Bug, res:duplicate, 2 - Forms
