### ISSUE TITLE
Show multiple records at once in form view

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2709] opened 2022-12-23 21:28 UTC
> Is there any way in Specify 7 that we can keep multiple records visible during a session when doing data entry?  I am finding that during a session I need to go back and edit a record I have entered before but can't get to it without searching.  It would be nice if there were arrows at the top (like when I browse in forms from a query) that I could use to navigate between records during a session.  Specify 6 does this and it is very handy.

**Requested By:** @acbentley

**Comment by maxxxxxdlp** [comment] 2022-12-23 22:01
Duplicate of https://github.com/specify/specify7/issues/511/ and https://github.com/specify/specify7/issues/1692

**Closed by maxxxxxdlp** 2022-12-23 22:01 UTC
Labels: type:enhance, pri:unknown
