### ISSUE TITLE
can't edit pick lists

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#2197] opened 2022-09-21 15:14 UTC
**Describe the bug**
Attempting to edit pick lists fails.  - Spins for about 10 seconds, then gets a 500 error.  
I'm editing in schema editor in 7.  
![image](https://user-images.githubusercontent.com/8005676/191542269-1f2e1795-25eb-4673-964f-a3cc4923e01c.png)

only item of interest I think is that its a long picklist - 857 items.  

we can add items to it successfully in 6.

- diags available on the herb-rbge at 16:13 BST 21/9

![image](https://user-images.githubusercontent.com/8005676/191542912-f765b22b-d60b-4b28-a6fa-ff03d00307df.png)

**Comment by grantfitzsimmons** [comment] 2022-09-21 19:19
Hi @benritchie -
Is this only on picklists with hundreds of items like the one in this example?

**Comment by benritchie** [comment] 2022-09-22 08:15
Looks like it is.  Yep.  
I've just successfully edited a short picklist (2 items).  
I don't know where the cut-off is.  
thanks

**Comment by grantfitzsimmons** [comment] 2022-09-22 14:47
@maxxxxxdlp **It seems that the picklist maximum is 500 in Specify 7.**

The save button is disabled when the limit is above 500, and in the screenshot from @benritchie the limit is set at 0. Specify 6 has no such restriction, so this is unintended behavior. 

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/37256050/191778020-a4cb1411-639a-4f89-be91-f934800ebfaa.png">

**Comment by maxxxxxdlp** [comment] 2022-09-22 17:58
The BussinessRule is limiting the max number of items in a pick list to what is set in the size limit field.
The form definition does not allow setting that value to higher than 500.
Setting it to 0 would disable the size limit. The default pick list form has a minimum size limit requirement of `2`. Thus, you should either edit the size limit though the API, or though the database, or create a custom form without that limit.

But really though, that Business rules should be removed altogether. Please vote up on https://github.com/specify/specify7/issues/1025 to get it fixed sooner

**Comment by maxxxxxdlp** [comment] 2022-09-22 18:02
Closing this as duplicate, as fixing https://github.com/specify/specify7/issues/1025 would fix this.

**Closed** 2022-09-22 18:02 UTC
Labels: type:bug, pri:unknown
