### ISSUE TITLE
[a11y] Horizontal scrollbar not appearing in Safari

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1571] opened 2022-05-12 19:41 UTC
![image](https://user-images.githubusercontent.com/37256050/168155312-23db5b22-1550-4a51-b349-12abff763ea2.png)

The WorkBench is not showing the horizontal scrollbar in Safari.

**Comment by maxxxxxdlp** [comment] 2022-05-20 02:40
Duplicate of #1507

**Closed by maxxxxxdlp** 2022-05-20 02:40 UTC
Labels: type:bug, pri:unknown
