### ISSUE TITLE
WB Error Cells no longer highlighted red

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4561] opened 2024-02-19 19:54 UTC
**Describe the bug**

See comparison between versions in screenshot (same dataset) 

<img width="1910" alt="Screenshot 2024-02-19 at 1 50 42 PM" src="https://github.com/specify/specify7/assets/135047322/3bc90b67-eab1-448b-a77d-853dde3039b5">

I used the arrows in the cell navigating boxes to go to the error cells but they aren't a different color in `edge`

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: `ku_fish_5_16_23`

**Comment by CarolineDenis** [comment] 2024-02-19 20:57
Duplicate of https://github.com/specify/specify7/issues/4450

**Closed** 2024-02-19 20:58 UTC
Labels: 1 - Bug, 2 - WorkBench
