### ISSUE TITLE
[testability] Fields pointing to relationship fields not displaying

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2279] opened 2022-10-04 00:32 UTC
<img width="2555" alt="image" src="https://user-images.githubusercontent.com/37256050/193709210-20c1c531-0b20-4f40-9602-0f4e63b51746.png">

This is visible on `testability` with the following excerpt on the `herb_rbge` CO form:

_See the Family No. and Genus No. under the Determination Citations subview._

```
                <row>
                    <cell type="subview" id="detcit" name="determinationCitations" viewname="DeterminationCitation" colspan="13"/>                    
                </row>
                <row>
                    <cell type="label" labelfor="familyNumber" label="Family No."/>
                    <cell type="field" id="familyNumber" name="taxon.text11" uitype="label"/>
                    <cell type="label" labelfor="genusNumber" label="Genus No."/>
                    <cell type="field" id="genusNumber" name="taxon.text12" uitype="label"/>
                </row>
```

DB: `herb_rbge`
User: `britchie`

Left: `testability` - [Link](https://herbrbge-testability.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178)
Right: `v773` - [Link](https://herbrbge-v773.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178)

**Comment by grantfitzsimmons** [comment] 2022-10-04 01:25
![image](https://user-images.githubusercontent.com/37256050/193714604-83e7cdd7-285a-4fb6-b5a9-88854a28f11d.png)

Could be an unrelated issue, but I see it as the same.

https://herbrbge-testability.test.specifysystems.org/specify/view/gift/new/
https://herbrbge-v773.test.specifysystems.org/specify/view/gift/new/

**Comment by maxxxxxdlp** [comment] 2022-10-17 15:29
Duplicate of #2277

**Closed by maxxxxxdlp** 2022-10-17 15:29 UTC
Labels: type:bug, pri:unknown
