### ISSUE TITLE
Include a link to associated records in delete blocked dialogs 

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1696] opened 2022-05-27 16:49 UTC
When attempting to delete a record that is associated with another record, a popup saying the record can't be deleted appears saying which table has the association.  It would be helpful to know not only the record associated, but be able to go to the record(s) to investigate.  In the case of dependent tables, it would be helpful to be taken to the main record.  For example, when I tried to delete a reference work that was associated to a collection object via collection object citation, the pop up said I couldnt' delete because the RW was associated with a CO Citation.  It would be more helpful to go to the CO in that instance than the CO Citation.
![image](https://user-images.githubusercontent.com/12532430/170743675-d6932dae-4ddc-4154-9537-2e9adf2c508e.png)

**Comment by maxxxxxdlp** [comment] 2022-05-28 02:27
Duplicate of #1689. I would close that one in favor of this one.

> Make delete blockers dialog friendlier
At the very least, the mapping path should use localized labels and table icons. Ideally, there should also be a button to open the related resources. ![image](https://user-images.githubusercontent.com/40512816/170146891-aef2a990-b5ae-4414-bb66-0893ed35fc6b.png)
> 
> It might even be desirable to have a button to cascade delete all related resources

**Closed** 2022-09-27 03:05 UTC
Labels: type:enhance, pri:unknown
