### ISSUE TITLE
[a11y] Chaning a Specify User's field values do not prompt Save 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1504] opened 2022-05-10 18:45 UTC
![msedge_KhCWe6hetY](https://user-images.githubusercontent.com/37256050/167700098-a5e34c4f-ba6c-4aa4-9ab4-db30b1664b20.gif)

![msedge_SVSfMJlAD2](https://user-images.githubusercontent.com/37256050/167700146-f7e173b4-acf4-4a5e-bf35-d4999e0e2799.gif)

Changing the User Group or adding a user to a role prompt the **Save** option to become usable.

db: colorado_paleo
username: topdog_CUpaleo

**Comment by maxxxxxdlp** [comment] 2022-05-10 21:28
Duplicate of #1480

**Closed by maxxxxxdlp** 2022-05-10 21:28 UTC
Labels: type:bug, pri:unknown
