### ISSUE TITLE
`UnicodeDecodeError` when accessing a specific view set

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2681] opened 2022-12-16 14:02 UTC
```
UnicodeDecodeError at /api/specify/spappresourcedata/
'utf-8' codec can't decode byte 0x86 in position 10: invalid start byte
```

https://herbrbge6802-edge-2.test.specifysystems.org/specify/resources/view-set/3/

This is the view set named "Common".

[Specify 7 Crash Report - 2022-12-16T13_56_39.401Z.txt](https://github.com/specify/specify7/files/10246308/Specify.7.Crash.Report.-.2022-12-16T13_56_39.401Z.txt)

Same error on `v7.7.5`:
https://herbrbge6802-v775.test.specifysystems.org/specify/viewsets/3/

---

On `sandbox-rbge` on the EU cloud, another 500 error with presumably a similar cause:

https://sandbox-rbge.specifycloud.org/specify/resources/app-resource/30/

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/37256050/208114153-474d829f-4ab8-4bd5-91b9-8b331c967be7.png">

**Comment by maxxxxxdlp** [comment] 2022-12-16 14:05
Duplicate of #1202

**Closed by maxxxxxdlp** 2022-12-16 14:05 UTC
Labels: type:bug, pri:unknown
