### ISSUE TITLE
"No Address matches the given query." when saving agent

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#929] opened 2021-08-31 01:26 UTC
When I edited an existing agent and wanted to save it, the server responded with a 500 status code and a text response "No Address matches the given query."

I have been able to reduce the payload of the request object and still reproduce the error:
```js
fetch("http://localhost/api/specify/agent/54/", {
  "headers": {
    "x-csrftoken": "vWClfdv16NT8PPS3yzhkM8h1frw17IOcNeGg2Dzi0cNikqPImTehBBOej3AkZsZz",
  },
  "referrer": "http://localhost/specify/view/collectionobject/47359/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": JSON.stringify({
  "id": 54,
  "agenttype": 2,
  "lastname": "1",
  "url": "1",
  "version": 9,
  "resource_uri": "/api/specify/agent/54/",
  "addresses": [
    {
      "id": 772,
      "version": 2,
      "agent": "/api/specify/agent/54/",
      "createdbyagent": "/api/specify/agent/1/",
      "modifiedbyagent": "/api/specify/agent/1/",
      "divisions": "/api/specify/division/?address=772",
      "insitutions": "/api/specify/institution/?address=772",
      "resource_uri": "/api/specify/address/772/"
    }
  ],
}),
  "method": "PUT",
  "mode": "cors",
  "credentials": "include"
});
```

Replicated in the `Paleontological Research Institute` database (`UpdatedTo6801.sql` file)

Here is the original request object:
```js
fetch("http://localhost/api/specify/agent/54/", {
  "headers": {
    "accept": "application/json, text/javascript, */*; q=0.01",
    "accept-language": "en-US,en;q=0.9,uk;q=0.8",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Chromium\";v=\"94\", \"Google Chrome\";v=\"94\", \";Not A Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-csrftoken": "vWClfdv16NT8PPS3yzhkM8h1frw17IOcNeGg2Dzi0cNikqPImTehBBOej3AkZsZz",
    "x-requested-with": "XMLHttpRequest"
  },
  "referrer": "http://localhost/specify/view/collectionobject/47359/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": JSON.stringify({
  "id": 54,
  "abbreviation": "1",
  "agenttype": 2,
  "date1": null,
  "date1precision": null,
  "date2": null,
  "date2precision": null,
  "dateofbirth": null,
  "dateofbirthprecision": null,
  "dateofdeath": "1111-11-01",
  "dateofdeathprecision": 2,
  "datetype": null,
  "email": "1",
  "firstname": "1",
  "guid": "6d39515f-2e29-49c7-975b-bdf2a4c606f0",
  "initials": "1",
  "integer1": null,
  "integer2": null,
  "interests": "Not Approved Borrower",
  "jobtitle": "1",
  "lastname": "1",
  "middleinitial": "1",
  "remarks": "1",
  "suffix": "1",
  "text1": null,
  "text2": null,
  "text3": null,
  "text4": null,
  "text5": null,
  "timestampcreated": "2015-03-06T15:35:04",
  "timestampmodified": "2020-11-24T17:13:58",
  "title": "Ms.",
  "url": "1",
  "verbatimdate1": null,
  "verbatimdate2": null,
  "version": 9,
  "collcontentcontact": null,
  "colltechcontact": null,
  "createdbyagent": "/api/specify/agent/1/",
  "division": "/api/specify/division/2/",
  "instcontentcontact": null,
  "insttechcontact": null,
  "modifiedbyagent": "/api/specify/agent/1/",
  "organization": null,
  "specifyuser": null,
  "orgmembers": "/api/specify/agent/?organization=54",
  "collectors": "/api/specify/collector/?agent=54",
  "members": "/api/specify/groupperson/?member=54",
  "resource_uri": "/api/specify/agent/54/",
  "addresses": [
    {
      "id": 772,
      "address": "1",
      "address2": "1",
      "address3": "1",
      "address4": "1",
      "address5": null,
      "city": "1",
      "country": "1",
      "enddate": null,
      "fax": "11",
      "iscurrent": true,
      "isprimary": true,
      "isshipping": true,
      "ordinal": 0,
      "phone1": "1",
      "phone2": "1",
      "positionheld": null,
      "postalcode": "1",
      "remarks": null,
      "roomorbuilding": "1",
      "startdate": null,
      "state": "1",
      "timestampcreated": "2017-11-29T15:54:05",
      "timestampmodified": "2017-11-29T15:54:05",
      "typeofaddr": null,
      "version": 2,
      "agent": "/api/specify/agent/54/",
      "createdbyagent": "/api/specify/agent/1/",
      "modifiedbyagent": "/api/specify/agent/1/",
      "divisions": "/api/specify/division/?address=772",
      "insitutions": "/api/specify/institution/?address=772",
      "resource_uri": "/api/specify/address/772/"
    },
    {
      "id": 873,
      "address": "1",
      "address2": "1",
      "address3": "1",
      "address4": "1",
      "address5": null,
      "city": "1",
      "country": "1",
      "enddate": null,
      "fax": "1",
      "iscurrent": true,
      "isprimary": true,
      "isshipping": true,
      "ordinal": 2,
      "phone1": "1",
      "phone2": "1",
      "positionheld": null,
      "postalcode": "1",
      "remarks": null,
      "roomorbuilding": "1",
      "startdate": null,
      "state": "1",
      "timestampcreated": "2020-11-24T17:13:08",
      "timestampmodified": "2020-11-24T17:13:08",
      "typeofaddr": null,
      "version": 1,
      "agent": "/api/specify/agent/54/",
      "createdbyagent": "/api/specify/agent/1/",
      "modifiedbyagent": "/api/specify/agent/1/",
      "divisions": "/api/specify/division/?address=873",
      "insitutions": "/api/specify/institution/?address=873",
      "resource_uri": "/api/specify/address/873/"
    }
  ],
  "agentattachments": [
    {
      "id": 27,
      "ordinal": 0,
      "remarks": null,
      "timestampcreated": "2019-11-08T11:32:26",
      "timestampmodified": "2019-11-08T11:32:26",
      "version": 0,
      "agent": "/api/specify/agent/54/",
      "attachment": {
        "id": 33505,
        "attachmentlocation": "sp67242810630200668681.att.pdf",
        "attachmentstorageconfig": null,
        "capturedevice": null,
        "copyrightdate": null,
        "copyrightholder": null,
        "credit": null,
        "dateimaged": null,
        "filecreateddate": null,
        "guid": "38e2bb6a-fcca-4655-a4f6-0abe46658070",
        "ispublic": false,
        "license": null,
        "licenselogourl": null,
        "metadatatext": null,
        "mimetype": "application/pdf",
        "origfilename": "K:\\Collections\\COLLECTIONS ARCHIVES\\Digitized Documents and Photos\\Approved Borrower scans\\Durham_approved_borrower_2017.pdf",
        "remarks": null,
        "scopeid": 2,
        "scopetype": 2,
        "subjectorientation": null,
        "subtype": null,
        "tableid": 5,
        "timestampcreated": "2019-11-08T11:32:26",
        "timestampmodified": "2019-11-08T11:32:26",
        "title": "Durham_approved_borrower_2017",
        "type": null,
        "version": 1,
        "visibility": null,
        "attachmentimageattribute": null,
        "createdbyagent": "/api/specify/agent/1157/",
        "creator": null,
        "modifiedbyagent": null,
        "visibilitysetby": null,
        "accessionattachments": "/api/specify/accessionattachment/?attachment=33505",
        "agentattachments": "/api/specify/agentattachment/?attachment=33505",
        "metadata": "/api/specify/attachmentmetadata/?attachment=33505",
        "tags": "/api/specify/attachmenttag/?attachment=33505",
        "borrowattachments": "/api/specify/borrowattachment/?attachment=33505",
        "collectingeventattachments": "/api/specify/collectingeventattachment/?attachment=33505",
        "collectingtripattachments": "/api/specify/collectingtripattachment/?attachment=33505",
        "collectionobjectattachments": "/api/specify/collectionobjectattachment/?attachment=33505",
        "conservdescriptionattachments": "/api/specify/conservdescriptionattachment/?attachment=33505",
        "conserveventattachments": "/api/specify/conserveventattachment/?attachment=33505",
        "dnasequenceattachments": "/api/specify/dnasequenceattachment/?attachment=33505",
        "dnasequencingrunattachments": "/api/specify/dnasequencingrunattachment/?attachment=33505",
        "deaccessionattachments": "/api/specify/deaccessionattachment/?attachment=33505",
        "disposalattachments": "/api/specify/disposalattachment/?attachment=33505",
        "fieldnotebookattachments": "/api/specify/fieldnotebookattachment/?attachment=33505",
        "fieldnotebookpageattachments": "/api/specify/fieldnotebookpageattachment/?attachment=33505",
        "fieldnotebookpagesetattachments": "/api/specify/fieldnotebookpagesetattachment/?attachment=33505",
        "giftattachments": "/api/specify/giftattachment/?attachment=33505",
        "loanattachments": "/api/specify/loanattachment/?attachment=33505",
        "localityattachments": "/api/specify/localityattachment/?attachment=33505",
        "permitattachments": "/api/specify/permitattachment/?attachment=33505",
        "preparationattachments": "/api/specify/preparationattachment/?attachment=33505",
        "referenceworkattachments": "/api/specify/referenceworkattachment/?attachment=33505",
        "repositoryagreementattachments": "/api/specify/repositoryagreementattachment/?attachment=33505",
        "storageattachments": "/api/specify/storageattachment/?attachment=33505",
        "taxonattachments": "/api/specify/taxonattachment/?attachment=33505",
        "treatmenteventattachments": "/api/specify/treatmenteventattachment/?attachment=33505",
        "resource_uri": "/api/specify/attachment/33505/"
      },
      "createdbyagent": "/api/specify/agent/1157/",
      "modifiedbyagent": null,
      "resource_uri": "/api/specify/agentattachment/27/"
    }
  ],
  "agentgeographies": [],
  "agentspecialties": [],
  "variants": [
    {
      "agent": "/api/specify/agent/54/",
      "vartype": 3,
      "name": "1"
    }
  ],
  "groups": []
}),
  "method": "PUT",
  "mode": "cors",
  "credentials": "include"
});

```

**Comment by maxxxxxdlp** [comment] 2021-08-31 14:18
I got this error again in a blank database when assigning an agent to user:

```js
fetch("http://localhost/api/specify/agent/2/", {
  "headers": {
    "accept": "application/json, text/javascript, */*; q=0.01",
    "accept-language": "en-US,en;q=0.9,uk;q=0.8",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Chromium\";v=\"94\", \"Google Chrome\";v=\"94\", \";Not A Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-csrftoken": "wKQ0T0HnXMkiEQjNdykGQOxKxCdQERsj8Hvjii0vEamz4hhgYauuqw452jRTnf6G",
    "x-requested-with": "XMLHttpRequest"
  },
  "referrer": "http://localhost/specify/view/specifyuser/2/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": JSON.stringify({
  "id": 2,
  "abbreviation": "2",
  "agenttype": 2,
  "date1": null,
  "date1precision": null,
  "date2": null,
  "date2precision": null,
  "dateofbirth": null,
  "dateofbirthprecision": null,
  "dateofdeath": null,
  "dateofdeathprecision": null,
  "datetype": null,
  "email": "2",
  "firstname": "2",
  "guid": "70af83e4-f51f-4987-b678-d2d4a36bbb71",
  "initials": null,
  "integer1": null,
  "integer2": null,
  "interests": null,
  "jobtitle": null,
  "lastname": "2",
  "middleinitial": "2",
  "remarks": null,
  "suffix": null,
  "text1": null,
  "text2": null,
  "text3": null,
  "text4": null,
  "text5": null,
  "timestampcreated": "2021-08-31T14:16:03",
  "timestampmodified": "2021-08-31T14:16:03",
  "title": "mrs",
  "url": null,
  "verbatimdate1": null,
  "verbatimdate2": null,
  "version": 0,
  "collcontentcontact": null,
  "colltechcontact": null,
  "createdbyagent": "/api/specify/agent/1/",
  "division": "/api/specify/division/2/",
  "instcontentcontact": null,
  "insttechcontact": null,
  "modifiedbyagent": null,
  "organization": null,
  "specifyuser": "/api/specify/specifyuser/2/",
  "orgmembers": "/api/specify/agent/?organization=2",
  "collectors": "/api/specify/collector/?agent=2",
  "members": "/api/specify/groupperson/?member=2",
  "resource_uri": "/api/specify/agent/2/",
  "addresses": [
    {
      "id": 2,
      "address": "2",
      "address2": "2",
      "address3": null,
      "address4": null,
      "address5": null,
      "city": "2",
      "country": "2",
      "enddate": null,
      "fax": "2",
      "iscurrent": null,
      "isprimary": true,
      "isshipping": null,
      "ordinal": 0,
      "phone1": "2",
      "phone2": "2",
      "positionheld": null,
      "postalcode": "2",
      "remarks": null,
      "roomorbuilding": "2",
      "startdate": null,
      "state": "2",
      "timestampcreated": "2021-08-31T14:16:03",
      "timestampmodified": "2021-08-31T14:16:03",
      "typeofaddr": null,
      "version": 0,
      "agent": "/api/specify/agent/2/",
      "createdbyagent": "/api/specify/agent/1/",
      "modifiedbyagent": null,
      "divisions": "/api/specify/division/?address=2",
      "insitutions": "/api/specify/institution/?address=2",
      "resource_uri": "/api/specify/address/2/"
    }
  ],
  "agentattachments": [],
  "agentgeographies": [],
  "agentspecialties": [
    {
      "id": 1,
      "ordernumber": 0,
      "specialtyname": "2",
      "timestampcreated": "2021-08-31T14:16:03",
      "timestampmodified": "2021-08-31T14:16:03",
      "version": 0,
      "agent": "/api/specify/agent/2/",
      "createdbyagent": "/api/specify/agent/1/",
      "modifiedbyagent": null,
      "resource_uri": "/api/specify/agentspecialty/1/"
    }
  ],
  "variants": [
    {
      "id": 1,
      "country": null,
      "language": null,
      "name": "2",
      "timestampcreated": "2021-08-31T14:16:03",
      "timestampmodified": "2021-08-31T14:16:03",
      "vartype": 4,
      "variant": null,
      "version": 0,
      "agent": "/api/specify/agent/2/",
      "createdbyagent": "/api/specify/agent/1/",
      "modifiedbyagent": null,
      "resource_uri": "/api/specify/agentvariant/1/"
    }
  ],
  "groups": []
}),
  "method": "PUT",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by benanhalt** [comment] 2021-08-31 15:18
How are you generating these requests?

**Comment by maxxxxxdlp** [comment] 2021-08-31 15:27
These requests are generated by Specify's front end. I just go to Chrome's DevTools and press "Copy as NodeJS fetch" in the context menu for those requests

**Comment by melton-jason** [comment] 2023-01-13 23:00
> > Here is the decision we have reached regarding the problematic Business Rule Exception which disallows Addresses being added to Agents of type Other and Group ([#2518 (comment)](https://github.com/specify/specify7/issues/2518#issuecomment-1347039470))
> > The Business Rule will be removed in Specify 7. Before the Specify 6 release ([specify/specify6#1189](https://github.com/specify/specify6/pull/1189)), I will remove it there as well (if the removal does not cause major problems). The BusinessRule will be removed from Specify 7 even if we can not safely/easily remove it in Specify 6
> 
> In [#2702 (comment)](https://github.com/specify/specify7/pull/2702#issuecomment-1381057692)

- From https://github.com/specify/specify7/issues/2518#issuecomment-1381058301


This is a duplicate of #2518

This was happening because there was a BusinessRule in place which deleted the Addresses when saving an Agent of type Other and Group.  This BusinessRule was removed in #2702 (https://github.com/specify/specify7/pull/2702/commits/3839b72b7b1218ac79e42df8d83e5c1d9ca8561b)

**Closed by melton-jason** 2023-01-13 23:00 UTC
Labels: type:bug, pri:unknown, back-end
