### ISSUE TITLE
Report broken in `edge`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4515] opened 2024-02-09 22:04 UTC
**Describe the bug**
At least one report does not work in `edge` but does in `v7.9.3`

**To Reproduce**

1. Go to 
    a. https://umherb11024-edge.test.specifysystems.org/specify/view/collectionobject/228767/?recordsetid=8500
    b. https://umherb11024-v793.test.specifysystems.org/specify/view/collectionobject/228767/?recordsetid=8500
2. Use the 'Generate Label' button to print `SpecimenLabels`
3. See that there is an error on `edge` and not on `v7.9.3`

`waltersb` user on `umherb_1_10_24`
https://umherb11024-edge.test.specifysystems.org/specify/resources/app-resource/26/

https://github.com/specify/specify7/assets/37256050/6d56d3af-a4b8-416a-8637-ee60b48a2e57

**Comment by melton-jason** [comment] 2024-02-27 23:11
This is a duplicate of #3690, and was fixed in `v7.8.13` in #3693. 

The cause of #3690 is that the frontend was _always_ inserting an `xml` declaration to the top of the report (`jrxml` file)  when parsing it (even when the file already contained the declaration) and sending the modified file content to the report runner, which can not handle the declaration. 
This bug is very likely front-end only and should require finding where the extra declaration is being added to the report and ensuring a declaration is only added if it already does not exist in the file.

**Closed** 2024-03-05 18:18 UTC
Labels: 1 - Bug, 2 - Reports
