### ISSUE TITLE
Paleo Map Error Messgae

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3427] opened 2023-04-27 20:52 UTC
**Describe the bug**
The message talks about a Collecting Event form when the real problem is that the button requires a Locality to be entered first.

**To Reproduce**
1. Go to a Database with Paleo Button. EG morpaleo 
2. Click on `Data Entry -> Collection Object`
3. Click `Paleo Map` Button

**Expected behavior**
Would be preferable if it talked about filling in the relevant fields or saving the object.

**Screenshots**
<img width="1193" alt="Screenshot 2023-04-27 at 3 18 26 PM" src="https://user-images.githubusercontent.com/53784701/234986732-b70de4bf-7133-4faa-97f6-f22d7e4a60bc.png">

**Resolved By Filling In Fields Nothing Else**
<img width="1166" alt="Screenshot 2023-04-27 at 3 38 25 PM" src="https://user-images.githubusercontent.com/53784701/234988047-9abcad41-0f06-41b7-9332-a8871c78f001.png">

Desktop:
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

Database Name: morpaleo

Reported By
@carlosmbe

**Comment by grantfitzsimmons** [comment] 2023-04-28 01:50
Duplicate of https://github.com/specify/specify7/issues/3350

**Closed by grantfitzsimmons** 2023-04-28 01:50 UTC
Labels: type:bug, pri:unknown
