### ISSUE TITLE
Taxon name ranks should be able to be set as default

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1120] opened 2021-12-16 14:04 UTC
When adding a new name, it should be possible for chosen ranks to be the default. Currently, you have to sort through infrageneric ranks before you can select the direct child of the parent. 
_Example: When adding a new Species under Genus, Species should be at the top of the list._

Setting Genus to be enforced did not impact the order of ranks displayed when attempting to add a family. There does not appear to be an option in the UI to change this behavior.

**Reported By:** Edinburgh & Geneva

**Comment by maxxxxxdlp** [comment] 2022-04-15 22:39
Duplicate of https://github.com/specify/specify7/issues/345
See https://github.com/specify/specify7/issues/345#issuecomment-1025840646

**Closed** 2022-05-17 23:28 UTC
Labels: type:enhance, pri:unknown
