### ISSUE TITLE
Report Query Returned No Results

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3773] opened 2023-07-12 19:49 UTC
**Describe the bug**
This is a quite the strange bug. I don't understand what's causing it so please forgive the rather vague explanations.

Talk to @melton-jason for more details.

**To Reproduce**
1. Go to `Clean NHMD` Log in as `petrifiedroadkill` and go to the `NHMD Amber` Collection
2. Find the first loan created in it. Namely `Loan: 2023-EN-001` or just use the link below
3. Make some changes or just clone
4. Experiment with either Generate Invoice on Save being on/off
5. See error

Link to loan
cleannhmdtest030823copy-v79-dev.test.specifysystems.org/specify/view/loan/224/

Make up sure you have pop ups enabled on the page.

One of three things could happen when saving the loan:
1. It works
2. Report Query Returned No Results
3. An NS_Error is thrown

**Expected behavior**
It always works

**Beautiful Pictures**

<img width="339" alt="Screenshot 2023-07-12 at 2 42 00 PM" src="https://github.com/specify/specify7/assets/53784701/d13f109d-378b-49de-8bf4-58146d21edd9">

<img width="1789" alt="Screenshot 2023-07-12 at 2 14 34 PM" src="https://github.com/specify/specify7/assets/53784701/4ffd3119-4c76-4feb-a76b-0c2504ac04ff">

https://github.com/specify/specify7/assets/53784701/55e1b96c-d744-4d1c-9937-cd91fb36d44c

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by grantfitzsimmons** [comment] 2023-07-12 20:33
@carlosmbe Make sure that you recreate any issue on `v7.9` on `v7.8.13` so that we have a baseline to compare it to so that we can accurately assess priority!

Can you try to recreate this in the previous version?

**Comment by maxxxxxdlp** [comment] 2023-07-13 02:20
The issue looks like an internal firefox error message (not a javascript error message)

Duplicate of #3115

**Closed by maxxxxxdlp** 2023-07-13 02:20 UTC
Labels: 1 - Bug, 2 - Reports

**Comment by carlosmbe** [comment] 2023-07-13 19:55
Not exclusive to Firefox, recreated in Chrome.

Moreover, recreated in 7.8.13 and 7.9 @grantfitzsimmons

**Comment by maxxxxxdlp** [comment] 2023-07-14 01:35
Really, @grantfitzsimmons did this happen for you in Chrome?

I can only find reports online of this happening in Firefox (and VirtualBox lol)

They even have an open bug for this on their side - https://bugzilla.mozilla.org/show_bug.cgi?id=941146
