### ISSUE TITLE
Formatted Queries being saved as unmapped due to column alias becoming null

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3468] opened 2023-05-08 20:00 UTC
**Describe the bug**
This seems to be happen because a value that shouldn't be `formatted` is formatted either through a double click or importing a 6 query.

In the `Updated PriPaleo` Database. Some queries are displayed as unmapped as Specify is making their `Column Alias` value null. However, they are not actually unmapped as they still work fine.

Go to `Sp7 Made Taxon Query` and observe.
<img width="1791" alt="Screenshot 2023-05-08 at 2 42 52 PM" src="https://user-images.githubusercontent.com/53784701/236918218-4d2bb0c1-810b-47f2-a85c-08d24b435cde.png">

<img width="1791" alt="Screenshot 2023-05-08 at 2 43 02 PM" src="https://user-images.githubusercontent.com/53784701/236918212-29a3c5e7-23ac-43e8-bced-5d7399cf2b0e.png">

**To Reproduce**
Watch Video. 
All fields are added by double click

https://user-images.githubusercontent.com/53784701/236920763-6e382136-8ac7-4dbc-a0cd-ab1afbd5950c.mov

**Note** that `fieldname` has an extra space this time and that `columnalias` is null when it shouldn't be
```
....
"id": 4323,
			"allownulls": null,
			"alwaysfilter": null,
			"columnalias": null,
			"contexttableident": null,
			"endvalue": null,
			"fieldname": "Kingdom ",
			"formatname": null,
			"isdisplay": true,
			.....
```

**Expected behavior**
That the name remains and that it is not changed to `unmapped`

**Comment by maxxxxxdlp** [comment] 2023-05-08 20:05
Seems like a duplicate of #3467. I will merge them

**Closed as not planned by maxxxxxdlp** 2023-05-08 20:05 UTC
Labels: 1 - Bug
