### ISSUE TITLE
Pick list throws size limit issue when the limit is larger than the quantity of items

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2138] opened 2022-09-13 00:00 UTC
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/37256050/189778900-4972ab3e-1124-4b63-9f37-7e1d57c2d4d1.png">

This has happened infrequently to me in the past. It is difficult to recreate, but in this case,
This was a pick list with a size limit of 8.
1. Remove all 7 items from the picklist.
2. Add 7 new items
3. See error

`newmexico_august22` on `edge`

**Comment by maxxxxxdlp** [comment] 2022-10-21 14:59
Duplicate of https://github.com/specify/specify7/issues/1025
Already fixed

**Closed by maxxxxxdlp** 2022-10-21 14:59 UTC
Labels: type:bug, pri:unknown, back-end
