### ISSUE TITLE
Editing a user role loses unsaved data

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1798] opened 2022-07-06 14:53 UTC
<img width="894" alt="image" src="https://user-images.githubusercontent.com/37256050/177579655-06fc6bc2-f1b4-4745-b7fe-b0c40abe6456.png">

When you click on the pencil next to the assigned user role, all information entered is lost since there is no warning before it navigates away from the form.

**Comment by maxxxxxdlp** [comment] 2022-07-06 14:55
There are several issues of this type in the security panel.

The issue is that the security panel is not integrated with the app's router (you can notice that by the fact that page URL does not change as you switch between pages in the security panel)

This would be fixed in 7.8.0 with the introduction of a modern routing system.

**Comment by maxxxxxdlp** [comment] 2022-08-01 01:44
Fixed in [1ef88f26](https://github.com/specify/specify7/commit/1ef88f2652f0b20c8b16d82039096984bf2980db)

**Closed** 2022-09-28 02:02 UTC
Labels: type:bug, pri:unknown
