### ISSUE TITLE
Query builder loses Taxon rank name after save

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3467] opened 2023-05-08 19:51 UTC
**Left:** Created in Specify 7
**Right:** Created in Specify 6

<img width="1699" alt="image" src="https://user-images.githubusercontent.com/37256050/236918907-446e3993-f43c-4123-b6aa-bbaca78dbe19.png">

When creating a new query on Taxon from scratch, the following data is saved in the field ([link](https://pripaleoschemaupdatedcm202304211540-v7810-prerelease.test.specifysystems.org/specify/query/243/)):

```json
	"fields": [
		{
			"id": 4307,
			"allownulls": null,
			"alwaysfilter": null,
			"columnalias": null,
			"contexttableident": null,
			"endvalue": null,
			"fieldname": "Kingdom ",
```

When the query is created in Specify 6 and viewed in Specify 7 ([link](https://pripaleoschemaupdatedcm202304211540-v7810-prerelease.test.specifysystems.org/specify/query/242/)):

```json
	"fields": [
		{
			"id": 4291,
			"allownulls": null,
			"alwaysfilter": false,
			"columnalias": "Kingdom",
			"contexttableident": 4,
			"endvalue": null,
			"fieldname": "Kingdom",

```

Notice that `"columnalias"` is missing from the Specify 7 query's JSON. 

[Specify Queries JSON files.zip](https://github.com/specify/specify7/files/11424623/Archive.zip)

When creating the query from scratch (just by double-clicking each of the Taxon ranks and saving) in `v7.8.10`, saving results in the Taxon rank section becoming "NOT MAPPED".

See below:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/37256050/236919924-63404823-eef3-435b-b93c-23f5a4631090.png">

The query runs correctly.

**Comment by maxxxxxdlp** [comment] 2023-05-08 20:03
Sp7 does not look at `columnalias` at all. This bug must be caused by something else
Can you please try to replicate your fix on https://github.com/specify/specify7/pull/3026?
If it's not fixed there yet, it should be fixed on that branch as that branch added tests for cases like this

**Closed** 2023-11-29 21:20 UTC
Labels: 1 - Bug, 2 - Queries
