### ISSUE TITLE
Duplicate entry error when saving an additional preparation with the same `barCode`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2563] opened 2022-12-08 03:19 UTC
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/37256050/206347457-5beaddc0-36f6-40ae-aee9-4083fee387f9.png">

[Specify 7 Crash Report - 2022-12-08T03_16_55.589Z.txt](https://github.com/specify/specify7/files/10181769/Specify.7.Crash.Report.-.2022-12-08T03_16_55.589Z.txt)

This issue occured when adding a new preparation to the record with a barcode that is already in use. You can recreate by creating a new prep with the barcode ``123`.

https://herbrbge6802-edge.test.specifysystems.org/specify/view/collectionobject/151675/

**Comment by maxxxxxdlp** [comment] 2022-12-08 18:42
Potentially related to #108

**Comment by melton-jason** [comment] 2023-03-22 02:46
This is actually a duplicate of #2886 and #2061. 
`Preparation.barCode` was not a uniqueness rule on either the frontend or the backend.

The tricky part is that _making_ this a uniqueness rule will require more work than other cases. 
See https://github.com/specify/specify7/issues/2061#issuecomment-1439391935 for a more detailed breakdown

**Closed** 2023-03-22 02:50 UTC
Labels: type:bug, res:duplicate, pri:unknown
