### ISSUE TITLE
Cannot leave fullscreen in GeoMap

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4519] opened 2024-02-11 19:07 UTC
**Describe the bug**
Once you enter full screen in GeoMap, you can't escape.

**To Reproduce**

1. Run a query (https://umherb11024-edge.test.specifysystems.org/specify/query/fromtree/taxon/109665/)
2. Use the 'GeoMap' button to map all the points in the query
3. Use the full screen button
4. Try to leave full screen
5. See issue

https://github.com/specify/specify7/assets/37256050/8d49c6bf-aa9e-491b-a003-346d0e4f73ba

**Comment by CarolineDenis** [comment] 2024-02-12 22:25
This is actually a duplicate of: https://github.com/specify/specify7/issues/4385
The dialog leaves full screen but since it keeps the previous dimensions it stays wide

**Comment by CarolineDenis** [comment] 2024-02-13 16:14
Duplicate of: https://github.com/specify/specify7/issues/4385

**Comment by emenslin** [comment] 2024-03-21 16:37
Can still get stuck in GeoMap full screen. Dialog does not overflow however when minimizing screen so that aspect was fixed from the PR that is linked. 

https://github.com/specify/specify7/assets/150940840/4ed3f0a5-ae34-417a-acc1-32d9a7a75960

https://lsumzmammals9823-edge.test.specifysystems.org/specify/query/42/

**Closed** 2024-03-22 13:24 UTC
Labels: 1 - Bug, 2 - User Interface
