### ISSUE TITLE
[a11y] Remove header row from formTable when no records present

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1228] opened 2022-04-15 02:36 UTC
**Describe the bug**
Column headers for a grid view appear in form view (specifically for Preparations). These should only be visible when grid editing in the form viewer.

**To Reproduce**
1. Create a CO
2. View error

**Screenshots**
No Preparations:
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/37256050/163508957-2faaece4-67be-4e1a-90d9-a170021ba318.png">

Blank preparation form view:
![image](https://user-images.githubusercontent.com/37256050/163508814-3435ddb7-d251-4ca9-8f47-ebf94c380315.png)

Bug is present somewhat on edge:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/37256050/163508932-a8ce1a50-6763-49e4-83f3-1d94d248a1cf.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari, Edge

**Comment by maxxxxxdlp** [comment] 2022-04-15 02:39
I believe this is the expected behavior.
Keep in mind that there can be more than one record in a grid table (press the Add button) and most of the time none of those records are going to be expanded.

**Comment by grantfitzsimmons** [comment] 2022-04-15 02:44
It should only appear if in grid editing view correct? It displays redundant information when form editing and when not adding preparations.

**Comment by maxxxxxdlp** [comment] 2022-04-15 02:46
For reference, this is what it looks like in the current release?

<img width="1201" alt="Screen Shot 2022-04-14 at 21 45 39" src="https://user-images.githubusercontent.com/40512816/163509883-92891f7b-0e23-44f3-a97b-6ce290b9fd44.png">

And with one row expanded:
<img width="1201" alt="Screen Shot 2022-04-14 at 21 46 04" src="https://user-images.githubusercontent.com/40512816/163509911-f6e1254a-c41a-41bd-8a88-c378ebfbd9dd.png">

I don't think column headers are redundant there

**Comment by grantfitzsimmons** [comment] 2022-04-15 02:48
I see what you're referring to! Definitely should remove when no preparations are present. If it is simple it would be nice for those headings to only appear when there is a grid present, but if that's complicated or introduces more issues then it is not a priority.

**Comment by maxxxxxdlp** [comment] 2022-04-15 14:53
Fixed in [e415416](https://github.com/specify/specify7/commit/e415416f0869dabe265f44b8e8ea63d0750e8b74)

**Closed** 2022-05-20 01:51 UTC
Labels: type:bug, pri:unknown
