### ISSUE TITLE
Can't delete users

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1069] opened 2021-11-16 04:16 UTC
Reported by Gothenburg, confirmed in several databases on the test server using the "next-release" version.
When you click to delete a user a dialog comes up saying they couldn't be deleted.  Here is the error reported by Gothenburg:
Log from assigning collections:

specify7_1         | Traceback (most recent call last):

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner

specify7_1         |     response = get_response(request)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response

specify7_1         |     response = self.process_exception_by_middleware(e, request)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response

specify7_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)

specify7_1         |   File "/opt/specify7/specifyweb/specify/views.py", line 20, in wrapped

specify7_1         |     return view(request, *args, **kwargs)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner

specify7_1         |     return func(request, *args, **kwargs)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func

specify7_1         |     response = view_func(request, *args, **kwargs)

specify7_1         |   File "/opt/specify7/specifyweb/context/views.py", line 77, in user_collection_access

specify7_1         |     set_users_collections(cursor, user, collections)

specify7_1         |   File "/opt/specify7/specifyweb/context/views.py", line 49, in set_users_collections

specify7_1         |     cursor.execute('delete from spprincipal where grouptype is null and spprincipalid not in ('

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute

specify7_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

specify7_1         |     return executor(sql, params, many, context)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute

specify7_1         |     return self.cursor.execute(sql, params)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__

specify7_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute

specify7_1         |     return self.cursor.execute(sql)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute

specify7_1         |     return self.cursor.execute(query, args)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute

specify7_1         |     self.errorhandler(self, exc, value)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler

specify7_1         |     raise errorvalue

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute

specify7_1         |     res = self._query(query)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query

specify7_1         |     rowcount = self._do_query(q)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query

specify7_1         |     db.query(q)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query

specify7_1         |     _mysql.connection.query(self, query)

specify7_1         | django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`specify`.`spprincipal_sppermission`, CONSTRAINT `FK9DD8B2FA99A7381A` FOREIGN KEY (`SpPrincipalID`) REFERENCES `spprincipal` (`SpPrincipalID`))')

 

Log from deleting:

specify7_1         | Traceback (most recent call last):

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner

specify7_1         |     response = get_response(request)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response

specify7_1         |     response = self.process_exception_by_middleware(e, request)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response

specify7_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)

specify7_1         |   File "/opt/specify7/specifyweb/specify/views.py", line 20, in wrapped

specify7_1         |     return view(request, *args, **kwargs)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled

specify7_1         |     response = viewfunc(request, *args, **kw)

specify7_1         |   File "/opt/specify7/specifyweb/specify/views.py", line 32, in wrapped

specify7_1         |     return view(request, *args, **kwargs)

specify7_1         |   File "/opt/specify7/specifyweb/specify/views.py", line 62, in view

specify7_1         |     return dispatch_func(request, *args, **kwargs)

specify7_1         |   File "/opt/specify7/specifyweb/specify/api.py", line 118, in resource_dispatch

specify7_1         |     delete_resource(request.specify_user_agent, model, id, version)

specify7_1         |   File "/usr/lib/python3.6/contextlib.py", line 52, in inner

specify7_1         |     return func(*args, **kwds)

specify7_1         |   File "/opt/specify7/specifyweb/specify/api.py", line 545, in delete_resource

specify7_1         |     return delete_obj(agent, obj, version)

specify7_1         |   File "/opt/specify7/specifyweb/specify/api.py", line 560, in delete_obj

specify7_1         |     obj.delete()

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/models/base.py", line 919, in delete

specify7_1         |     return collector.delete()

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/models/deletion.py", line 289, in delete

specify7_1         |     sender=model, instance=obj, using=self.using

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send

specify7_1         |     for receiver in self._live_receivers(sender)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>

specify7_1         |     for receiver in self._live_receivers(sender)

specify7_1         |   File "/opt/specify7/specifyweb/businessrules/user_rules.py", line 32, in deleting_user

specify7_1         |     cursor.execute('delete from spprincipal where grouptype is null and spprincipalid not in ('

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute

specify7_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

specify7_1         |     return executor(sql, params, many, context)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute

specify7_1         |     return self.cursor.execute(sql, params)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__

specify7_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute

specify7_1         |     return self.cursor.execute(sql)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute

specify7_1         |     return self.cursor.execute(query, args)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute

specify7_1         |     self.errorhandler(self, exc, value)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler

specify7_1         |     raise errorvalue

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute

specify7_1         |     res = self._query(query)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query

specify7_1         |     rowcount = self._do_query(q)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query

specify7_1         |     db.query(q)

specify7_1         |   File "/opt/specify7/ve/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query

specify7_1         |     _mysql.connection.query(self, query)

specify7_1         | django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`specify`.`spprincipal_sppermission`, CONSTRAINT `FK9DD8B2FA99A7381A` FOREIGN KEY (`SpPrincipalID`) REFERENCES `spprincipal` (`SpPrincipalID`))')

**Comment by grantfitzsimmons** [comment] 2022-09-02 19:03
Is this still open?

**Comment by maxxxxxdlp** [comment] 2022-09-02 20:59
This is probably still an issue.

The error message refers to the Specify 6 permission tables.

Seems like Sp7 should delete records from those tables when deleting a user.

**Comment by grantfitzsimmons** [comment] 2022-10-27 13:21
Reported by Charles at Cornell as well.

**Comment by benanhalt** [comment] 2022-10-27 16:39
The first stack trace looks like #1161 which should be fixed. The second stack trace appears to be a different issue and is likely still a bug.

**Comment by mc0822** [comment] 2022-12-19 20:21
Reported by Cameron Wood, Cranbrook Institute of Science, too.

**Comment by grantfitzsimmons** [comment] 2022-12-19 20:33
@mc0822 This is not the issue that Cameron Wood is having– they are unable to delete a user because they have a query (or queries) that are owned by that user in the database.

![Screenshot 2022-12-19 at 08-51-10 Specify User Specify 7](https://user-images.githubusercontent.com/37256050/208515843-d23f087e-ee86-4c08-9d5c-5b398f887a24.png)

I reccomend including screenshots when adding to an issue as well, especially when they send them 🙂

**Comment by maxxxxxdlp** [comment] 2023-03-08 04:22
Closing this as a duplicate of #2784

**Closed by maxxxxxdlp** 2023-03-08 04:22 UTC
Labels: type:bug
