### ISSUE TITLE
Error when saving New CO after inputting existing ID value

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4359] opened 2024-01-04 18:16 UTC
**Describe the bug**
Error appears when saving a New Collection Object after entering in an existing unique value into the ID field. 

**To Reproduce**
1. Go to Data Entry ⇒ Collection Object (https://herbumass-edge.test.specifysystems.org/specify/view/collectionobject/new/)
2. Manually type in or paste existing CO ID without zeros from formatting (e.g. "1234" instead of "000001234") into ID field. 
3. Click off field and see that ID is automatically formatted. ("000001234")
4. Click Save
5. See error 
[Specify 7 Crash Report - 2024-01-04T16_29_09.518Z.txt](https://github.com/specify/specify7/files/13833917/Specify.7.Crash.Report.-.2024-01-04T16_29_09.518Z.txt)

**Expected behavior**
User should not be allowed to save and should be prompted with "Value must be unique to Collection".
![expected-behavior](https://github.com/specify/specify7/assets/118556884/845dd15a-0736-419b-8cd1-575cd29e1bb6)

**Evidence**

https://github.com/specify/specify7/assets/118556884/ea36c4c4-a63e-4f0b-8e23-67924eec4bce

**Additional info**
Only functions correctly when typing in or pasting the exact CO ID that includes formatted zeros. (0:17 - 0:24 in video)

**Desktop:**
- OS: macOS Monterey (12.6.5)
- Browser: Chrome
- Specify 7 Version: `edge`

**Database Name:**
tested on `herb_umass` and `lsumz`

**Comment by melton-jason** [comment] 2024-01-04 18:51
This is a duplicate of #2859 :sweat_smile: 

For a breakdown on why this happens, see https://github.com/specify/specify7/issues/2859#issuecomment-1468868462 (partially pasted below for convenience) 

The issue also occurs when adding a space to the end of the catalognumber (see https://github.com/specify/specify7/issues/2859#issuecomment-1675035327)

In short, the problem occurs because the code which parses/formats the field does not re-run the necessary business rule checks. 

> I was unable to recreate the issue specifically because of the way Specify handled formatting numeric catalognumbers for CollectionObjects:
> 
> Consider the numeric catalog number format for the collection: `#########`:
> 
> Here is a the process Specify takes in an example workflow:
> 
> 1. I enter `31300` into the Catalog Number field
> 2. The frontend asks the backend if `31300` is a unique catalog number
> 3. The backend then (correctly) tells the front end that there is not a CollectionObject with catalog number `31300`
> 4. The frontend then formats the catalognumber to the required format `000031300`
> 5. The frontend does not run the check on catalognumber again
> 
> To consistently reproduce:
> 
> 1. Go to https://umichmollusks20221222-edge.test.specifysystems.org/specify/view/collectionobject/new/
> 2. Enter `1` in the CatalogNumber field
> 
> * Note that there already exists a CollectionObject with CatalogNumber `1`
> 
> 3. See the front reports no errors
> 4. Make a change to the catalog number field (i.e., delete and re-add the `1` at the end of the catalog number)
> 5. See the front now correctly identifies the duplicate

**Closed by melton-jason** 2024-01-04 18:51 UTC
Labels: 1 - Bug
