### ISSUE TITLE
Warn the user that the worker is not running when when using the WorkBench

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2571] opened 2022-12-09 14:33 UTC
Currently the WorkBench just hangs on the validation or upload function if the [`worker`](https://github.com/specify/specify7#the-specify-7-worker) process is not running.

It would be nice to have some icon and tooltip (or something similar) that displays a warning if it pings the server and the worker is not running. Even if it is busy, it is helpful to have some indication.

There have been many instances where users ask support@specifysoftware.org for help due to this process not running. Without an indication for a user, it seems that the WorkBench is just always busy, even when it is definitely not the case.

**Comment by maxxxxxdlp** [comment] 2022-12-09 14:42
Duplicate of #2272. I will merge them

**Closed by maxxxxxdlp** 2022-12-09 14:42 UTC
Labels: type:enhance, pri:unknown
