### ISSUE TITLE
Project is not showing up on Collection Object data entry forms

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1172] opened 2022-03-04 18:42 UTC
Reported by UMich

they tried to add projects to the CO form, it appears in 6 but not in 7.
Code added:
cell type="subview" viewname="Project" id="proj" name="projects" initialize="btn=true"

error in the console:
unhandled relationship type: many-to-many

**Comment by grantfitzsimmons** [comment] 2023-08-07 03:18
Duplicate of https://github.com/specify/specify7/issues/2928

**Closed by grantfitzsimmons** 2023-08-07 03:18 UTC
Labels: 1 - Bug, 2 - Forms

**Comment by specifysoftware** [comment] 2023-10-20 15:57
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-vs-specify-7-feature-comparison/551/3
