### ISSUE TITLE
Geo Map: TypeError: cannot read undefined getNearObject 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3910] opened 2023-08-11 15:58 UTC
**Describe the bug**
I can't pinpoint the record causing this issue. However I have the query saved.

Go to NHMD -> NHMD Amber -> Queries -> KML Test

Make sure you remove any unmapped fields. Run the query and use the Geo Map Plug In. It should crash.

**Expected behavior**
No crush

**Beautiful Screen Recording**

https://github.com/specify/specify7/assets/53784701/93925035-6f40-43aa-a592-495bc97dff40

[Specify 7 Crash Report - 2023-08-11T14_10_46.005Z.txt](https://github.com/specify/specify7/files/12323198/Specify.7.Crash.Report.-.2023-08-11T14_10_46.005Z.txt)

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Database Name:** NHMD

**Comment by carlosmbe** [comment] 2023-08-11 15:59
Assuming I haven't shut down this instance here is a link
https://nhmdtest030823-v79-dev.test.specifysystems.org/specify/query/411/

**Comment by CarolineDenis** [comment] 2023-08-24 17:14
I cannot reproduce on the last version of 7.9-dev. Can you @carlosmbe ?

**Comment by carlosmbe** [comment] 2023-08-24 20:02
@CarolineDenis Fixed in Edge. Present in 7.9-Dev. Do you know which branch fixed it? For reference sake.

**Comment by CarolineDenis** [comment] 2023-08-24 20:26
I do not at this moment sorry

**Comment by grantfitzsimmons** [comment] 2024-04-26 20:17
Closing in favor of #4848

**Closed by grantfitzsimmons** 2024-04-26 20:17 UTC
Labels: 1 - Bug, 2 - Queries
