### ISSUE TITLE
[testability] Gift Kind picklist showing as invalid

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2282] opened 2022-10-04 01:22 UTC
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/193714288-381b8d4a-05c6-462e-8b83-eeeeb2b99f66.png">

`testability` - [Link](https://herbrbge-testability.test.specifysystems.org/specify/view/exchangeout/1/):
<img width="369" alt="image" src="https://user-images.githubusercontent.com/37256050/193714326-b5990382-e58a-4daa-b946-8e0d53bcda81.png">

`v773` - [Link](https://herbrbge-v773.test.specifysystems.org/specify/view/exchangeout/1/):
<img width="360" alt="image" src="https://user-images.githubusercontent.com/37256050/193714338-0729aa02-0e68-4f53-aaa6-b5491d338359.png">

**Comment by maxxxxxdlp** [comment] 2022-10-18 18:12
Seems to be fixed now (https://herbrbge-testability.test.specifysystems.org/specify/view/exchangeout/new/)

It was likely caused by the same problems as all those picklist issues in production. Since testability is now rebased to `v7.7.4`, the issue is resolved

![Screen Shot 2022-10-18 at 13 10 28](https://user-images.githubusercontent.com/40512816/196510709-f407a9f5-f7d7-49a7-b612-4802d5e6e0a4.png)

**Closed by maxxxxxdlp** 2022-10-18 18:12 UTC
Labels: type:bug, pri:unknown
