### ISSUE TITLE
Sorting by locality column header reveals hidden search fields in mapper

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3733] opened 2023-07-06 16:06 UTC
**Describe the bug**
When querying on any locality field (on any table) sorting by column header renders fields being searched in the background in the mapper. This then leads to the issue described in #3683 where those fields carry over after opening a new query through the side bar.

**To Reproduce**
1. Go to Query Builder
2. Choose locality table or other linked table
3. Add a locality field to mapper 
4. Click `Query`
5. Sort by the locality column header
6. See error

**Expected behavior**
Should simply sort the column without extra fields rendering in mapper.

**Screenshots**

https://github.com/specify/specify7/assets/135047322/df53956b-6594-4be9-9b80-1ff9f654ce7d

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version: 7.9-dev

**Database Name:** If applicable
herb_rbge_3_31_23

**Additional context**
Database name or any other context about the problem here.
Crash Report thrown after switching tables:
[Specify 7 Crash Report - 2023-07-06T15_30_55.572Z.txt](https://github.com/specify/specify7/files/11969903/Specify.7.Crash.Report.-.2023-07-06T15_30_55.572Z.txt)
- Just tested and am able to recreate in `v7.8.13` (my fault)

**Comment by bronwyncombs** [comment] 2023-07-06 16:55
More context: I believe this issue is the root of the problem with issue #3683. If that is the case they can be closed together

**Comment by CarolineDenis** [comment] 2023-07-06 18:55
Issue introduced in V7.8.0

**Comment by maxxxxxdlp** [comment] 2023-07-07 02:28
See https://github.com/specify/specify7/issues/3683#issuecomment-1624553415

**Comment by CarolineDenis** [comment] 2023-07-12 17:29
duplicate of https://github.com/specify/specify7/issues/3725

**Comment by grantfitzsimmons** [comment] 2023-07-12 20:24
Solved by https://github.com/specify/specify7/pull/3741

**Closed by grantfitzsimmons** 2023-07-12 20:24 UTC
Labels: 1 - Bug, 2 - Queries
