### ISSUE TITLE
Errors should not force users to lose all work on a form

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1727] opened 2022-06-03 18:01 UTC
Discovered during a duplicate key issue due to clone function.
Currently, if there is an error, such as a duplicate key error, users lose all of their data on the form.  There is no choice to go back to the form and fix the error even if the error told them what to fix.
This happens with small errors that would be easy to fix as well as larger issues

**Comment by maxxxxxdlp** [comment] 2022-06-04 02:47
Duplicate of #1699
The uniqueness error and other business rule errors would be handled properly in next release
Also, I would try to make specify 7 smarter about which errors can always be safely dismissable

**Closed by maxxxxxdlp** 2022-06-04 02:47 UTC
Labels: type:bug, pri:unknown
