### ISSUE TITLE
Refresh Query Title After Changing It

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3585] opened 2023-06-06 20:30 UTC
**Describe the bug**
If you change a query title while said query is open. The title will not change till you refresh the page. Would be great if it automatically did.

**To Reproduce**
1. Go to a saved query
2. Click on the pencil by the title
3. Change the title and save

**Screen Recording**

https://github.com/specify/specify7/assets/53784701/f4632fa4-a233-40b5-bb79-6d05114a95ff

**Desktop:**
 - OS: Mac OsX Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.11 and 7.8.12

**Comment by maxxxxxdlp** [comment] 2023-06-07 02:53
Will be fixed by migrating off backbone, so not sure if it's worth fixing it manually until then as that code would have to be thrown out anyway and this is not a big issue

**Comment by melton-jason** [comment] 2024-07-10 20:18
Duplicate of #2234

**Closed** 2024-07-10 20:19 UTC
Labels: 1 - Bug
