### ISSUE TITLE
[Sp7.7] Specify crashes when attempting to add child to synonymised name

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#2062] opened 2022-08-30 13:06 UTC
**Describe the bug**
See description.  
Ideally, adding children to synonymised names should be accepted.  - it is a valid operation - e.g. a syn. Genus may have Syn. Species under it.  - That's covered by separate GitHub's.  
However, if that can't in the short term be enabled, then specify should not crash when this is attempted.  
Instead, the system should detect the error, and explain the issue to the user.  
When creating the taxa through the Data Entry form, the fact that the parent is a syn. isn't visible in the form, so its basically impossible for the user to spot this / avoid / know why the system has crashed.  

**To Reproduce**
1. create a syn. taxa.  
2. attempt to add a child to it through data entry screens.  
3. see crash.  

**Expected behavior**
see above

**Database Name:** rbge_herb

**Comment by benritchie** [comment] 2022-09-27 11:25
Ben - is there any updates on plans for this issue?  
Thanks

**Comment by maxxxxxdlp** [comment] 2022-09-27 12:56
I belive this ticket is a duplicate of https://github.com/specify/specify7/issues/1735

7.7.0 added a remote pref that allows to disable this error.

Note, the "Add children" button in the taxon tree is still disabled (will be fixed in the future - https://github.com/specify/specify7/issues/1735#issuecomment-1256554584)

We are also in the process of improving the error message - https://github.com/specify/specify7/issues/108

**Closed by maxxxxxdlp** 2022-09-27 12:56 UTC
Labels: type:bug, pri:unknown, back-end
