### ISSUE TITLE
Open linkout fields in a separate browser window

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#726] opened 2020-08-27 17:23 UTC
From Andy:

`...can we get linkout fields to open in a separate browser window?  Currently if I click on a CT scan link or a Genbank sequence link it opens in the same browser window which causes Specify to “go away” and I have to use the back button to get back into the database.  For workflows that is not ideal.`

**Comment by maxxxxxdlp** [comment] 2021-07-15 14:52
Duplicate of #680

**Closed by maxxxxxdlp** 2021-07-15 14:52 UTC
Labels: type:enhance
