### ISSUE TITLE
Cannot add Collection Object record in new Collecting Event form

### ISSUE THREAD

**Issue by mc0822** [specify/specify7#2165] opened 2022-09-16 21:10 UTC
**Describe the bug**
In New Collecting Event form, you cannot add a Collection Object record.

**Expected behavior**
You should be able to add a Collection Object record.

**Screenshots**
https://anfc-v772.test.specifysystems.org/specify/view/collectingevent/new/

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7.7.2

**Database Name:** If applicable
Specimens

**Reported By**
Theresa at Specify

**Comment by maxxxxxdlp** [comment] 2022-09-16 21:30
Is this a duplicate of https://github.com/specify/specify7/issues/114?

**Comment by mc0822** [comment] 2022-09-16 21:38
It looks it may be a duplicate, but it's more similar to #97.  #114 is from 2015, so it'd be good to fix this.  Thanks!

**Closed** 2022-09-19 14:14 UTC
Labels: type:bug, pri:unknown
