### ISSUE TITLE
Add multiple determiners

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2112] opened 2022-09-08 17:17 UTC
Many institutions have requested the ability to add multiple determiners to a determination. This would be very helpful for recording the group of determiners that identified a specimen as a specific taxonomy.

**Requested By:** NMC Herbaria, West Virginia Herbarium

**Comment by maxxxxxdlp** [comment] 2022-10-21 15:00
Duplicate of https://github.com/specify/specify6/issues/1131

**Closed by maxxxxxdlp** 2022-10-21 15:00 UTC
Labels: type:enhance, pri:unknown, back-end
