### ISSUE TITLE
Pressing 'Enter' deletes search query in the app resource editor

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4238] opened 2023-11-29 19:34 UTC
This is the behavior in `v7.9.1`. Need to verify on `xml-editor`.

To recreate, search for a term (in this case, `label=`). Highlight, then click 'backspace' or 'delete' to remove some text. See that your search term has been removed as well, and you need to retype it.

https://github.com/specify/specify7/assets/37256050/157d62fe-2b22-45d3-b29a-ea2af576b337

**Comment by melton-jason** [comment] 2023-11-30 15:56
This behavior is present on `xml-editor`, `v7.9.0`, `v7.8.13` and `v7.8.9` (likely present on previous/other versions as well). 
And for more information, the search does not need to be executed for this bug to occur. Simply losing the focus (dismissing the search options) is enough to "reset" it and clear all information. 

> To recreate, search for a term (in this case, label=). Highlight, then click 'backspace' or 'delete' to remove some text. See that your search term has been removed as well, and you need to retype it.

So, another method of recreating this is simply enter a search term in the box and then make any edit to the App Resource. 
The search options disappear and all prior information is lost.

**Comment by maxxxxxdlp** [comment] 2023-12-01 04:59
Duplicate of https://github.com/specify/specify7/issues/2386

the problem with duplicate issues is that there was time spent researching the problem, but now because we have a duplicate issue, time was spent on it again (despite the fact that the original issue now has a solution proposed)

**Closed by maxxxxxdlp** 2023-12-01 04:59 UTC
Labels: 1 - Bug, 2 - App Resources
