### ISSUE TITLE
Saving a view definition should automatically clear the cache

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2085] opened 2022-09-02 14:46 UTC
When updating the schema configuration, it automatically clears your cache. 

The same behavior should happen when updating a views file! Bonus points if it can also preserve the current URL.

**Comment by grantfitzsimmons** [comment] 2022-09-15 14:40
Matthew Cruz at UMich also submitted a question about this today. Logging in and out to see your form changes is cumbersome.. especially when the [cache buster often breaks](https://github.com/specify/specify7/issues/2102) making logging in and out faster.

**Comment by maxxxxxdlp** [comment] 2022-09-15 15:38
Duplicate of https://github.com/specify/specify7/issues/1977

I will repost your comments there

**Closed by maxxxxxdlp** 2022-09-15 15:38 UTC
Labels: type:enhance, pri:unknown
