### ISSUE TITLE
Entire web link field missing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2416] opened 2022-11-06 19:17 UTC
<img width="2551" alt="image" src="https://user-images.githubusercontent.com/37256050/200190422-9049db67-f89c-4820-8302-e61e98ed58b9.png">

On Collection Object form-

`spadmin` is the user. JSTOR image link is the missing field.

https://purdueherbaria-testability.test.specifysystems.org/specify/view/collectionobject/1/?recordsetid=1130

Might be related to https://github.com/specify/specify7/issues/2413

**Comment by maxxxxxdlp** [comment] 2022-11-21 15:14
WebLink does not have a name:

```xml
<cell type="field" id="t14" name="description" uitype="plugin" initialize="name=WebLinkButton" />
```

And even if it had name, there is only one weblink defined:
![Screenshot 2022-11-21 at 09 13 19](https://user-images.githubusercontent.com/40512816/203090125-5c0f679c-8901-4eb0-aeba-bf6516ca105c.png)

Thus, this is a duplicate of #2404

**Comment by maxxxxxdlp** [comment] 2022-12-12 21:08
People have been saving values into weblink fields. Even though web links are misconfigured, the values in the field should still be editable

**Comment by chanulee1** [comment] 2022-12-12 22:39
Weblink field is rendered and editable. Appears to be fixed.

**Closed** 2022-12-12 23:18 UTC
Labels: type:bug, pri:unknown
