### ISSUE TITLE
Make notification relative date relative to the Specify system time and not user's time

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4050] opened 2023-09-29 14:33 UTC
<img width="802" alt="image" src="https://github.com/specify/specify7/assets/37256050/60a4a74e-7cff-4a5b-a73c-3c42ef81987e">

The timestamps shown (`now`, `last month`, `yesterday`, etc.) are relative to the current user's time, but these should be relative to the system time so that the dates are not in the future.

The database stores the timestamp for the system, not the user accessing Specify in the browser.

**Comment by maxxxxxdlp** [comment] 2023-09-30 01:58
Duplicate of #641

**Closed by maxxxxxdlp** 2023-09-30 01:58 UTC
Labels: 1 - Request, 2 - User Interface

**Comment by grantfitzsimmons** [comment] 2023-09-30 02:12
@maxxxxxdlp This duplicate is findable, so I'm glad I opened it :joy:

**Comment by maxxxxxdlp** [comment] 2023-09-30 03:15
renamed the title, and added "Bug" label. should be easier to find now. feel free to improve futher
