### ISSUE TITLE
Expand tables allowed to auto-generate subforms in Remote preferences

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4567] opened 2024-02-20 16:14 UTC
**Is your feature request related to a problem? Please describe.**

CSIRO is using the ConservDescription and ConservEvents tables as a visitor log for their institution. Because of the dependent relationship between these tables, they are wanting to configure their ConservDescription record to automatically generate a ConservEvent record like with COs and Preps, for example, but this is not applicable at this time.

**Describe the solution you'd like**

Allow to use other table IDs to configure automatically generated records during data entry in the Remote Preferences file. 

**Reported By**
CSIRO

**Additional Context**

[discourse on existing preference configuration](https://discourse.specifysoftware.org/t/automatically-create-a-new-preparation-determination-or-collection-object-attribute-upon-co-creation/1014)

**Comment by maxpatiiuk** [comment] 2024-02-21 01:53
Duplicate of #2056

**Closed by maxpatiiuk** 2024-02-21 01:53 UTC
Labels: 1 - Request, 2 - App Resources
