### ISSUE TITLE
[testability] Saving changes to Agent record with certain fields filled out results in error

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2518] opened 2022-11-30 23:44 UTC
Attempting to save changes to an agent record with agent type "Other" and an associated address record results in error. Error logs say address cannot be found, but a query showed that the address record was created.

https://user-images.githubusercontent.com/103299204/204930222-e9f8b782-4ab2-4e33-b572-d5d30a86125e.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/view/agent/4443/

[Specify 7 Crash Report - 2022-11-30T23_32_24.663Z.txt](https://github.com/specify/specify7/files/10128092/Specify.7.Crash.Report.-.2022-11-30T23_32_24.663Z.txt)

Console:
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/204930715-180da789-c733-4860-81a2-18b9e4e6fc01.png"/>

**Comment by realVinayak** [comment] 2022-12-01 14:13
I can replicate the error on my local instance. The problem seems to be the incorrect address id. It looks like making a request to `/api/specify/address/{id}/` is giving an error.  In my case, frontend is trying to access `addressid=776` in `address table`. However, when I check the address table using SQL, there is no `addressid 776`. That is, there is no address in the address table with id=776.

**Comment by melton-jason** [comment] 2022-12-01 16:26
Some additional context:
The error only occurs on PUT requests (i.e. updating an already existing Agent) and only for agent types `Other` and `Group`: seemingly behaves as intended otherwise.  

@realVinayak where are you seeing this request? On a local instance of Specify7 (and through the API for `kufishnotests`), I was able to find the PUT request, and the addressID in the request correctly corresponds to the address it _should_ be adding/updating (and yet, the error is still being thrown).

**Comment by maxxxxxdlp** [comment] 2022-12-01 18:26
Potentially related to https://github.com/specify/specify7/issues/1702 or https://github.com/specify/specify7/issues/929

@realVinayak @melton-jason this is a concerning issue.

Also, see how the error message in the video includes `[object Object]` - that's a separate bug - should be fixed to.

Let me know if you have questions, need help figuring this out

**Comment by grantfitzsimmons** [comment] 2022-12-06 15:00
https://herbrbge6802-testability.test.specifysystems.org/specify/query/new/agent/

I was able to recreate this on `testability`

```
Error: [object Object]
    at i (https://herbrbge6802-testability.test.specifysystems.org/static/js/main.89a990d7a6b36380deab.bundle.js:2:84452)
    at https://herbrbge6802-testability.test.specifysystems.org/static/js/7377.067cb8cd9ba92c043133.bundle.js:1:110834

```

In `edge` you just get page not found

![Uploading image.png…]()

**Comment by melton-jason** [comment] 2022-12-12 18:34
> It turns out there is a business rule that agents with type other and group cannot have address. The backend exception weren't properly setup so the exception didn't raise on frontend.
@realVinayak  

The way the backend currently addresses this businessrule is that it deletes all addresses from the agent. I find this problematic, as it is possible an already existing address can be assigned to an agent: creating a swarm of potential issues (including this one).

There are two easy solutions: 
(1) Remove the Business Rule
(2) Raise the BusinessRuleException 

Regarding (1), this rule _does_ exist already in Specify 6; an address can not be added to an Agent of type Other or Group. A conversation with @tlammer revealed no specific reason as to why this business rule exists, and I can not think of any potential conflicts Specify6 would have if an Other or Group Agent has an address. But this rule was intentionally added, and there may be unforeseen issues with this approach. Testing (in both Specify 6 and 7) would be required. 

Regarding (2): Preferably, the exception would be raised _without_ deleting addresses. When this is the case, I believe the intended behavior remains: the exception is raised and the user is directed away from the form and back to the home page, without saving any changes they made. 
If we move forward, the most user-friendly implementation of this would be to use save blockers so the user is not directed away from the form.

**Comment by melton-jason** [comment] 2023-01-12 22:19
> Here is the decision we have reached regarding the problematic Business Rule Exception which disallows Addresses being added to Agents of type Other and Group ([#2518 (comment)](https://github.com/specify/specify7/issues/2518#issuecomment-1347039470))
> 
> The Business Rule will be removed in Specify 7. Before the Specify 6 release ([specify/specify6#1189](https://github.com/specify/specify6/pull/1189)), I will remove it there as well (if the removal does not cause major problems). The BusinessRule will be removed from Specify 7 even if we can not safely/easily remove it in Specify 6

In https://github.com/specify/specify7/pull/2702#issuecomment-1381057692

**Closed by melton-jason** 2023-01-12 22:19 UTC
Labels: type:bug, pri:unknown
