### ISSUE TITLE
Simple Search Needs A Select All Button 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3634] opened 2023-06-16 19:59 UTC
The[ Discourse Documentation ](https://discourse.specifysoftware.org/t/simple-search/185)states that simple search has a Select All/Deselect All Button. However, we only have a deselect button and the only way to select multiple items is manually.
<img width="783" alt="Screenshot 2023-06-16 at 2 56 39 PM" src="https://github.com/specify/specify7/assets/53784701/06a26f49-5d6c-4e60-bc2e-3b04325dafe2">

It would be nice to have a Select All Button in addition to the Deselect All Button
<img width="1625" alt="Screenshot 2023-06-16 at 2 58 34 PM" src="https://github.com/specify/specify7/assets/53784701/ed9c453b-4081-4835-a4b4-bb432178c72e">
<img width="1626" alt="Screenshot 2023-06-16 at 2 58 22 PM" src="https://github.com/specify/specify7/assets/53784701/b7bd6da5-b020-4d99-8fdb-343e67908328">

**Comment by maxxxxxdlp** [comment] 2023-06-17 04:12
Since express search reuses query builder UI for this, this issue is a duplicate of https://github.com/specify/specify7/issues/2049

**Closed by maxxxxxdlp** 2023-06-17 04:12 UTC
Labels: type:enhance, pri:unknown
