### ISSUE TITLE
Python3: Duplicated forms in the Data Entry menu

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#694] opened 2020-06-26 12:41 UTC
Most of the forms in this menu are duplicated

<img width="544" alt="Screen Shot 2020-06-26 at 3 40 20 PM" src="https://user-images.githubusercontent.com/40512816/85857900-4fc18180-b780-11ea-8394-62bb461217ce.png">

**Comment by benanhalt** [comment] 2020-06-26 17:01
Duplicate of #636

**Closed by benanhalt** 2020-06-26 17:01 UTC
Labels: type:bug
