### ISSUE TITLE
404 If you open agent mergeing notifications after deleting it

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3896] opened 2023-08-03 15:05 UTC
**Describe the bug**
Uploaded some agents via Work Bench. There were some duplicates in this spread sheet. Merged them. Then rolled back. Now I get a 404 throughout Specify if I open notifications.

**Beautiful Screen Recording**
### This starts from rolling back the agents

https://github.com/specify/specify7/assets/53784701/8949ae5b-e698-4081-8b91-9c48876b8259

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by CarolineDenis** [comment] 2023-08-03 15:18
@carlosmbe @bronwyncombs duplicate of: https://github.com/specify/specify7/issues/3887 ?

**Closed** 2023-08-03 15:19 UTC
Labels: 1 - Bug, 2 - Merging
