### ISSUE TITLE
Allow uploading/validating more than one data set at a time

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2273] opened 2022-10-03 18:21 UTC
Don't know if anyone asked for this, but we talked about this during the Workbench redesign.

Currently, the worker process can only work on one data set at a time. Thus, if there is validation in progress, no one else can do validation/upload.

**Comment by grantfitzsimmons** [comment] 2023-08-08 21:04
Duplicate of https://github.com/specify/specify7/issues/854

**Closed by grantfitzsimmons** 2023-08-08 21:04 UTC
Labels: 1 - Request, 2 - WorkBench
