### ISSUE TITLE
Attempting to open views definition results in error message

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2337] opened 2022-10-18 22:21 UTC
**Describe the bug**
When try to open the "Common" view definition (global resource) in the `herb_rbge` database, error message appears.

Link: https://herbrbge-testability.test.specifysystems.org/specify/resources/view-set/3/

**To Reproduce**
1. Go to app resources
2. Click on "Common" view definition
3. See error: 
[Specify 7 Crash Report - 2022-10-18T22_10_59.550Z (1).txt](https://github.com/specify/specify7/files/9815427/Specify.7.Crash.Report.-.2022-10-18T22_10_59.550Z.1.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/103299204/196555563-7ff8e517-2860-4400-a043-f5625830be05.png)

<a href="https://user-images.githubusercontent.com/103299204/196555623-e42a65d1-dce0-47a8-8594-d555cfd84e8e.png">Console</a>

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: `testability`, `7.7.5`

**Database Name:** `herb_rbge`
user: `david`

**Comment by maxxxxxdlp** [comment] 2022-10-18 22:29
Not sure what causes this, but this is a duplicate of #1202

**Closed by maxxxxxdlp** 2022-10-18 22:29 UTC
Labels: type:bug, pri:unknown
