### ISSUE TITLE
Support count attribute in aggregators

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2161] opened 2022-09-16 18:23 UTC
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/37256050/190705864-c56a802b-9d7d-46c0-8c88-73b3a3eb6622.png">

Specify 7 currently ignores the count="" attribute for aggregators in the DataObjFormatters document.

This prevents the ability to specify a count of 1 in situations like Determinations for instance. In Specify 6, you can show only the current determination where in 7 you see all determinations.

**Comment by maxxxxxdlp** [comment] 2022-09-19 14:32
https://github.com/specify/specify7/issues/1144#issuecomment-1015887568

**Comment by maxxxxxdlp** [comment] 2023-03-18 02:19
Closing this as a duplicate of #1144

**Closed by maxxxxxdlp** 2023-03-18 02:19 UTC
Labels: type:bug, pri:unknown
