### ISSUE TITLE
Leaflet error polygons use wrong field

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1907] opened 2022-07-27 03:33 UTC
When leaflets plots a locality, it retrives the error radius from the `Locality.latLongAccuracy` field.

`Locality.geoCoordDetails.maxUncertaintyEst` should be used instead, as that's the field that is used by GeoLocale.

**Comment by cdamyx** [comment] 2023-03-07 20:51
I'm trying to display the actual leaflet map on the front-end to test my fix. Am I in the correct location in the screenshot below? I can't view the "Geolocate" and "Geomap" buttons, unless I edit the DOM to display them. Thanks in advance!
![image](https://user-images.githubusercontent.com/40224280/223549170-bb0e023a-30f6-4136-b200-155157f89868.png)

**Comment by maxxxxxdlp** [comment] 2023-03-07 21:10
You need to add `longitude1` field to your data set mapping for that button to become available.
We have a feature request about making that more clear: https://github.com/specify/specify7/issues/2624

**Comment by cdamyx** [comment] 2023-03-08 05:51
Ah, that make sense, thanks!

It looks like circles are what's using errorRadius in ../components/leaflet/index.ts  - is that where the changes are needed from latlongaccuracy, or am I still missing something?

**Comment by maxxxxxdlp** [comment] 2023-03-08 15:00
That's a correct place. But there appears to be quite a lot of places that would need to be changed.
The way to go is probably to search for all occurrences of `latlongaccuracy` in the code, and evaluate weather they should be replaced by `geocoorddetails.maxuncertaintyest`

**Comment by emenslin** [comment] 2024-08-06 14:41
Duplicate of #3957

**Closed by emenslin** 2024-08-06 14:41 UTC
Labels: 1 - Bug, good first issue
