### ISSUE TITLE
Getting uniqueness constraint error when merging several records together

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3840] opened 2023-07-26 01:05 UTC
https://herbrbge71423-issue-3822.test.specifysystems.org/specify/overlay/merge/Agent/?records=12571%2C12297%2C11701%2C11432%2C10217%2C9993

`issue-3822` (based on `v7.9-dev`), macOS, Firefox

<img width="2557" alt="image" src="https://github.com/specify/specify7/assets/37256050/9473f528-2a68-402c-ae1b-4ba86a14d5c0">

Response Headers:
```
Allow | E,  r, r, o, r, !,  , M, u, l, t, i, p, l, e,  , r, e, c, o, r, d, s,  , v,  i, o, l, a, t, i, n, g,  , u, n, i, q, u, e, n, e, s, s,  , c, o, n, s,  t, r, a, i, n, t, s,  , i, n,  , C, o, l, l, e, c, t, o, r
```

405 as fetch:
```
await fetch("https://herbrbge71423-issue-3822.test.specifysystems.org/api/specify/agent/replace/12297/", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0",
        "Accept": "text/plain",
        "Accept-Language": "en-US,en;q=0.5",
        "Content-Type": "application/json",
        "X-CSRFToken": "jlu1featQkNVX5yo3q8AkJ3LuRnrwoOgdgfhQ8a4sGcgfcaN0V9Z5i0CugdRkDzg",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "referrer": "https://herbrbge71423-issue-3822.test.specifysystems.org/specify/overlay/merge/Agent/?records=12571%2C12297%2C11701%2C11432%2C10217%2C9993",
    "body": "{\"old_record_ids\":[12571,11432,11701,10217,9993],\"new_record_data\":{\"abbreviation\":\"CGN\",\"agenttype\":1,\"date1\":\"1994-07-01\",\"date1precision\":3,\"date2\":\"1996-07-01\",\"date2precision\":3,\"dateofbirth\":\"1964-07-01\",\"dateofbirthprecision\":3,\"dateofdeath\":null,\"dateofdeathprecision\":null,\"datetype\":null,\"email\":null,\"firstname\":\"J.\",\"guid\":\"1C4622AD-BE43-4539-93B0-D8FE1987BC22\",\"initials\":null,\"integer1\":null,\"integer2\":null,\"interests\":null,\"jobtitle\":null,\"lastname\":\"Zhang\",\"middleinitial\":\"W.\",\"remarks\":\"Keywords: Asia\",\"suffix\":null,\"text1\":null,\"text2\":null,\"text3\":null,\"text4\":null,\"text5\":null,\"timestampcreated\":\"2022-02-25T00:00:00\",\"timestampmodified\":\"2022-02-25T00:00:00\",\"title\":\"Ms.\",\"url\":null,\"verbatimdate1\":null,\"verbatimdate2\":null,\"version\":1,\"collcontentcontact\":null,\"colltechcontact\":null,\"createdbyagent\":\"/api/specify/agent/2/\",\"division\":\"/api/specify/division/2/\",\"instcontentcontact\":null,\"insttechcontact\":null,\"modifiedbyagent\":\"/api/specify/agent/2/\",\"organization\":null,\"specifyuser\":null,\"orgmembers\":\"/api/specify/agent/?organization=10217\",\"collectors\":\"/api/specify/collector/?agent=10217\",\"members\":\"/api/specify/groupperson/?member=10217\",\"catalogerof\":\"/api/specify/CollectionObject?cataloger=10217\",\"addresses\":[],\"agentattachments\":[],\"agentgeographies\":[],\"identifiers\":[],\"agentspecialties\":[],\"variants\":[{\"country\":null,\"language\":null,\"name\":\"Zhang, C.Q.\",\"vartype\":5,\"variant\":null,\"agent\":\"/api/specify/agent/12297/\",\"createdbyagent\":null,\"modifiedbyagent\":null,\"timestampcreated\":\"2023-07-25\",\"timestampmodified\":null,\"version\":1,\"_tableName\":\"AgentVariant\"},{\"country\":null,\"language\":null,\"name\":\"Zhang, C.Q.\",\"vartype\":6,\"variant\":null,\"agent\":\"/api/specify/agent/12297/\",\"createdbyagent\":null,\"modifiedbyagent\":null,\"timestampcreated\":\"2023-07-25\",\"timestampmodified\":null,\"version\":1,\"_tableName\":\"AgentVariant\"},{\"country\":null,\"language\":null,\"name\":\"Zhang, C.Q.\",\"vartype\":7,\"variant\":null,\"agent\":\"/api/specify/agent/12297/\",\"createdbyagent\":null,\"modifiedbyagent\":null,\"timestampcreated\":\"2023-07-25\",\"timestampmodified\":null,\"version\":1,\"_tableName\":\"AgentVariant\"},{\"country\":null,\"language\":null,\"name\":\"Zhang, Chang-qin\",\"vartype\":8,\"variant\":null,\"agent\":\"/api/specify/agent/12297/\",\"createdbyagent\":null,\"modifiedbyagent\":null,\"timestampcreated\":\"2023-07-25\",\"timestampmodified\":null,\"version\":1,\"_tableName\":\"AgentVariant\"}],\"groups\":[],\"_tableName\":\"Agent\"}}",
    "method": "POST",
    "mode": "cors"
});
```

**Comment by melton-jason** [comment] 2023-07-26 02:00
Duplicate of #3801

**Closed** 2023-07-26 02:00 UTC
Labels: 1 - Bug

**Comment by realVinayak** [comment] 2023-07-26 06:49
I've also added a unit test for this in my changes. Should be resolved now.
