### ISSUE TITLE
Visual Editor UI Not Refreshing After Reseting Preferences 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3419] opened 2023-04-26 21:55 UTC
**Describe the bug**
Possibly related to #3411. @realVinayak would know.

After setting preferences  using Customization -> Preferences 
Reseting those same user preferences from **App Resources** works globally but the option fields in the UI do not refresh in the visual editor.

**To Reproduce**
1. Go to Customization -> Preferences and make save some changes
2. Reset to see expected UI behaviour
3. Go to Resources -> `{Current User In Current Collection}`-> UserPreferences
4. Reset and See error

**Expected behavior**

https://user-images.githubusercontent.com/53784701/234711140-93061a93-46d3-44f6-be8c-6b7b73cf1a1a.mov

**Error**
It is still saying Light Mode despite the preferences being reset. Same happens with other values.

https://user-images.githubusercontent.com/53784701/234711642-28cdc4a3-bdcc-4081-984e-81d7c57ef35e.mov

**Desktop:**
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

**Database Name:** gothenberg

**Reported By**
@carlosmbe

**Comment by realVinayak** [comment] 2023-04-26 21:59
This is because there is a bug in app resources preferences which causes it to rese the current user's preferences instead of the target one. Here is the line that causes it: https://github.com/specify/specify7/blob/e96288c5e8cd530b31ceb841fbc6326731418822/specifyweb/frontend/js_src/lib/components/Preferences/index.tsx#L181. It should instead take it from the PrefererencesContext.

**Comment by maxxxxxdlp** [comment] 2023-04-27 17:37
@realVinayak good catch. See how this hook knows where to store preferences and do something similar based on that in here:
https://github.com/specify/specify7/blob/bb0db83b23cd406c260ae647e79fd7cdfea6d0ed/specifyweb/frontend/js_src/lib/components/Preferences/BasePreferences.tsx#L373

<details>
  <summary>Solution</summary>
  Instead of `userPreferneces` use `currentPreferences`, where `currentPreferences` is defined like this:
  ```
  const currentPreferences = React.useContext(userPreferences.Context)
  ```
</details>

Of course, you would have to replace `userPreferences` with `collectionPreferences` (make this component receive that as a prop) in the future

**Comment by melton-jason** [comment] 2023-06-13 02:22
@realVinayak 
Please feel free to close this as a duplicate of #3411 if they have the same underlying issue (I think they do)

**Comment by grantfitzsimmons** [comment] 2023-08-08 02:33
Duplicate of https://github.com/specify/specify7/issues/3411

**Closed by grantfitzsimmons** 2023-08-08 02:33 UTC
Labels: 1 - Bug
