### ISSUE TITLE
[a11y] Creating a new user gives a 500 error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1614] opened 2022-05-17 14:53 UTC
![image](https://user-images.githubusercontent.com/37256050/168841315-c025835c-2ac5-4f2f-9f9d-4b1e7141f25a.png)

Jim and I have tried to create a new user with a password and we both received the 500 error code.

browser: Firefox
db: `kufish`

**Comment by maxxxxxdlp** [comment] 2022-05-18 17:47
Duplicate of #1646

**Closed by maxxxxxdlp** 2022-05-18 17:47 UTC
Labels: type:bug, pri:unknown
