### ISSUE TITLE
Query builder from QCB doesn't disable Browse in Forms when 0 results returned 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3796] opened 2023-07-17 17:01 UTC
**Describe the bug**
The query builder dialog that's accessed from a query combo box allows to select `Browse in Forms` even when 0 results are returned. Upon click an infinite loading dialog begins. 

**To Reproduce**
1. Go to record with query combo box
2. Click on magnifying glass icon to the right
3. Click on `Query Builder`
4. Run a query that returns no results
5. Select `Browse in Forms`
6. See error

**Screenshots**

https://github.com/specify/specify7/assets/135047322/331885a0-cdec-4c0b-9c28-60419bdd99c8

https://github.com/specify/specify7/assets/135047322/1287d789-8f2d-448a-b778-81ce042f8980

**Desktop:**
 - macOS, Chrome, `v7.9-dev`
 
**Database Name:** sdnhmpaleo

**Comment by bronwyncombs** [comment] 2023-07-17 17:01
Can't recreate in `v7.8.13`

**Comment by CarolineDenis** [comment] 2023-07-18 15:16
@bronwyncombs I cannot reproduce

**Comment by bronwyncombs** [comment] 2023-07-18 16:07
I'm on `herb_rbge` and getting this dialog now instead of the loading screen. Still only through the query combo box to query builder path. Also, only with certain fields (first name, not email)?

https://github.com/specify/specify7/assets/135047322/ee413d86-6c54-458a-a939-a2564f98f6ab


From a UX perspective, I don't see a problem with this "No Data." dialog view. It's probably not necessary to disable `Browse in Forms` under the conditions it does appear since this is now the case

**Comment by CarolineDenis** [comment] 2023-07-18 17:29
@bronwyncombs, I can reproduce but only if the name entered is 'hi' :sweat_smile:
See bellow

![Screenshot 2023-07-18 at 10 28 52 AM](https://github.com/specify/specify7/assets/108160931/74e4f0fd-3602-424d-ac65-2be6da907009)
![Screenshot 2023-07-18 at 10 28 39 AM](https://github.com/specify/specify7/assets/108160931/ac279977-f02e-4da2-88e4-37f3db4cc5d4)
![Screenshot 2023-07-18 at 10 28 29 AM](https://github.com/specify/specify7/assets/108160931/f3208715-a6f1-45ee-b39a-d4eb48626a78)

**Comment by CarolineDenis** [comment] 2023-07-18 18:43
@grantfitzsimmons, I can add a condition if totalcount is = 0 or we can accept the dialog with no data?

**Comment by maxxxxxdlp** [comment] 2023-07-19 02:45
> Super inconsistent. Running this same query over and over yielded different results.

that button only appears once total count is fetched.

fetching results and fetching total count are separate results - they can be resolved in any order - that is why you see the inconsistency

**Comment by CarolineDenis** [comment] 2023-07-19 13:27
@maxxxxxdlp would this be a valid solution? https://github.com/specify/specify7/commit/d185519157c0843753390c14a22430c7c6b1e430

**Comment by grantfitzsimmons** [comment] 2023-07-19 21:09
@maxxxxxdlp

That's Interesting, but I can wait forever and it does not appear if it loads and does not show the browse in forms. 
It's not that I am impatient (though I am).  You are likely correct, but I don't understand why it "gives up" loading the total count in those cases

**Closed** 2023-07-21 13:33 UTC
Labels: 1 - Bug, 2 - Queries
