### ISSUE TITLE
Error message when moving taxa

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1643] opened 2022-05-17 22:01 UTC
I moved a genus to a new family in the colorado_paleo database and got the attached error message
[message.docx](https://github.com/specify/specify7/files/8711805/message.docx)

**Comment by maxxxxxdlp** [comment] 2022-05-17 22:12
The error says "bad tree structure"
It is database specific. Not sure why tree structure is broken in this database though.

**Comment by maxxxxxdlp** [comment] 2023-03-14 00:22
@melton-jason take a look if there is anything to learn from this broken tree structure (i.e, cause, whether the cause is already fixed, etc). If not close this issue

**Comment by melton-jason** [comment] 2023-03-14 04:48
This was the same issue that caused #2707 and #2753. 

There was a tree node whose rank id was the same or less than its parent. There are two cases which are important: whether the affected node was synonymized or not.

In the case the node is synonymized, we have disabled that tree check as tree structure is not that important for synonymized nodes.
In the case the node not is not synonymized, then that _is_ an indication of bad tree structure, and the error response has been improved enough to identify the affected node(s).

**Closed by melton-jason** 2023-03-14 04:48 UTC
Labels: type:bug, pri:unknown
