### ISSUE TITLE
[testability] Loan Preparations are not being created

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2281] opened 2022-10-04 00:44 UTC
https://user-images.githubusercontent.com/37256050/193710366-dd0ae5ac-678a-4711-becf-c88f88417ab7.mov

<img width="2372" alt="image" src="https://user-images.githubusercontent.com/37256050/193710529-22c711fb-0102-4cb7-b6aa-039836aa8e1c.png">

<img width="2509" alt="image" src="https://user-images.githubusercontent.com/37256050/193710507-b99c680e-28a7-42c0-8ba2-7b794f908692.png">

**To Reproduce:**
1. Create a loan based on catalog number `00000005` in `herb_rbge`
2. Select the 1 preparation associated with `Reseda lutea`
3. See that the Loan Preparations are not filled in on `testability`

DB: `herb_rbge`
User: `britchie`

Left: `testability` - [Link](https://herbrbge-testability.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178)
Right: `v773` - [Link](https://herbrbge-v773.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178)

**Comment by grantfitzsimmons** [comment] 2022-10-04 01:20
<img width="2558" alt="image" src="https://user-images.githubusercontent.com/37256050/193714130-e606d072-7e0b-4f1d-8c4e-4b9c739af8b4.png">

https://herbrbge-v773.test.specifysystems.org/specify/view/loanpreparation/1/
https://herbrbge-testability.test.specifysystems.org/specify/view/loanpreparation/1/

This was an existing record

**Comment by maxxxxxdlp** [comment] 2022-10-18 18:06
Duplicate of #2277

**Closed by maxxxxxdlp** 2022-10-18 18:06 UTC
Labels: type:bug, pri:unknown
