### ISSUE TITLE
BusinessRuleException When Creating Duplicate Collection Object

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3595] opened 2023-06-08 16:15 UTC
**Describe the bug**
If you create a new collection object with a catalog number that's already being used. Specify throws an errors.

**To Reproduce**
1. Go to Data Entry
2. Click on `Catalog Number` and add a used catalog number
3. Save

**Expected behavior**
A prompt saying the number is already in use or something else that is not an error like highlighting the `Catalog Number` field red. It can be a pain to fill out the entire form and then have a crash and have to start again.

**Screen Recording and Crash Reports**
Note that Catalog Number 1 is in use.
[Specify 7 Crash Report - 2023-06-08T16_14_52.613Z (1).txt](https://github.com/specify/specify7/files/11690857/Specify.7.Crash.Report.-.2023-06-08T16_14_52.613Z.1.txt)
[Specify 7 Crash Report - 2023-06-08T16_14_52.613Z.txt](https://github.com/specify/specify7/files/11690858/Specify.7.Crash.Report.-.2023-06-08T16_14_52.613Z.txt)

https://github.com/specify/specify7/assets/53784701/065028f9-1875-46d0-a03d-153223a19aa5

**Desktop:**
 - OS: Mac OSx Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.12

**Comment by melton-jason** [comment] 2023-06-08 17:19
This is a known issue. 
This is related to #3579, and very likely has the same cause. 
The problem stems from the fact that Specify is checking uniqueness using the CatalogNumber _before_ it was formatted (in this case `1`). Because no other Collection Objects have a catalog number of `1` in the collection, the frontend does not think there is a problem. 
If you make an edit to the CatalogNumber field _after_ it has been formatted, then you will get the expected results. 

This is likely something that can be addressed on the `xml-editor` branch, where business rules, save-blockers, and parsing have all seen some changes.

**Comment by melton-jason** [comment] 2023-08-11 16:10
Closing as a duplicate of #2859

**Closed by melton-jason** 2023-08-11 16:10 UTC
Labels: 1 - Bug
