### ISSUE TITLE
`AttributeError` when adding a cataloger

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3326] opened 2023-04-11 13:02 UTC
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/37256050/231170334-c260e7e2-6e5c-44cb-8843-45b66b79de31.png">

https://coldfish-issue-3314.test.specifysystems.org/specify/view/collectionobject/new/

`abentley`, KU Fish Voucher Collection

Create a determination record, try to add a cataloger by typing "A" in the QCBX for determiner

[Specify 7 Crash Report - 2023-04-11T13_01_14.239Z.txt](https://github.com/specify/specify7/files/11200647/Specify.7.Crash.Report.-.2023-04-11T13_01_14.239Z.txt)

**Comment by realVinayak** [comment] 2023-04-11 17:35
I can't reproduce this on demo instance. The issue might be a side-effect of xml testing. I've had queries fail on `coldFish` on test panel because of invalid formatters (which were caused by xml testing)

**Comment by CarolineDenis** [comment] 2023-06-21 20:26
@melton-jason let us know if we can close this

**Comment by melton-jason** [comment] 2023-06-21 20:34
Yes, I will close this!

**Comment by realVinayak** [comment] 2023-06-21 20:38
I wouldn't close this for now. 

Probably caused by xml-editor. But, at least we should now why this gets raised. I think it runs a ephemeral query for that, so my changes should handle it. Not sure if it does this now.

**Comment by carlosmbe** [comment] 2023-11-13 20:57
I got a Recursion Error on 7.9.1 and xml editor on Cold Fish. Went to a determiner and changed Taxon to "a". Might or might not be related. On XML editor the Taxon is a number on 7.9.1. It's just blank.

Similar behaviour with cataloger. Recursion error instead of Attribute Error.  

However both versions start with the cataloguer being "Agent # NUM"

 
<img width="1792" alt="Screenshot 2023-11-13 at 2 56 11 PM" src="https://github.com/specify/specify7/assets/53784701/c61999a7-dfee-4652-8cb1-c69ef4b3ef0b">


# 7.9.1
<img width="1792" alt="Screenshot 2023-11-13 at 2 51 52 PM" src="https://github.com/specify/specify7/assets/53784701/d9008051-5efa-4907-b8ca-f99a5b186512">

<img width="1792" alt="Screenshot 2023-11-13 at 2 39 48 PM" src="https://github.com/specify/specify7/assets/53784701/00adf093-589d-4769-a8cc-95ef675c9990">

[Specify 7 Crash Report - 2023-11-13T20_39_49.366Z.txt](https://github.com/specify/specify7/files/13341113/Specify.7.Crash.Report.-.2023-11-13T20_39_49.366Z.txt)


# xml - editor

<img width="1792" alt="Screenshot 2023-11-13 at 2 49 12 PM" src="https://github.com/specify/specify7/assets/53784701/14921b67-c149-44ee-a61a-652e8d0b69d5">


<img width="1787" alt="Screenshot 2023-11-13 at 2 49 33 PM" src="https://github.com/specify/specify7/assets/53784701/cd2b27f9-d495-4ee1-84a0-2a07d293281d">


[Specify 7 Crash Report - 2023-11-13T20_49_43.775Z.txt](https://github.com/specify/specify7/files/13341230/Specify.7.Crash.Report.-.2023-11-13T20_49_43.775Z.txt)

**Comment by realVinayak** [comment] 2023-11-13 21:37
@carlosmbe can you try it on `xml-editor-backend-fixes` branch?

**Comment by carlosmbe** [comment] 2023-11-13 21:42
Recursion and Attribute error of Agents were due to misconfiguration of DataObjFormatter. @grantfitzsimmons  did a killer job in helping figure that out.

However, the taxon issue has evolved into a Index Error after fixing the XML file

**Comment by realVinayak** [comment] 2023-11-13 21:43
The Recursion error has been handled on that branch, specifically for this!

**Comment by carlosmbe** [comment] 2023-11-13 21:44
@realVinayak Should all todo verifies that involve XML editor be tested on that branch?

**Comment by realVinayak** [comment] 2023-11-13 21:45
Hmm not all of them. If an issue is related to data object formatters, then yeah.

**Comment by carlosmbe** [comment] 2023-11-13 21:57
@realVinayak `xml-editor-backend-fixes ` did not fix the issue. The Index Error was indeed the result of a messed up DataObjFormatter file.

**Closed** 2023-12-27 05:03 UTC
Labels: 1 - Bug
