### ISSUE TITLE
[testability] Logging out and back in throws an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2372] opened 2022-10-31 01:34 UTC
https://user-images.githubusercontent.com/37256050/198913815-36b54442-084d-4c49-ac31-13b18c710f07.mov

Here is the URL with the error:
`https://kufishnotests-testability.test.specifysystems.org/accounts/choose_collection/?next=`

Going back and choosing the collection again works fine!

https://kufishnotests-testability.test.specifysystems.org/specify/

user: `abentley`
system: macOS, Chrome

**Comment by grantfitzsimmons** [comment] 2022-10-31 01:34
I was able to recreate this 3 times, but let me know if you are having trouble getting this to occur.

**Comment by grantfitzsimmons** [comment] 2022-10-31 01:35
Same happened when I tried to change the password:
![Uploading image.png…]()

**Comment by maxxxxxdlp** [comment] 2022-10-31 18:42
I had this happen several times on this particular deployment. Haven't seen it for others.
I has no connection to the routing system.
Could be caused by the fact that schema version and database version don't match (it might cause back-end errors)
Or, most likely, the server was just reloading.

I will close this for now, but if it happens again, reopen it as a high priority

**Comment by grantfitzsimmons** [comment] 2022-10-31 18:43
For the record, this happened before the schema version was changed

**Closed by maxxxxxdlp** 2022-10-31 18:42 UTC
Labels: type:bug, pri:unknown
