### ISSUE TITLE
Attachment count by table should be scoped to current collection

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3284] opened 2023-04-03 14:27 UTC
![image](https://user-images.githubusercontent.com/37256050/229539615-ae66f5a9-7d11-49c9-8ad3-623fafc142da.png)

For instance, it shows that 7,135 collection objects have attachments.

When logged into a collection without CO attachments, you can see the count is 7,135 but none are returned.

![image](https://user-images.githubusercontent.com/37256050/229539715-5e6b5f99-0380-4925-b3c0-1a755bd901a4.png)

**Comment by maxxxxxdlp** [comment] 2023-04-05 14:53
Duplicate of #2762
Duplicate of #2292
Why do duplicate issues get open so often?

**Closed by maxxxxxdlp** 2023-04-05 14:53 UTC
Labels: type:bug, pri:unknown
