### ISSUE TITLE
DataObjFormatter for ReferenceWork field not listened to 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4064] opened 2023-10-04 16:19 UTC
**Describe the bug**
The desired format of the ReferenceWork field is not respected after the record is added to the citation form. The format displays correctly when searching and in query results, but the field reverts to the default display order after being added to the form. The table formats are set in schema config for CO citation, Taxon citation, and the Reference Works table.  

**To Reproduce**
Test Panel Database: `mcnb_7_31_23`
1. Open a new Collection Object or Taxon record
2. Open the Citation subview (icon on CO and subform on Taxon)
4. Search in the referencework field (Cita bibliofràfica) and add a citation
5. Save form
6. See error in changed formatting of field

**Expected behavior**
referencework field should display according to the defined format on the forms. 

**Screenshots**

**format is correct in queries on the Reference Work table:**
![Screenshot 2023-10-04 at 10 18 12 AM](https://github.com/specify/specify7/assets/135047322/2ffaba16-cc12-44a8-9c29-95edb2a764d9)

**format is correct in queries on the CO table ONLY when (formatted) for CO is mapped to the query as well:**

https://github.com/specify/specify7/assets/135047322/5afb3e01-8bcd-4ffd-9b00-421227cd911f

**adding a citation to the form:**

https://github.com/specify/specify7/assets/135047322/b96ea559-9206-435d-bfc9-2be3ea50b730

**Comment by realVinayak** [comment] 2023-10-04 17:46
Can you check this on 7.8.13 as well?

**Comment by emenslin** [comment] 2024-05-29 17:26
Duplicate of #3868

**Closed by emenslin** 2024-05-29 17:26 UTC
Labels: 1 - Bug, 2 - Schema Config, 2 - App Resources
