### ISSUE TITLE
Change synonymize text

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1734] opened 2022-06-06 18:40 UTC
Enhancement requested by edinburgh
When you select a species, and click synonymise, it says:

![unnamed](https://user-images.githubusercontent.com/12532430/172225367-72f6ec03-9075-4bcc-a49c-86820cd5f95e.png)

That made me think it was going to try to synonymise it with itself! – I now see I’m meant to click again on target.  However, would be really useful if we could change the initial text to an instruction – e.g. “click on accepted name in tree” – so people know what to do.

**Comment by maxxxxxdlp** [comment] 2022-06-07 02:24
Duplicate of https://github.com/specify/specify7/issues/1654
Would be fixed in next release

**Closed by maxxxxxdlp** 2022-06-07 02:24 UTC
Labels: type:enhance, res:duplicate, pri:unknown
