### ISSUE TITLE
Unload Protect triggered browsing in locality record sets 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4554] opened 2024-02-16 19:09 UTC
**Describe the bug**

the 8th record in this record set specifically triggers unload protect: 
[demofish record set ](https://sp7demofish2924-v79.test.specifysystems.org/specify/view/locality/6/?recordsetid=41)

Happens on this record set in `fwri` when you skip to the last record and go backward: 
[fwri record set](https://fwri1924-edge.test.specifysystems.org/specify/view/locality/41941/?recordsetid=1907)

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `v7.9`
- Database Name: `fwri_1_9_24` and `sp7demofish_2_9_24`

**Additional context**

related issue: 
https://github.com/specify/specify7/issues/3259

**Comment by emenslin** [comment] 2024-07-15 19:48
Duplicate of #3259

**Closed by emenslin** 2024-07-15 19:48 UTC
Labels: 1 - Bug, 2 - Record Sets
