### ISSUE TITLE
Query Builder - Tree Table to Anything Else OperationalError

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#4231] opened 2023-11-24 22:11 UTC
**Describe the bug**
If you create a query based on any of the Trees:

1. Taxon
2. Storage
3. Geography
4. Lithostrat
5. Chronostrat

Then go and create another new query with any other table as a base. It's going to through an OperationalError

**Expected behavior**
No error
[Specify 7 Crash Report - 2023-11-24T22_08_09.151Z.txt](https://github.com/specify/specify7/files/13462329/Specify.7.Crash.Report.-.2023-11-24T22_08_09.151Z.txt)

**Beautiful Screen Recording**

https://github.com/specify/specify7/assets/53784701/86e67a69-b87d-4fed-95a5-4c6f8a37acf3

**Desktop:**
 - OS: Mac OsX
 - Browser: Chrome
 - Specify 7 Version: Any

**Comment by melton-jason** [comment] 2023-12-18 15:55
Closing this as a duplicate of #4294 as that issue is more more general and covers all tables, not just tree tables

**Closed by melton-jason** 2023-12-18 15:55 UTC
Labels: 1 - Bug
