### ISSUE TITLE
Taxon import via Workbench fails randomly 

### ISSUE THREAD

**Issue by vivekpulukuri** [specify/specify7#1143] opened 2022-01-17 03:02 UTC
Trying to import taxon tree through the workbench, Validate or Upload actions throw unfriendly json errors message on the screen 

Log from  celery process
```
[2022-01-11 17:21:56,793: INFO/MainProcess] mingle: all alone
[2022-01-11 17:21:56,801: INFO/MainProcess] celery@specify-dev ready.
[2022-01-11 17:22:11,234: INFO/MainProcess] Received task: specifyweb.workbench.                                                                                                                                   tasks.upload[2cd2e8d7-4397-4d56-a138-0d5f1984b1dd]
[11/Jan/2022 17:22:11] [ERROR] [specifyweb.celery:30] Celery task failure!!!1
Traceback (most recent call last):
  File "/srv/apps/anfc/specify7/ve/lib/python3.6/site-packages/celery/app/trace.                                                                                                                                   py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/apps/anfc/specify7/ve/lib/python3.6/site-packages/celery/app/trace.                                                                                                                                   py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/apps/anfc/specify7/specifyweb/workbench/tasks.py", line 41, in uplo                                                                                                                                   ad
    do_upload_dataset(collection, uploading_agent_id, ds, no_commit, allow_parti                                                                                                                                   al, progress)
  File "/srv/apps/anfc/specify7/specifyweb/workbench/upload/upload.py", line 114                                                                                                                                   , in do_upload_dataset
    results = do_upload(collection, rows, upload_plan, uploading_agent_id, disam                                                                                                                                   biguation, no_commit, allow_partial, progress)
  File "/srv/apps/anfc/specify7/specifyweb/workbench/upload/upload.py", line 185                                                                                                                                   , in do_upload
    bind_result = upload_plan.disambiguate(da).bind(collection, row, uploading_a                                                                                                                                   gent_id, _auditlog, cache)
  File "/srv/apps/anfc/specify7/specifyweb/workbench/upload/treerecord.py", line                                                                                                                                    71, in bind
    if filters['name'] is None:
KeyError: 'name'
[2022-01-11 17:22:11,417: ERROR/ForkPoolWorker-1] Task specifyweb.workbench.task                                                                                                                                   s.upload[2cd2e8d7-4397-4d56-a138-0d5f1984b1dd] raised unexpected: KeyError('name                                                                                                                                   ',)
Traceback (most recent call last):
  File "/srv/apps/anfc/specify7/ve/lib/python3.6/site-packages/celery/app/trace.                                                                                                                                   py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/apps/anfc/specify7/ve/lib/python3.6/site-packages/celery/app/trace.                                                                                                                                   py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/apps/anfc/specify7/specifyweb/workbench/tasks.py", line 41, in uplo                                                                                                                                   ad
    do_upload_dataset(collection, uploading_agent_id, ds, no_commit, allow_parti                                                                                                                                   al, progress)
  File "/srv/apps/anfc/specify7/specifyweb/workbench/upload/upload.py", line 114                                                                                                                                   , in do_upload_dataset
    results = do_upload(collection, rows, upload_plan, uploading_agent_id, disam                                                                                                                                   biguation, no_commit, allow_partial, progress)
  File "/srv/apps/anfc/specify7/specifyweb/workbench/upload/upload.py", line 185                                                                                                                                   , in do_upload
    bind_result = upload_plan.disambiguate(da).bind(collection, row, uploading_a                                                                                                                                   gent_id, _auditlog, cache)
  File "/srv/apps/anfc/specify7/specifyweb/workbench/upload/treerecord.py", line                                                                                                                                    71, in bind
    if filters['name'] is None:
KeyError: 'name'
```
**To Reproduce**
try to import a flattened taxon tree through the WB.
validate works showing highlighing error cells but fails randomly with 
![image](https://user-images.githubusercontent.com/2975626/149037959-feecece8-319e-4d84-803e-d542134c4479.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:. Windows 10
 - Browser :Chrome,
 - Specify 7 Version  7.6.1

**Reported By**
Vivek Pulukuri ( CSIRO )

**Comment by maxxxxxdlp** [comment] 2022-01-18 17:37
Replicated the issue when "Match Behaviour" is set to "Ignore When Blank" or "Always Ignore".
@benanhalt please look into this

**Comment by vivekpulukuri** [comment] 2022-02-28 06:14
@maxxxxxdlp @benanhalt  it seems like this worked in the previous version where missing/empty nodes are allowed in  taxon tree. Now there is no way for us to import taxa with missing/empty values in some ranks.  Any ideas when this can be fixed? or any workarounds.

**Comment by maxxxxxdlp** [comment] 2022-02-28 14:41
I believe you can change the tree definition in Specify 6 to not enforce certain ranks
Another solution would be to provide a default value for missing ranks using the "gear" button at the end of the mapping line. E.g "(no Class)" in the Class column

**Comment by benanhalt** [comment] 2022-07-27 16:42
I will try to fix the proximate issue that is causing the exception and the we can proceed from there.

**Comment by benanhalt** [comment] 2022-07-28 18:21
This is a duplicate of #1375 and has been fixed.

**Closed by benanhalt** 2022-07-28 18:21 UTC
Labels: type:bug, pri:unknown, back-end
