### ISSUE TITLE
Determiners not available in the WorkBench mapper

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2850] opened 2023-01-19 17:13 UTC
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/37256050/213513545-996b82e8-9eb7-45fe-8922-55700fb75ccc.png">

This is _pretty_ urgent as I need to upload several determiners for each determination & this should be already supported.

**Comment by maxxxxxdlp** [comment] 2023-01-19 17:32
Duplicate of #2331

Agree, this needs to be fixed. But there were some challenges with it which is why it wasn't in the first release of the work bench. Talk to Jason/Alec about what difficulties there are

**Closed by maxxxxxdlp** 2023-01-19 17:32 UTC
Labels: type:bug, pri:unknown

**Comment by grantfitzsimmons** [comment] 2023-01-19 17:34
I opened the duplicate for a reason– we do better about tackling recent problems...

**Comment by maxxxxxdlp** [comment] 2023-01-19 18:28
That is valid! If you want to do the same in the future, then close the older issue first and move relevant comments from it into the new issue.

But really, you should just mention to back-end programmers how much of a priority this is in comparison to other things (they don't deal with conversions as much so it's harder to estimate priorities)
