### ISSUE TITLE
False "No Agent matches the given query" response for agent merging

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3892] opened 2023-08-02 20:21 UTC
I am repeatedly getting this response when merging, but the agents _do_ exist! 

![Screenshot 2023-08-02 at 3 15 37 PM](https://github.com/specify/specify7/assets/135047322/cb9aca3b-878a-4d56-8ba2-97606ab0ef49)

- macOS, chrome, v7.9-dev
- `herb_rbge_3_31_23`

**Comment by grantfitzsimmons** [comment] 2023-08-04 16:14
@melton-jason has no clue what causes this

**Comment by CarolineDenis** [comment] 2023-08-04 20:47
I think it was caused by the same problem than in https://github.com/specify/specify7/issues/3887
Might be fixed with https://github.com/specify/specify7/pull/3906
To test

**Comment by CarolineDenis** [comment] 2023-08-16 14:48
@bronwyncombs, can you still reproduce this?

**Comment by grantfitzsimmons** [comment] 2023-08-18 21:03
@bronwyncombs did you try to reproduce this for @CarolineDenis ?

**Comment by bronwyncombs** [comment] 2023-08-21 16:55
@CarolineDenis yes I can reproduce using the same DB & agents. Haven't run into this specific issue anywhere else.

Here's the whole message w/ traceback:

```javascript
 "message_id": 361,
        "read": false,
        "timestamp": "2023-08-21T16:48:00.341819",
        "type": "record-merge-failed",
        "response": "Traceback (most recent call last):\n  File \"/opt/specify7/ve/lib/python3.8/site-packages/django/shortcuts.py\", line 76, in get_object_or_404\n    return queryset.get(*args, **kwargs)\n  File \"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py\", line 435, in get\n    raise self.model.DoesNotExist(\nspecifyweb.specify.models.Agent.DoesNotExist: Agent matching query does not exist.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/specify7/specifyweb/specify/views.py\", line 438, in resolve_record_merge_response\n    response = start_function()\n  File \"/opt/specify7/specifyweb/specify/views.py\", line 672, in <lambda>\n    response = resolve_record_merge_response(lambda: record_merge_fx(model_name, old_model_ids, int(new_model_id), progress, new_record_info))\n  File \"/usr/lib/python3.8/contextlib.py\", line 75, in inner\n    return func(*args, **kwds)\n  File \"/opt/specify7/specifyweb/specify/views.py\", line 628, in record_merge_fx\n    obj = api.put_resource(new_record_info['collection'],\n  File \"/usr/lib/python3.8/contextlib.py\", line 75, in inner\n    return func(*args, **kwds)\n  File \"/opt/specify7/specifyweb/specify/api.py\", line 612, in put_resource\n    return update_obj(collection, agent, name, id, version, data)\n  File \"/opt/specify7/specifyweb/specify/api.py\", line 622, in update_obj\n    dependents_to_delete, fk_dirty = handle_fk_fields(collection, agent, obj, data)\n  File \"/opt/specify7/specifyweb/specify/api.py\", line 503, in handle_fk_fields\n    setattr(obj, field_name, get_object_or_404(fk_model, id=fk_id))\n  File \"/opt/specify7/specifyweb/specify/api.py\", line 232, in get_object_or_404\n    return get_object(model, *args, **kwargs)\n  File \"/opt/specify7/ve/lib/python3.8/site-packages/django/shortcuts.py\", line 78, in get_object_or_404\n    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)\ndjango.http.response.Http404: No Agent matches the given query.\n",
        "task_id": "53d8352f-0d7b-4970-b6eb-20ebd99d2bc2",
        "table": "Agent",
        "new_record_id": 13377,
        "old_record_ids": "[126]"
```

**Comment by grantfitzsimmons** [comment] 2023-08-22 17:25
It looks like #3906 did not resolve this issue.

**Comment by CarolineDenis** [comment] 2023-08-22 17:28
No but after running the most recent migrations on the DB the issue was fixed. Need @bronwyncombs to confirm this.

**Comment by grantfitzsimmons** [comment] 2023-08-23 18:37
[Merging 80d29ff5-5339-4b13-b3b2-fb35db44108b Crash Report - 2023-08-23T18 36 49.413Z.txt](https://github.com/specify/specify7/files/12422293/Merging.80d29ff5-5339-4b13-b3b2-fb35db44108b.Crash.Report.-.2023-08-23T18.36.49.413Z.txt)

https://herbrbge31323-fix-recursive-progress.test.specifysystems.org/specify/overlay/merge/Agent/?records=126%2C13377

<img width="1310" alt="image" src="https://github.com/specify/specify7/assets/37256050/45fcaf96-f72c-4704-b283-27ef3330a5f5">

**Comment by grantfitzsimmons** [comment] 2023-08-23 18:45
|id|name|taskid|mergingstatus|response|table|newrecordid|newrecordata|oldrecordids|collection_id|specifyuser_id|timestampcreated|timestampmodified|createdbyagent_id|modifiedbyagent_id|
|--|----|------|-------------|--------|-----|-----------|------------|------------|-------------|--------------|----------------|-----------------|-----------------|------------------|
|1|Merge_agent_13377|80d29ff5-5339-4b13-b3b2-fb35db44108b|FAILED|Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
specifyweb.specify.models.Agent.DoesNotExist: Agent matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/specify7/specifyweb/specify/views.py", line 439, in resolve_record_merge_response
    response = start_function()
  File "/opt/specify7/specifyweb/specify/views.py", line 688, in <lambda>
    lambda: record_merge_fx(model_name, old_model_ids, int(new_model_id), progress, new_record_info))
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/specify7/specifyweb/specify/views.py", line 637, in record_merge_fx
    obj = api.put_resource(new_record_info['collection'],
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/specify7/specifyweb/specify/api.py", line 612, in put_resource
    return update_obj(collection, agent, name, id, version, data)
  File "/opt/specify7/specifyweb/specify/api.py", line 622, in update_obj
    dependents_to_delete, fk_dirty = handle_fk_fields(collection, agent, obj, data)
  File "/opt/specify7/specifyweb/specify/api.py", line 503, in handle_fk_fields
    setattr(obj, field_name, get_object_or_404(fk_model, id=fk_id))
  File "/opt/specify7/specifyweb/specify/api.py", line 232, in get_object_or_404
    return get_object(model, *args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/shortcuts.py", line 78, in get_object_or_404
    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)
django.http.response.Http404: No Agent matches the given query.
|Agent|13377|"{\"abbreviation\": \"RAKER\", \"agenttype\": 1, \"date1\": null, \"date1precision\": null, \"date2\": null, \"date2precision\": null, \"dateofbirth\": \"1983-01-08\", \"dateofbirthprecision\": 1, \"dateofdeath\": null, \"dateofdeathprecision\": null, \"datetype\": null, \"email\": null, \"firstname\": \"Ruth\", \"guid\": \"CE9FD87B-4C46-4763-BDE9-335506D92A7A\", \"initials\": null, \"integer1\": null, \"integer2\": null, \"interests\": null, \"jobtitle\": null, \"lastname\": \"Akers\", \"middleinitial\": \"Margaret\", \"remarks\": \"Keywords: msc 2007,RBGE,Misc: RBGE MSc student 2006-2007\", \"suffix\": null, \"text1\": null, \"text2\": null, \"text3\": null, \"text4\": null, \"text5\": null, \"timestampcreated\": \"2007-02-14T00:00:00\", \"timestampmodified\": \"2022-12-05T13:27:48\", \"title\": \"Miss\", \"url\": null, \"verbatimdate1\": null, \"verbatimdate2\": null, \"version\": 1, \"collcontentcontact\": null, \"colltechcontact\": null, \"createdbyagent\": \"/api/specify/agent/126/\", \"division\": \"/api/specify/division/2/\", \"instcontentcontact\": null, \"insttechcontact\": null, \"modifiedbyagent\": \"/api/specify/agent/8567/\", \"organization\": null, \"specifyuser\": null, \"orgmembers\": \"/api/specify/agent/?organization=13377\", \"collectors\": \"/api/specify/collector/?agent=13377\", \"members\": \"/api/specify/groupperson/?member=13377\", \"catalogerof\": \"/api/specify/CollectionObject?cataloger=13377\", \"addresses\": [], \"agentattachments\": [], \"agentgeographies\": [], \"identifiers\": [], \"agentspecialties\": [], \"variants\": [{\"country\": null, \"language\": null, \"name\": \"Akers\", \"vartype\": 5, \"variant\": null, \"agent\": \"/api/specify/agent/13377/\", \"createdbyagent\": null, \"modifiedbyagent\": null, \"timestampcreated\": \"2023-08-23\", \"timestampmodified\": null, \"version\": 1, \"_tableName\": \"AgentVariant\"}, {\"country\": null, \"language\": null, \"name\": \"Akers, R\", \"vartype\": 6, \"variant\": null, \"agent\": \"/api/specify/agent/13377/\", \"createdbyagent\": null, \"modifiedbyagent\": null, \"timestampcreated\": \"2023-08-23\", \"timestampmodified\": null, \"version\": 1, \"_tableName\": \"AgentVariant\"}, {\"country\": null, \"language\": null, \"name\": \"Akers, Ruth M\", \"vartype\": 8, \"variant\": null, \"agent\": \"/api/specify/agent/13377/\", \"createdbyagent\": null, \"modifiedbyagent\": null, \"timestampcreated\": \"2023-08-23\", \"timestampmodified\": null, \"version\": 1, \"_tableName\": \"AgentVariant\"}], \"groups\": [], \"_tableName\": \"Agent\"}"|"[126]"|4|16|2023-08-23 18:36:14.524|2023-08-23 18:36:19.578|26142|26142|
|2|Merge_agent_44994|b10f32bd-bc9a-4418-8637-09d24f2d9c14|SUCCEEDED||Agent|44994|"{\"abbreviation\": \"RAKER\", \"agenttype\": 1, \"date1\": null, \"date1precision\": null, \"date2\": null, \"date2precision\": null, \"dateofbirth\": \"1983-01-08\", \"dateofbirthprecision\": 1, \"dateofdeath\": null, \"dateofdeathprecision\": null, \"datetype\": null, \"email\": null, \"firstname\": \"Ruth\", \"guid\": \"a5453e4c-3e02-41bf-a3a9-40a5f6f1026a\", \"initials\": null, \"integer1\": null, \"integer2\": null, \"interests\": null, \"jobtitle\": null, \"lastname\": \"Akers\", \"middleinitial\": \"Margaret\", \"remarks\": \"Keywords: msc 2007,RBGE,Misc: RBGE MSc student 2006-2007\", \"suffix\": \"k\", \"text1\": null, \"text2\": null, \"text3\": null, \"text4\": null, \"text5\": null, \"timestampcreated\": \"2023-08-23T18:43:27.495038\", \"timestampmodified\": \"2023-08-23T18:43:27.495061\", \"title\": \"Miss\", \"url\": null, \"verbatimdate1\": null, \"verbatimdate2\": null, \"version\": 1, \"collcontentcontact\": null, \"colltechcontact\": null, \"createdbyagent\": \"/api/specify/agent/26142/\", \"division\": \"/api/specify/division/2/\", \"instcontentcontact\": null, \"insttechcontact\": null, \"modifiedbyagent\": \"/api/specify/agent/8567/\", \"organization\": null, \"specifyuser\": null, \"orgmembers\": \"/api/specify/agent/?organization=44994\", \"collectors\": \"/api/specify/collector/?agent=44994\", \"members\": \"/api/specify/groupperson/?member=44994\", \"catalogerof\": \"/api/specify/CollectionObject?cataloger=13377\", \"id\": 44994, \"resource_uri\": \"/api/specify/agent/44994/\", \"addresses\": [], \"agentattachments\": [], \"agentgeographies\": [], \"identifiers\": [], \"agentspecialties\": [], \"variants\": [{\"id\": 31376, \"country\": null, \"language\": null, \"name\": \"Akers\", \"timestampcreated\": \"2023-08-23T18:43:27\", \"timestampmodified\": \"2023-08-23T18:43:27\", \"vartype\": 5, \"variant\": null, \"version\": 1, \"agent\": \"/api/specify/agent/44994/\", \"createdbyagent\": \"/api/specify/agent/26142/\", \"modifiedbyagent\": null, \"resource_uri\": \"/api/specify/agentvariant/31376/\"}, {\"id\": 31377, \"country\": null, \"language\": null, \"name\": \"Akers, R\", \"timestampcreated\": \"2023-08-23T18:43:27\", \"timestampmodified\": \"2023-08-23T18:43:27\", \"vartype\": 6, \"variant\": null, \"version\": 1, \"agent\": \"/api/specify/agent/44994/\", \"createdbyagent\": \"/api/specify/agent/26142/\", \"modifiedbyagent\": null, \"resource_uri\": \"/api/specify/agentvariant/31377/\"}, {\"id\": 31378, \"country\": null, \"language\": null, \"name\": \"Akers, Ruth M\", \"timestampcreated\": \"2023-08-23T18:43:27\", \"timestampmodified\": \"2023-08-23T18:43:27\", \"vartype\": 8, \"variant\": null, \"version\": 1, \"agent\": \"/api/specify/agent/44994/\", \"createdbyagent\": \"/api/specify/agent/26142/\", \"modifiedbyagent\": null, \"resource_uri\": \"/api/specify/agentvariant/31378/\"}], \"groups\": []}"|"[126]"|4|16|2023-08-23 18:43:30.211|2023-08-23 18:43:34.642|26142|26142|

**Comment by carlosmbe** [comment] 2023-08-24 20:18
Can this be closed @bronwyncombs / @CarolineDenis ?

**Comment by CarolineDenis** [comment] 2023-08-24 20:28
I follow with the same question to @melton-jason & @grantfitzsimmons :)

**Comment by grantfitzsimmons** [comment] 2023-08-25 00:30
I think we can close this since it seems to be an anomaly, but I do feel we may run into this issue again in the future. I hope we don't need to revisit this 😄

**Closed by grantfitzsimmons** 2023-08-25 00:30 UTC
Labels: 1 - Bug, 2 - Merging
