### ISSUE TITLE
Ability to search fields in the QB

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2274] opened 2022-10-03 18:27 UTC
It would be nice to have a search function in the Query Builder to search the labels for all fields that are visible (and hidden if the show hidden items option is selected). This would speed up query building for users unfamiliar with the relational database components of Specify and want to find specific information.

**Requested By:** New Mexico Herbarium

**Comment by grantfitzsimmons** [comment] 2023-08-08 14:20
This is so smart

**Comment by maxxxxxdlp** [comment] 2023-08-09 00:40
Closing as duplicate of #3611

**Closed by maxxxxxdlp** 2023-08-09 00:40 UTC
Labels: 1 - Request, 2 - Queries
