### ISSUE TITLE
[a11y] Navigating a record set causes button placement to move

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1519] opened 2022-05-11 13:45 UTC
![msedge_yX5kmFKcW2](https://user-images.githubusercontent.com/37256050/167864417-9a9676d3-6d05-4b03-bef3-753d1162a047.gif)

When navigating through items in a record set, the page refreshes, moving the buttons and could potentially cause the user to jump to the first or last entry. I know that I have.

These buttons should be fixed in place to prevent this issue from happening!

**Comment by maxxxxxdlp** [comment] 2022-05-20 02:13
Duplicate of #1592

**Closed by maxxxxxdlp** 2022-05-20 02:13 UTC
Labels: type:bug, pri:unknown
