### ISSUE TITLE
AutoMapper behavior varies between 7.7 and 7.8

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2408] opened 2022-11-04 18:34 UTC
When mapping the following workbench plan to CO:
https://willemcatno-testability.test.specifysystems.org/specify/workbench/plan/129/

Is this change intentional? It does not seem to have much logic to its decision making. 

<img width="2559" alt="image" src="https://user-images.githubusercontent.com/37256050/200050006-7e377fcc-6aa8-4299-a049-8c7e9d28e0a4.png">

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/200050038-1af8971e-5920-4439-81aa-4efbfd8d51fa.png">

<img width="2548" alt="image" src="https://user-images.githubusercontent.com/37256050/200050071-f203d541-913d-406f-8652-9d8ca3f55c51.png">

<img width="2558" alt="image" src="https://user-images.githubusercontent.com/37256050/200049963-e773c192-81ee-4fca-9094-9f43afda0725.png">

**Comment by grantfitzsimmons** [comment] 2022-11-04 18:36
<img width="2532" alt="image" src="https://user-images.githubusercontent.com/37256050/200050234-a44d8853-88c5-473e-850a-2c14a70857b3.png">

Interesting behavioral difference

**Comment by maxxxxxdlp** [comment] 2022-11-18 20:36
Caused by https://github.com/specify/specify7/commit/2f70e6662c1d03be08ceb4c9193cad23226ce1b6

When I made that change, I didn't think about its effect on the auto mapper or the validation system - will fix.

**Comment by maxxxxxdlp** [comment] 2022-11-30 03:37
To test:
Do both on `edge` and `testability` for this data set - https://willemcatno-testability.test.specifysystems.org/specify/workbench/plan/129/
Run automapper
Make sure automapper results match between the versions.
Press on "Validate" to validate mappings. Make sure results between the versions match.

**Comment by chanulee1** [comment] 2022-11-30 22:33
There seems to be some discrepancies.

left: `testability`, right: `edge`

![image](https://user-images.githubusercontent.com/103299204/204922370-f0b9c3fb-3856-4ddb-8648-f4db3f1e7919.png)

![image](https://user-images.githubusercontent.com/103299204/204922514-b7a145e1-849e-4bc1-b9da-c4a242ab2008.png)

![image](https://user-images.githubusercontent.com/103299204/204922597-7364e285-db90-49c0-a810-192197b7b13f.png)

**Comment by maxxxxxdlp** [comment] 2022-12-01 18:17
Looks like there were two issues here.
One is a bug that was introduced on testability and already fixed - https://github.com/specify/specify7/issues/2408#issuecomment-1331603480
The mapping results are different because of a bug on `edge`. If you mark a table as hidden in the schema config, `edge` did not mark the table as hidden. That is fixed on `testability`, and thus relationships to the hidden tables are hidden in return (`PaleoContext` is a hidden table in this database, so `testability` wasn't using it for mapping)

**Closed** 2022-12-01 18:17 UTC
Labels: type:bug, pri:unknown
