### ISSUE TITLE
Add support for explicitly choosing a formatter in Query Builder

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1959] opened 2022-08-15 17:00 UTC
Query Builder currently uses the default formatter.

If we were to add an ability to explicitly select a formatter, users would be able to create a formatter than includes all the fields they need, with a separator they need. Then, that formatter could be used in reports/labels.

This will essentially add a way to concatenate fields in the Query Builder, which has been requested by many (including CSIRO)

**Comment by benanhalt** [comment] 2022-08-15 17:12
Pretty sure the backend already supports including a format name for a query field. The name would identify one of the formatters/aggregators defined in dataobjformatters.xml. 

For use in labels, it would be preferable to extend the formatter/aggregator syntax to generate JSON structures that could then be destructured using a scriptlet. Ideally it would support some kind of JSON path syntax.

https://stackoverflow.com/questions/41405510/json-query-and-json-path

**Comment by maxxxxxdlp** [comment] 2022-09-13 21:25
What is the syntax for specifying Formatter/Aggregator?

The following `SpQueryField` does not work:

```
{
      "tablelist": "1,10,2",
      "stringid": "1,10,2.locality.locality.FormatterName",
      "fieldname": "locality",
      "isrelfld": true,
      "sorttype": 0,
      "position": 0,
      "isdisplay": true,
      "operstart": 8,
      "startvalue": "",
      "isnot": false
    }
```

**Comment by grantfitzsimmons** [comment] 2022-09-13 21:31
Andy is interested in having his catalogNumber added to the base URL (“https://freshfish-testability.test.specifysystems.org/specify/bycatalog/KUI/” + “catalogNumber”) in the query output for each item.

This could be accomplished using a custom table format, but then it would apply everywhere. Solving this could allow him to specify a specific format for queries/forms and a specific format for exporting data.

**Comment by benanhalt** [comment] 2022-09-13 21:33
@maxxxxxdlp try something like:
```
 {
      "tablelist": "1,10,2",
      "stringid": "1,10,2.locality.locality",
      "fieldname": "locality",
      "isrelfld": true,
      "sorttype": 0,
      "position": 0,
      "isdisplay": true,
      "operstart": 8,
      "startvalue": "",
      "isnot": false,
      "formatname": "name of the formatter defined in dataobjformatters.xml"
    }
```

**Comment by maxxxxxdlp** [comment] 2022-09-13 21:43
That works! Awesome. I will add a UI for it

**Comment by benanhalt** [comment] 2022-09-13 21:51
I think it is even possible to format the base table that way using a stringid of just "1.collectionobject" or something like that. I think I added it for the querycbx or express search or something. But such queries won't work if they are saved and run from Sp6

**Comment by grantfitzsimmons** [comment] 2022-09-13 22:00
The primary purpose of this feature is for export definitions, right?

**Comment by maxxxxxdlp** [comment] 2022-09-13 22:04
The query builder UI in 7.7.0 already allows running a formatter on the base table. This was not possible in 7.6.1

**Comment by grantfitzsimmons** [comment] 2022-11-02 21:31
> Is there a way that I can specify a different formatter for a date field for exporting through DwC?  The standard is YYYY/MM/DD while my database uses mm/DD/YYYY.  Also, when exporting through the IPT Tim included information in the SQL query that rounded lat's and long's to 5 decimals and corrected for partial dates so that 1's were not entered for missing day and month.  Any way of doing that?

Andy is looking to choose a per-field formatter in the query builder for export purposes as well

**Comment by grantfitzsimmons** [comment] 2023-01-27 17:13
This came up again for MOR Paleo, it would be great to be able to truncate latitudes and longitudes when sharing data

**Comment by maxxxxxdlp** [comment] 2023-03-08 03:38
After this is fixed, need to also fix #1959

**Comment by grantfitzsimmons** [comment] 2023-06-06 15:27
CSIRO has requested again

**Comment by maxxxxxdlp** [comment] 2023-06-07 02:24
This is fixed on the xml-editor branch and just needs testing

**Comment by maxxxxxdlp** [comment] 2023-06-07 02:24
Fixed both for formatters and aggregators
The way it's implemented might even be compatible with sp6 (but needs testing)

**Comment by grantfitzsimmons** [comment] 2023-07-06 23:26
Mentioned as a potential solution for some of the pain caused by not having the ability to include multiple items for one-to-many relationships

**Closed** 2024-03-13 14:00 UTC
Labels: 1 - Request, 2 - Queries
