### ISSUE TITLE
Nucleotide sequence fields not calculating numbers of each base type

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1718] opened 2022-06-02 22:36 UTC
In Specify 6, the user can paste or type a genomic sequence into the gene sequence field and the Total Residues, Comp A, Comp C, Comp G, Comp T, and Ambiguous fields all auto calculate how many of each are in the gene sequence.
7 doesn't calculate or let the user type in the field (which it shouldn't).

**Comment by maxxxxxdlp** [comment] 2022-06-03 02:44
Duplicate of #676

**Closed** 2022-06-11 19:58 UTC
Labels: type:bug, res:duplicate, pri:unknown
