### ISSUE TITLE
Cloning Preferences results in a 404 error

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4683] opened 2024-03-25 17:01 UTC
**Describe the bug**
Cloning any Preference (Global/Remote) in Global Resources causes a 404 error displayed to the user.

**To Reproduce**
1. Go to App Resources -> Global Resources -> Any Preference (e.g. Global Preferences; https://fwri1924-edge.test.specifysystems.org/specify/resources/app-resource/1/)
2. Click on Clone
4. See 404 error

Note: found bug while testing #4531

**Expected behavior**
Page should display the selected Resource cloned with a unique name.
Behavior in `v7.9`:

https://github.com/specify/specify7/assets/118556884/997ae1f0-c9ab-4c83-9287-7aaf8d7659fe

**Evidence**

https://github.com/specify/specify7/assets/118556884/eb136268-585e-4a2f-b2fb-1851cb4fd51b

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `fwri_1_9_24`

**Comment by CarolineDenis** [comment] 2024-03-25 17:57
NOTES: 
location.search in useSerachParameter() is missing GlobalPreferences

**Comment by CarolineDenis** [comment] 2024-03-25 21:07
@maxpatiiuk, 
any hints on where to look for this? Didn't find the start of the problem yet... 
From what I understand 
the rawDirectoryKey in AppResources useProps() should be globalResources but is undefined

**Comment by maxpatiiuk** [comment] 2024-03-26 03:57
you are on a correct path.
there should be a directoryKey in the URL, but there isn't
see where it's supposed to be set:
https://github.com/specify/specify7/blob/075104652b2204e273501289a7090e79b3998007/specifyweb/frontend/js_src/lib/components/AppResources/EditorWrapper.tsx#L101-L104

**Comment by CarolineDenis** [comment] 2024-03-26 15:35
NOTES: 
- directory id for global pref is 1 and for prefs is 3
- getGlobalAllResources only returns the common directory with the id 10
- results: the directory id for our preferences cannot be find. 

getGlobalAllResources return only one mainDirectory but should now returns 3 (common - prefs - global prefs) the issue is that this is used in a lot of places in the code 

https://github.com/specify/specify7/blob/075104652b2204e273501289a7090e79b3998007/specifyweb/frontend/js_src/lib/components/AppResources/tree.ts#L81

```ts
/**
   * Even though there are several global directories, for consistency, all
   * global resources are added to the one that has userType==='Common'
   */
  const mainDirectory =
    globalDirectories.find(({ userType }) => userType === 'Common') ??
    globalDirectories[0];
  /**
   * Resources from all global directories are visually merged into a single
   * one. This is because there is currently no use case for separate
   * global resource dirs, while having them separated in the UI would
   * suggest the opposite.
   */

**Closed** 2024-03-28 15:22 UTC
Labels: 1 - Bug, 2 - App Resources
