### ISSUE TITLE
Multiple Downloads Can Crash Chrome

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3671] opened 2023-06-23 18:39 UTC
**Describe the bug**
Downloading a TSV after refreshing Stats Page and interacting with the Chrome Download Permissions thing will cause a crash.
Same can happen with Downloading entire Query CSVs

**To Reproduce**
1. Go to Stats Page
2. Click on Download CSV
3. Click on refresh
4. Click on Download Permission on top
5. Repeat until crash

**Expected behavior**
No crash

**Screenshots**

https://github.com/specify/specify7/assets/53784701/1de1b8fc-81bc-49a7-9b9d-41c438ee210b

<img width="1792" alt="Screenshot 2023-06-23 at 1 41 51 PM" src="https://github.com/specify/specify7/assets/53784701/be797eb0-f47b-4abe-a0fb-a7631cf2e4bb">

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by carlosmbe** [comment] 2023-06-23 18:48
Possibly related to https://github.com/specify/specify7/issues/2638

**Comment by grantfitzsimmons** [comment] 2023-06-23 19:00
I believe this is a Chrome bug.

I think it has to do with downloading duplicate files over and over, breaking the browser's dialog asking the user if this is OK after viewing it first.

**Comment by maxxxxxdlp** [comment] 2023-06-24 23:50
I would like to shine some light on this comment of mine:

https://github.com/specify/specify7/blob/041259050c024debfa26bef7a0a68df01330dd6d/specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx#L125-L136

I glued together two hacks to make file downloading work, without involvement of back-end and to allow us to use arbitrary file name and extension - at the time I wrote this, I don't think a better solution of this relatively small size and complexity existed (outside of large libraries specialized for this, which we might require to use if the problem gets too complicated)

**Comment by grantfitzsimmons** [comment] 2023-07-05 15:26
Not `v7.9-dev` specific, can be done on `v7.8.13`.

**Comment by grantfitzsimmons** [comment] 2023-07-06 15:34
Looks like only one file is being downloaded on `v7.9`. Feel free to confirm @carlosmbe , but this might be fixed.

**Comment by grantfitzsimmons** [comment] 2023-07-11 02:02
This is a exceedingly rare Chrome-specific issue, so I will close this in favor of reporting it to Google instead.

https://support.google.com/chrome/answer/95315?hl=en&co=GENIE.Platform%3DDesktop
If you are interested in making a report

**Closed** 2023-07-11 02:03 UTC
Labels: 1 - Bug

**Comment by maxxxxxdlp** [comment] 2023-07-13 01:22
Nice, I didn't know you can report bugs that way.

Web developers usually report Chrome bugs in a different place - https://bugs.chromium.org/p/chromium/issues/list

Plus, there you can get a faster response - though you need to provide more details and reproduction cases
