### ISSUE TITLE
Cannot associate loan preparations with existing loan

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2915] opened 2023-01-30 19:19 UTC
Can add loan preparations to an existing loan but going to preparations show that they are not loaned. Happens when adding with both catalog numbers and records sets. Also, adding preparations does not trigger the save button. (Edit: Appears to be duplicate of #2565)

https://user-images.githubusercontent.com/103299204/215572840-c43d6698-77dd-4fd8-ab3f-70e3afe23459.mp4

https://coldfish-edge.test.specifysystems.org/specify/view/loan/325/

**Comment by maxxxxxdlp** [comment] 2023-02-22 02:30
I believe Specify 7 just does not integrate with the `Is On Loan` checkbox

**Comment by grantfitzsimmons** [comment] 2023-08-07 02:22
Duplicate of https://github.com/specify/specify7/issues/2565)

**Closed by grantfitzsimmons** 2023-08-07 02:22 UTC
Labels: 1 - Bug, 2 - Interactions
