### ISSUE TITLE
Improve GeoMap so that it stops grouping fields by name and instead by object

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4253] opened 2023-12-04 17:54 UTC
<img width="669" alt="image" src="https://github.com/specify/specify7/assets/37256050/29bcc29b-ac6d-40fd-af30-e9f9344f3349">

For instance, all of these objects were collected at the same point. 
Instead of showing the catalog number, collectors, and start date grouped by collection object, Specify groups these fields by field name, so it's unclear how they are related. It's confusing, especially in other instances where the collectors and start dates are different.

**Reported By:** Barcelona and others

**Comment by maxpatiiuk** [comment] 2023-12-06 04:41
Duplicate of https://github.com/specify/specify7/issues/2463

**Closed by maxpatiiuk** 2023-12-06 04:41 UTC
Labels: 1 - Request, 2 - User Interface
