### ISSUE TITLE
[a11y] Enabling taxon tiles dramatically slows Specify

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1332] opened 2022-04-26 13:58 UTC
**Describe the bug**
Enabling taxon tiles slows the Specify experience to a crawl. It can take a minute to interact with buttons

**To Reproduce**
1. Enable taxon tiles for the welcome page
2. View welcome page

**Expected behavior**
It should show the taxon tiles

**Screenshots**
![msedge_vPFbuvzLUP](https://user-images.githubusercontent.com/37256050/165316251-faf5a358-2a3d-4b43-b150-556d8a789b64.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - i7-3770, 16GB RAM

**Comment by maxxxxxdlp** [comment] 2022-04-28 22:35
Fixed in 91eb26f5
The performance issues were caused by all tiles being squeezed into a `497px X 1px` space

**Closed** 2022-05-20 01:58 UTC
Labels: type:bug, pri:unknown
