### ISSUE TITLE
Remove intrinsic size limitation for attachments 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1974] opened 2022-08-16 19:46 UTC
<img width="1795" alt="image" src="https://user-images.githubusercontent.com/37256050/184970704-b1cdb749-4998-4449-a51c-22024a3c6ce2.png">

123px is arbitrary and should be expanded. Even blurry the icon looks better.

**Comment by maxxxxxdlp** [comment] 2022-09-12 18:37
Duplicate of https://github.com/specify/specify7/issues/1812

**Closed by maxxxxxdlp** 2022-09-12 18:37 UTC
Labels: type:bug, pri:unknown
