### ISSUE TITLE
Taxonomic Rank field displays API URL

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4666] opened 2024-03-18 16:51 UTC
**Describe the bug**
When viewing a Taxon record with no parent nodes (highest rank), the Taxonomic Rank field displays an API URL instead of the field being blank.

**To Reproduce**

1. Go to Taxon Tree
2. Click on the highest ranking node/node with no parents (https://fwri1924-edge.test.specifysystems.org/specify/view/taxon/12689/)
3. See the **Taxonomic Rank** field contains an API URL 

**Expected behavior**
Taxonomic Rank field should be blank if there are no parent nodes.
Behavior from **`v7.9.3`**:
![expected](https://github.com/specify/specify7/assets/118556884/4bd488b7-8665-4e6e-a27a-bbcf9b7e5b8f)

**Evidence**
![issue](https://github.com/specify/specify7/assets/118556884/3a4afdee-d16d-40be-92ed-a97117824583)

https://github.com/specify/specify7/assets/118556884/08e1c353-78f4-43c0-8ae7-fde99972f905

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `fwri_1_9_24`

**Comment by pashiav** [comment] 2024-03-25 16:22
1. Create a taxon record from Data Entry => Taxon (https://umherb11024-edge.test.specifysystems.org/specify/view/taxon/new/) 
2. Select a high ranking node as Parent that is not the root node (e.g. Fungi)
3. See Taxonomic Rank field contains API URL in form
![Screen Shot 2024-03-25 at 11 14 03 AM](https://github.com/specify/specify7/assets/118556884/7efb2c8f-e054-4af8-9a1b-d053fabccdcb)

**Comment by melton-jason** [comment] 2024-03-26 15:49
I could not directly recreate the issue, however I did encounter another issue with the value not being actually set into the field when initially loaded. 

https://github.com/specify/specify7/assets/64045831/4b62e056-9dc1-466b-b497-0bf6c3c13fe7

@specify/ux-testing can you recreate either this issue or https://github.com/specify/specify7/issues/4666#issuecomment-2018396940?

**Comment by emenslin** [comment] 2024-03-26 16:22
@melton-jason Can recreate this issue https://github.com/specify/specify7/issues/4666#issuecomment-2020804892 

https://github.com/specify/specify7/assets/150940840/36a7cc76-3ab9-43f9-9aca-f5336fda52cd


And I'm not sure if this is the same issue as Pashia mentioned here https://github.com/specify/specify7/issues/4666#issuecomment-2018396940 but I did run into this 

https://github.com/specify/specify7/assets/150940840/bffe11ea-993b-4972-9000-b91dc6f42fe2

**Comment by melton-jason** [comment] 2024-03-26 17:30
>  qI0BCYRfzR.mp4 
> And I'm not sure if this is the same issue as Pashia mentioned here [#4666 (comment)](https://github.com/specify/specify7/issues/4666#issuecomment-2018396940) but I did run into this
> 
>  4ewn4voNRy.mp4

This specific issue is related to #2637, and occurs in `v7.9.3.1` as well, so it will likely not be addressed in `v7.9.4`. 

---

With regards to the other issue mentioned, here is what I have found in the code. 

The issue is not with the field value on the resource object.
Which is being set from
https://github.com/specify/specify7/blob/967d0d28c342e8d9d365f878053f0b82c90ed7b2/specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx#L123-L125

The underlying issue is with regards to parseResults in the useResourceValue hook. 
In this case `parseResults` returns `{isValid: false, value: <treeDefItemUrl>, reason: ''}`

https://github.com/specify/specify7/blob/967d0d28c342e8d9d365f878053f0b82c90ed7b2/specifyweb/frontend/js_src/lib/hooks/useResourceValue.tsx#L116-L121

The problem is that the value is never being set on the HTML input element itself. 
Because of this, the [valueMissing](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/valueMissing) attribute remains `true`. 

https://github.com/specify/specify7/blob/967d0d28c342e8d9d365f878053f0b82c90ed7b2/specifyweb/frontend/js_src/lib/utils/parser/parse.ts#L41-L45

**Closed** 2024-03-28 17:20 UTC
Labels: 1 - Bug, 2 - Trees, 2 - Forms
