### ISSUE TITLE
Error message when query for new determiner entry date

### ISSUE THREAD

**Issue by mc0822** [specify/specify7#2750] opened 2023-01-04 21:31 UTC
**Describe the bug**
FWRI reports getting error message when querying for new determiner entry date.

**To Reproduce**
1. Go to query builder (see link below).
2. Run query.
3. See error:
[Specify 7 Crash Report - 2023-01-04T21_05_18.765Z.txt](https://github.com/specify/specify7/files/10347511/Specify.7.Crash.Report.-.2023-01-04T21_05_18.765Z.txt)

Link: https://fwri.specifycloud.org/specify/query/105/

**Expected behavior**
Expect to be able to run this query successfully.

**Screenshots**
![QueryError01032023](https://user-images.githubusercontent.com/111374878/210652181-40b3aec3-8e0c-4e1f-8536-73bf6ec2ae69.png)

**Desktop:**
OS: Windows 10
Browser: Edge

**Database Name:** 
fwri (6.8.01)

**Reported By**
Eric Post, FWRI

**Comment by grantfitzsimmons** [comment] 2023-01-05 01:28
https://fwri2023-favicon-improvements.test.specifysystems.org/specify/query/105/

user: `epost`

```
AttributeError at /stored_query/ephemeral/
'Relationship' object has no attribute 'otherSideName'
```

```
AttributeError at /stored_query/ephemeral/
'Relationship' object has no attribute 'otherSideName'
```

[Specify 7 Crash Report - 2023-01-05T01_27_42.148Z.txt](https://github.com/specify/specify7/files/10348617/Specify.7.Crash.Report.-.2023-01-05T01_27_42.148Z.txt)

**Comment by grantfitzsimmons** [comment] 2023-01-05 01:28
Duplicate of #2305

**Closed by grantfitzsimmons** 2023-01-05 01:28 UTC
Labels: type:bug, pri:unknown
