### ISSUE TITLE
[testability] Editing then saving a picklist does not immediately apply changes

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2297] opened 2022-10-05 21:22 UTC
**Describe the bug**
When editing a picklist (from the Schema config) in the Picklist editor, once the picklist is saved the changes do not _seemingly_ (see *Notable behavior* ) occur in Specify. The changes do not reflect on any Forms or Query. 

**To Reproduce**
1. Go to Schema Config
2. Click on any field that currently has a pick list 
3. Click on the pencil icon to edit the picklist
4.  Make any changes to the picklist (either adding/removing items, or changing the name of an item)
5.  Save the picklist
6.  Create a new Form or Query (what was changed, CO, Agent, Locality...)
7.  See the values have not been updated

**Notable behavior**
The Pick List _does_ save when the save button is clicked: When the picklist is viewed again in the pick list editor, the changes remain. However these changes do not apply anywhere else in Specify. The only way to propagate the changes through Specify is to navigate back to the schema config, make a change (like selecting a different pick list from the pick list selection), change it back to how it originally was, and then save the schema.

**Desktop**
- Chrome on Windows 11
 - Specify 7 Version: testability

**Database Name** 
`willemcatno`

**Comment by maxxxxxdlp** [comment] 2023-03-18 02:34
Is this reproducible on the `xml-editor` branch?
Is this fixed by opening an incognito branch (to clean cache)?

**Comment by chanulee1** [comment] 2023-03-20 20:03
@maxxxxxdlp Does not seem to be reproducible on `xml-editor` since picklist editor is now a dialog . Editing picklist and then clicking 'save' in the schema config propagates the changes to the data entry forms. Is it ok to close this issue?

**Closed** 2023-03-20 20:08 UTC
Labels: type:bug, pri:unknown
