### ISSUE TITLE
Desynonymize Node confirmation dialog lists one name twice

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#5083] opened 2024-07-09 16:29 UTC
**Describe the bug**

When desynonymizing a node in trees, the confirmation dialog shows the name of the synonymized node twice rather than the selected node name and the synonym node name. 

The correct names are used when synonymizing, this issue only occurs when desynonymizing nodes

**To Reproduce**

1. Go to Trees
2. Click on synonymized node or create one
3. Click on synonymize button
4. See same name used in confirmation dialog

**Expected behavior**

Dialog should correctly identify both names when desynonymizing nodes in trees

**Screenshots**

Synonymizing: 
<img width="1276" alt="Screenshot 2024-07-09 at 11 15 42 AM" src="https://github.com/specify/specify7/assets/135047322/464fb557-35eb-4ed2-9cf3-a97e62ac37c4">

Desynonymizing:
<img width="1276" alt="Screenshot 2024-07-09 at 11 15 15 AM" src="https://github.com/specify/specify7/assets/135047322/2f87ec3c-12c4-4b15-8e6e-66d53b5b2c31">

- OS: macOS
- Browser: Chrome
- Specify 7 Version: 7.6.1
- Database Name: demofish
- Collection name: KU Fish Tissue

**Reported By**
Willem @ SAIAB

**Comment by grantfitzsimmons** [comment] 2024-07-18 17:26
Duplicate of https://github.com/specify/specify7/issues/4477

**Closed by grantfitzsimmons** 2024-07-18 17:26 UTC
Labels: 1 - Bug, 2 - Trees
