### ISSUE TITLE
Specify 6 batch editing added entries in DataEntryTaskInit

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#458] opened 2018-05-25 15:59 UTC
This can cause multiple copies of a form to be listed.

**Comment by benanhalt** [comment] 2018-05-25 16:02
![issue458](https://user-images.githubusercontent.com/287254/40554370-1be52b74-600b-11e8-9385-f8583d5c04f8.png)

**Comment by maxxxxxdlp** [comment] 2021-09-14 03:31
Possible duplicate of #636

**Closed** 2022-05-20 01:50 UTC
Labels: type:bug
