### ISSUE TITLE
[a11y] Field showing as required to run a query

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1417] opened 2022-05-06 19:09 UTC
**Describe the bug**
A field requires a value for a query to be run.

**To Reproduce**
1. Go to 
https://a11y-2-2-2-2.test.specifysystems.org/specify/query/173/
2. Delete the Name value, see error.

**Expected behavior**
In `edge` this query runs without any value just fine.
![image](https://user-images.githubusercontent.com/37256050/167202459-ad75c288-dd88-4c05-bf34-51f05e9fcb3b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/167202374-ba44c789-5d05-48fc-b166-94c703a90658.png)

macOS, Edge

**Comment by grantfitzsimmons** [comment] 2022-05-06 19:11
username: collection

**Comment by grantfitzsimmons** [comment] 2022-05-06 19:13
![image](https://user-images.githubusercontent.com/37256050/167202916-913bb997-f501-410b-82b3-dd4f9d1923bc.png)

This may be due to the table requiring the field to save

**Comment by maxxxxxdlp** [comment] 2022-05-06 19:14
You can not run a query with missing query condition in the new query builder.
Either provide a value, or change the filter to "any"

**Comment by grantfitzsimmons** [comment] 2022-05-06 19:15
Maybe it should default to "Any" if a user attempts to run the query without a value

**Comment by maxxxxxdlp** [comment] 2022-05-06 19:29
Doesn't that defeat the purpose of validation?

**Comment by grantfitzsimmons** [comment] 2022-05-06 19:31
Maybe there should be a dialog that offers to switch it to Any. Is there a demand for validation in the QB?

**Comment by maxxxxxdlp** [comment] 2022-06-15 04:03
Duplicate of #1419

**Closed by maxxxxxdlp** 2022-06-15 04:03 UTC
Labels: type:bug, pri:unknown
