### ISSUE TITLE
Person can have members

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#583] opened 2020-01-20 16:26 UTC
![Screenshot from 2020-01-20 08-25-06](https://user-images.githubusercontent.com/40512816/72742350-62df7e00-3b5e-11ea-9387-e5bd73941068.png)

Even though the `Agent type` is `Person`, I am still able to add members

**Comment by benanhalt** [comment] 2020-01-21 17:52
duplicate of #364

**Closed by benanhalt** 2020-01-21 17:52 UTC
Labels: type:bug
