### ISSUE TITLE
Search form for Agent query combobox does not work properly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4278] opened 2023-12-11 17:27 UTC
**Describe the bug**
The form search form for the Agent table that displays with every query combo box displays incorrectly and is missing functionality. There must be a bug for this already.

**To Reproduce**
1. Go to an Agent query combo box
2. Click on the 🔍 (search) icon
3. See issue

**Expected behavior**
It should work as it does in Specify 6 or we should show the query builder with a pre-made query by default.

<img width="902" alt="image" src="https://github.com/specify/specify7/assets/37256050/3de2637d-f679-4e78-a001-9fb9f9e92f03">

**Screenshots**
![image](https://github.com/specify/specify7/assets/37256050/cce92f43-9c5a-4b9d-94b0-172bcf864ea3)

**Comment by grantfitzsimmons** [comment] 2023-12-11 17:29
For reference, here's the definition in the `search.views.xml` file:

```xml
        <viewdef type="form"
            name="AgentSearch"
            class="edu.ku.brc.specify.datamodel.Agent"
            gettable="edu.ku.brc.af.ui.forms.DataGetterForHashMap"
            settable="edu.ku.brc.af.ui.forms.DataSetterForHashMap">
            
            <desc><![CDATA[The Agent Search Form]]></desc>
            <enableRules/>
            
            <columnDef>p,3dlu,p,3dlu,p,3dlu,p,3dlu,p</columnDef>
            <rowDef>p,2dlu,p,2dlu,p,2dlu,p,2dlu,p,2dlu,p,2dlu,p,2dlu,p,2dlu,p</rowDef>
            
            <rows>
                <row>
                    <cell type="separator" label="Agent Info" colspan="7"/>
                </row>
                <row>
                    <cell type="label" labelfor="1"/>
                    <cell type="field" id="1" name="LastName" uitype="text" cols="20"/>
                    <cell type="label" labelfor="2"/>
                    <cell type="field" id="2" name="FirstName" uitype="text" cols="20"/>
                </row>
                <row>
                    <cell type="label" labelfor="4"/>
                    <cell type="field" id="4" name="Addresses" uitype="text" colspan="6"/>
                </row>
                <row>
                    <cell type="label" labelfor="5"/>
                    <cell type="field" id="5" name="addresses.City" uitype="text" cols="20"/>
                    <cell type="label" labelfor="6"/>
                    <cell type="field" id="6" name="addresses.State" uitype="text" cols="15"/>
                </row>
                <row>
                    <cell type="label" labelfor="7"/>
                    <cell type="field" id="7" name="addresses.Postalcode" uitype="text" cols="11"/>
                    <cell type="label" labelfor="8"/>
                    <cell type="field" id="8" name="addresses.Country" uitype="text" cols="20"/>
                </row>
            </rows>
        </viewdef>
```

https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/config/backstop/search.views.xml#L417-L456

**Comment by maxpatiiuk** [comment] 2023-12-12 22:37
Duplicate of https://github.com/specify/specify7/issues/1503

**Closed** 2023-12-12 22:39 UTC
Labels: 1 - Bug, res:duplicate, 2 - Queries, 2 - User Interface
