### ISSUE TITLE
Improve the `docker-compose.yml` setup

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4110] opened 2023-10-13 17:17 UTC
Instead of repeating values twice that only need to be established once, we should consider using a `.env` file.

Right now, you need to establish this environment **twice**, once for the worker and once for the service.

```yml
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_NAME=specify
      - MASTER_NAME=master
      - MASTER_PASSWORD=master
      - SECRET_KEY=change this to some unique random string
      - ASSET_SERVER_URL=http://host.docker.internal/web_asset_store.xml
      - ASSET_SERVER_KEY=your asset server access key
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/1
      - LOG_LEVEL=WARNING
      - SP7_DEBUG=true
```

We could use a `.env` file to set these things once for both to prevent unnecessary issues.

**Comment by maxxxxxdlp** [comment] 2023-10-14 01:39
This issue is a duplicate of https://github.com/specify/docker-compositions/issues/20
Also, can you take a look at the changes in https://github.com/specify/docker-compositions/pull/21?

**Comment by grantfitzsimmons** [comment] 2023-10-14 17:51
@maxxxxxdlp They are different repositories with different goals, I think both need to happen, but implementation is different (development v. production) :smile:

I am reviewing your PR and implementing many of your ideas on this repo as well. Great work!

**Closed** 2023-10-19 22:10 UTC
Labels: 1 - Request, type:meta
