### ISSUE TITLE
`Data too long for column 'Name' at row 1` when attempting a WorkBench upload

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2570] opened 2022-12-09 14:19 UTC
**Full data set name:** `Refresh_Chakona_Western_Cape_April_2022_Observations`

The field type for the Name field in the `spdataset` table is `varchar(256)`, indicating to me that it can contain many more characters than the 52 characters in this data set name.

**Mapping:**
[WorkBench mapping](https://github.com/specify/specify7/files/10195570/Pedro.txt)

**Data Set:**
[Refresh_Chakona_Western_Cape_April_2022_Observations.csv](https://github.com/specify/specify7/files/10195572/Refresh_Chakona_Western_Cape_April_2022_Observations.csv)

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/206721903-df6aacb7-967a-442b-9292-ebd78aa6c854.png">

**Full worker log output:**
```
Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.8/site-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/specify7/specifyweb/workbench/tasks.py", line 41, in upload
    do_upload_dataset(collection, uploading_agent_id, ds, no_commit, allow_partial, progress)
  File "/opt/specify7/specifyweb/workbench/upload/upload.py", line 136, in do_upload_dataset
    rs = create_record_set(ds, base_table, results) if results and success else None
  File "/opt/specify7/specifyweb/workbench/upload/upload.py", line 163, in create_record_set
    rs = getattr(models, 'Recordset').objects.create(
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/specify7/specifyweb/specify/build_models.py", line 55, in save
    return super(model, self).save(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/base.py", line 740, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/base.py", line 777, in save_base
    updated = self._save_table(
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/base.py", line 907, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
    cursor.execute(sql, params)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'Name' at row 1")
```

See `willemcatno` in the Fish Observation Collection- user `collection`
https://willemcatno-edge.test.specifysystems.org/specify/workbench/141/

**Reported By:** Willem at SAIAB

**Comment by maxxxxxdlp** [comment] 2022-12-09 14:20
Are they on 6.8.02?

**Comment by grantfitzsimmons** [comment] 2022-12-09 14:21
No– but the upload works when the name is shortened as I suspected

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/206722815-74f27209-a0a3-404f-a325-6bea57b2fbbb.png">

**Comment by grantfitzsimmons** [comment] 2022-12-09 14:22
Record set name, isn't it?

**Comment by grantfitzsimmons** [comment] 2022-12-09 14:23
There should still be better handling of this error, but I see the problem. 

Record Set `Name` is only 64 chars

**Comment by maxxxxxdlp** [comment] 2022-12-09 14:23
@grantfitzsimmons https://github.com/specify/specify6/issues/1158#issuecomment-1282869587

**Comment by maxxxxxdlp** [comment] 2022-12-09 14:24
Duplicate of https://github.com/specify/specify6/issues/1158 - already fixed

**Closed by maxxxxxdlp** 2022-12-09 14:24 UTC
Labels: type:bug, pri:unknown
