### ISSUE TITLE
Query Builder not scoping collections during CO relationships

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#3253] opened 2023-03-27 16:31 UTC
**Describe the bug**
Consider this query over collecting events. I'm currently logged in KU Fish Teaching collection. The query builder is returning collecting events which have collection objects from a different collection. In the screenshot, the collection object returned is from KU Fish Voucher collection - this is fine, and not an issue. 

However, if you were to make any changes to the form, then it is not letting me save it since it requires catalog number to be of 5 digits (in KU Fish Teaching Collection). Since the catalog number need to be of more digits in the KU Fish Voucher Collection), the form throws an error saying the catalog number doesn't match the required format.

The collecting event - https://coldfish-edge-2.test.specifysystems.org/specify/view/collectingevent/4/

The bug screenshot
![image](https://user-images.githubusercontent.com/61122018/228005146-604b00f7-c35b-42ae-8f60-9d0167642ea3.png)

**Comment by maxxxxxdlp** [comment] 2023-03-27 18:48
I belive this is a duplicate of https://github.com/specify/specify7/issues/2902

@realVinayak If so, can you merge it with that issue or extend it?

**Comment by grantfitzsimmons** [comment] 2023-08-07 03:09
Duplicate of #2902

**Closed by grantfitzsimmons** 2023-08-07 03:09 UTC
Labels: 1 - Bug, 2 - Queries
