### ISSUE TITLE
`BusinessRuleException` when deleting and re-adding a collector with the same agent

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2980] opened 2023-02-13 14:53 UTC
```
BusinessRuleException at /api/specify/collectingevent/6/
```

```
('Collector must have unique agent in collectingevent', {'table': 'Collector', 'localizationKey': 'childFieldNotUnique', 'fieldName': 'agent', 'fieldData': ('agent', {'id': 626, 'abbreviation': None, 'agenttype': 1, 'date1': None, 'date1precision': None, 'date2': None, 'date2precision': None, 'dateofbirth': None, 'dateofbirthprecision': 1, 'dateofdeath': None, 'dateofdeathprecision': 1, 'datetype': None, 'email': None, 'firstname': 'Donald', 'guid': 'e0b196c7-f3af-4e3e-a5ef-5e8f8bf664ae', 'initials': None, 'integer1': None, 'integer2': None, 'interests': None, 'jobtitle': None, 'lastname': 'Huggins', 'middleinitial': 'E', 'remarks': None, 'suffix': None, 'text1': None, 'text2': None, 'text3': None, 'text4': None, 'text5': None, 'title': 'mr', 'url': None, 'verbatimdate1': None, 'verbatimdate2': None, 'version': 1, 'collcontentcontact': None, 'colltechcontact': None, 'createdbyagent': 1986, 'division': 2, 'instcontentcontact': None, 'insttechcontact': None, 'modifiedbyagent': 1987, 'organization': None, 'specifyuser': None}), 'parentField': 'collectingevent', 'parentData': 'collectingevent: id=6', 'conflicting': [2500]})
```

[Specify 7 Crash Report - 2023-02-13T14 53 10.570Z.txt](https://github.com/specify/specify7/files/10723351/Specify.7.Crash.Report.-.2023-02-13T14.53.10.570Z.txt)

---

This is a spin-off of #2884 focused on the underlying issue

> 
> I was editing the collectors in a record.
> 
> They were in the wrong order, so I deleted, them, and put them back, when I hit save, I got this error. Maybe I should have saved after I deleted???

**Reported by:** Heather Cole at AAFC

**Comment by maxxxxxdlp** [comment] 2023-02-14 04:19
Possibly related to https://github.com/specify/specify7/issues/1702

**Comment by melton-jason** [comment] 2023-03-14 21:31
This is caused by the same bug which caused #1702.

> This occurs for every `-to-many` relationship and is related to the way the frontend checks uniqueness rules. Essentially, when there is a `-to-many` relationship, the frontend would only check records within that `-to-many` relationship. Thus the database contains the values, but the frontend simply thinks it is a new AccessionAgent, and is only checking other AccessionAgents in that Acession.
> 
> So this specific case was not accounted for.

From https://github.com/specify/specify7/issues/1702#issuecomment-1468695227

**Comment by emenslin** [comment] 2024-05-31 19:00
Duplicate of #1702

**Closed by emenslin** 2024-05-31 19:00 UTC
Labels: 1 - Bug, 2 - Forms
