### ISSUE TITLE
[testability] Unable to delete cloned CO record 

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2557] opened 2022-12-07 17:50 UTC
Unable to delete a cloned CO record in `kufishnotests`. Maybe caused by the enabled "embedded CE record"  for CO records? The record that was cloned from did not have an associated CE record, but the cloned record automatically contained an embedded CE record.

In video: record 13 is original record, record 14 is cloned record

https://user-images.githubusercontent.com/103299204/206255975-fde1ecf4-32ee-4f50-9061-573827d96f27.mp4

[Specify 7 Crash Report - 2022-12-07T17_40_24.484Z (1).txt](https://github.com/specify/specify7/files/10178620/Specify.7.Crash.Report.-.2022-12-07T17_40_24.484Z.1.txt)

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/61200/?recordsetid=44

**Comment by chanulee1** [comment] 2022-12-07 19:04
That record (record 13 in the RS) that was cloned from is also unsaved upon navigation, and a flicker of the save warning dialog can be seen when navigating away from it -- relation to #2483?


https://user-images.githubusercontent.com/103299204/206272535-d68e52bb-2d9b-4213-8949-96ae79021b61.mp4


https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/61200/?recordsetid=44

**Comment by maxxxxxdlp** [comment] 2022-12-09 14:48
New collecting event is created automatically because of a business rule. The business rule can not be disabled until https://github.com/specify/specify7/issues/2056 is implemented

**Comment by maxxxxxdlp** [comment] 2022-12-09 14:53
The error is caused by https://github.com/specify/specify7/issues/2562
Since that bug is now fixed, this should not happen again, though the cloned CO can't be deleted anymore

**Comment by maxxxxxdlp** [comment] 2022-12-09 14:57
Unable to replicate the false unload protect dialog. Does it still happen for you?
If so, please open a separate issue for is as it's unrelated to this

**Closed** 2022-12-09 14:57 UTC
Labels: type:bug, pri:unknown

**Comment by chanulee1** [comment] 2022-12-09 16:34
Cannot replicate false unload protect dialog. Probably fixed by #2562.
