### ISSUE TITLE
Clearing browser cache on Error dialog breaks Go To Home Page button

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4568] opened 2024-02-20 16:32 UTC
**Reported By:** Dan @ CSIRO 

> When experiencing a crash report from specify, if you tick the box "Clear Browser Cache" before clicking the "Go To Homepage" button then the crash page does not disappear and will not return to the homepage. 
> 
> Steps:
> Perform a query and in the results page, click the "Create Record Set" button without selecting any of the results
> Tick the "Clear Browser Cache" tickbox and then click the "Go To Homepage" button
> 
> Expected:
> System clears the browser cache and returns to the homepage
> 
> Actual:
> System flickers the crash page and does not return to the homepage. Crash notification remains on screen. 

Recreated on demofish! 

- macOS, Chrome, `v7.9.3.1`

https://github.com/specify/specify7/assets/135047322/573fe147-e6f0-4b30-aa0e-964a7730d2e0

**Comment by melton-jason** [comment] 2024-02-20 17:16
@specify/ux-testing 
Is this fixed in #4435?

**Comment by emenslin** [comment] 2024-02-20 17:28
>Is this fixed in #4435?

Yes it is fixed in #4435

**Comment by melton-jason** [comment] 2024-02-20 17:31
Duplicate of #4432
Will be fixed by #4435

**Closed by melton-jason** 2024-02-20 17:31 UTC
Labels: 1 - Bug, 2 - User Interface
