### ISSUE TITLE
Already Saved Query with enabled `Save Query` Button

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3548] opened 2023-05-31 21:03 UTC
**Describe the bug**
This particular query is already saved. However, I am able to use the Save Query Button and it leads to a crash.

**To Reproduce**
1. Go to NHDM -> NHMD Amber -> Queries 
2. Click on  DarwinCore Types IV
3. Click `Save Query`

**Expected behavior**
A disabled Save Query Button

**Evidence**
[Specify 7 Crash Report - 2023-05-31T18_45_16.246Z (1).txt](https://github.com/specify/specify7/files/11617866/Specify.7.Crash.Report.-.2023-05-31T18_45_16.246Z.1.txt)
[Specify 7 Crash Report - 2023-05-31T18_45_16.246Z.txt](https://github.com/specify/specify7/files/11617867/Specify.7.Crash.Report.-.2023-05-31T18_45_16.246Z.txt)

https://github.com/specify/specify7/assets/53784701/f8cae1df-034d-4fbf-83a3-b8f886ca4904

**Desktop:**
 - OS: Mac OSx Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.11

**Database Name:** NHMD

**Comment by melton-jason** [comment] 2023-05-31 21:20
Is this reproducible for other Queries or just this one? 
This may be in part (or wholly) due to the fact that that is not a traditional Query. 
It looks like this is a Schema Mapping, created in Specify 6. 
See related #1385

If you're unfamiliar with what a Schema Mapping is, we have a Helpcast video available on the Speciforum 
https://discourse.specifysoftware.org/t/helpcast-schema-mapper/352

**Comment by carlosmbe** [comment] 2023-05-31 21:31
This reproducible in all `DarwinCore Types` Queries in this Database. It seems that during the initial load, some changes are applied automatically as Specify prompts me before leaving the query that changes were made.

<img width="735" alt="Screenshot 2023-05-31 at 4 30 27 PM" src="https://github.com/specify/specify7/assets/53784701/16cb9c3d-0c85-470c-893b-8cfd0ec8dfab">

<img width="476" alt="Screenshot 2023-05-31 at 4 28 32 PM" src="https://github.com/specify/specify7/assets/53784701/6e845f44-f13e-481e-9448-46c9a82b4a6a">

I'll work through the video before investigating further and report my findings

**Comment by melton-jason** [comment] 2023-05-31 22:03
@CarolineDenis @grantfitzsimmons 
What do you all think about making Schema Mappings readonly until we implement proper support for them?

**Comment by maxxxxxdlp** [comment] 2023-06-01 16:55
Duplicate of https://github.com/specify/specify7/issues/1385
This applies only to schema mappings, not regular queries - in sp6 schema mappings are not shown in the list of queries, because there is a separate menu for schema mappings
This should be fixed as part of https://github.com/specify/specify7/issues/285

**Closed by maxxxxxdlp** 2023-06-01 16:55 UTC
Labels: type:bug, pri:unknown

**Comment by grantfitzsimmons** [comment] 2023-06-09 21:21
> @CarolineDenis @grantfitzsimmons What do you all think about making Schema Mappings readonly until we implement proper support for them?

We need to make it clear to the user that it is not a query but a schema mapping in the interface.
