### ISSUE TITLE
Add ability to show specific rank of determination on the form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1939] opened 2022-08-04 23:22 UTC
Currently, you can specify the taxon.parent.parent to show the Family of a Species, but it would be nice to be able to specify the exact rank so there can be the family on every form regardless of the determination's rank.

**Comment by maxxxxxdlp** [comment] 2022-08-11 02:57
Duplicate of #805

**Closed by maxxxxxdlp** 2022-08-11 02:57 UTC
Labels: type:enhance, pri:unknown
