### ISSUE TITLE
DataObjFormatter "format" attribute not working correctly

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2351] opened 2022-10-25 17:06 UTC
See DataObjFormatter definition:

```xml
      <format
        name="Locality"
        title="Locality"
        class="edu.ku.brc.specify.datamodel.Locality"
        default="true"
        >
        <switch single="true">
            <fields>
                <field>localityName</field>
                <field sep="; ">geography.fullName</field>
                <field type="bigdecimal" format="%9.2f" sep="; ">latitude1</field>
                <field type="bigdecimal" format="%9.2f" sep=", ">longitude1</field>
            </fields>
        </switch>
    </format>
```

The `format` attribute on `<field />` is ignored by the front-end, but causes the back-end to get confused and output the raw value of the output rather than a formatted output:

![Screen Shot 2022-10-25 at 12 03 58](https://user-images.githubusercontent.com/40512816/197837313-490fda8a-3d6a-4a20-bba9-1d63dc587581.png)

Seems to happen here - https://github.com/specify/specify7/blob/774d108124c8d8f74c4e24feead2def47a83e5eb/specifyweb/stored_queries/format.py#L67

Discovered by @grantfitzsimmons

**Comment by grantfitzsimmons** [comment] 2023-08-06 23:12
**Is your feature request related to a problem? Please describe.**
While you can truncate the coordinates in the drop downs and QCBXs in how they display, you cannot do this for the aggregated output.

![image](https://user-images.githubusercontent.com/37256050/164517238-2248954b-7c7f-4e25-8bfd-79367711eb7b.png)

**Describe the solution you'd like**
A simple way to truncate coordinates in the aggregation settings.

**Reported By**
CSIRO

**Comment by grantfitzsimmons** [comment] 2023-08-06 23:13
Duplicate of https://github.com/specify/specify7/issues/1306

**Closed by grantfitzsimmons** 2023-08-06 23:13 UTC
Labels: 1 - Bug, 2 - Forms
