### ISSUE TITLE
Linking field auto-filled with formatted record value in tables linked through query combobox

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#4001] opened 2023-09-11 19:06 UTC
The Station Field Number field is getting auto-filled with the previous, formatted Collecting Event record's value when switching from a selected CE to a new one on the CO form.

To reproduce:
1) in a database where the CE/CO relationship is shared, in the CO form, select an existing CE.
2) decide that isn't the one you want and you want a new one, so click the green plus to add a new CE record.

The Station Field Number field will get filled in with the formatted value for the previous record.

**Comment by tlammer** [comment] 2023-09-11 19:06
https://github.com/specify/specify7/assets/12532430/40968842-6542-4918-896f-ae0eace69d17

**Comment by tlammer** [comment] 2023-09-11 21:24
It's more complicated than originally reported.  It appears to happen in tables linked through query comboboxes even when the query combobox has not had anything in it?

https://github.com/specify/specify7/assets/12532430/8208c868-5994-453a-afaa-658f426fa37c

**Comment by emenslin** [comment] 2024-08-05 19:47
Duplicate of #4984

**Closed by emenslin** 2024-08-05 19:47 UTC
Labels: 1 - Bug
