### ISSUE TITLE
Tree level combo box is not marked as required while loading, allowing to save (with crash)

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2171] opened 2022-09-19 14:51 UTC
Instead of `<select disabled>` use `<select><option disabled /></select>`

**Comment by CarolineDenis** [comment] 2023-11-08 15:46
@maxxxxxdlp , could you indicate me where can I find this combo box in sp7?

**Comment by maxxxxxdlp** [comment] 2023-11-12 22:01
sure, should have been clearer with this

when creating any tree record (taxon/geography/storage/litho...), there is a combo box for selecting the tree rank for the new record.
but tree ranks take time to fetch
once fetched, the field is marked as required
but, until ranks are fetched, the combo box is disabled, which supersedes the `required` status, thus allowing user to try to save the tree record without a tree rank, which causes a back-end exception

**Comment by CarolineDenis** [comment] 2023-11-13 20:51
@maxxxxxdlp, On the xml branch I cannot replicate the behavior you are describing. When the ranks are loading, the pick list is indeed empty but the save button is disabled. When save clicked, a focus is set to 'Taxonomic Rank' stating: 'Please fill out this field'

**Comment by maxxxxxdlp** [comment] 2023-11-14 00:51
interesting. do you know what is causing the save button to be disabled?
i.e we need to make sure it's disabled because ranks are not fully loaded rather than for some other reason that happened to coincide with when we needed to have the button disabled

**Comment by CarolineDenis** [comment] 2023-11-14 14:56
@maxxxxxdlp, it is disabled because taxonomic rank is empty. 
I cannot replicate the behavior you are describing in the issue in 7.8 neither. It is also disabled bu field is required.

**Comment by maxxxxxdlp** [comment] 2023-11-15 02:43
From what I remember, this was way easier to reproduce when specify7 back-end is running on an arm MacBook, rather than on the test panel.

The steps:
Open the taxon form directly (i.e by putting this into the url - /specify/view/taxon/new/)
type a name and parent
tree ranks are not loaded yet, so the tree ranks picklist is still disabled
try saving - see error.

if you want to replicate this on a fast server like the test panel, I was able to do so by enabling network throttling in the devtools ("Slow 3g")

![Screenshot 2023-11-14 at 18 43 01](https://github.com/specify/specify7/assets/40512816/2628f13b-c531-43f3-840f-238eb73cce7d)



Reproduction:
https://github.com/specify/specify7/assets/40512816/26db86d2-ce22-4f6e-9406-8b370daf3235

**Comment by CarolineDenis** [comment] 2023-11-15 14:43
@maxxxxxdlp , tested on slow 3G on xml editor, cannot save without tree rank. I think this can be closed. 
<img width="1224" alt="Screenshot 2023-11-15 at 6 42 11 AM" src="https://github.com/specify/specify7/assets/108160931/39566f9a-f759-4136-85e4-d73b07370444">

**Comment by maxxxxxdlp** [comment] 2023-11-16 00:58
Can you take a look at the video I attached in the above comment (looks like github is not displaying the preview, but it's the last link in my comment) - I was able to successfully reproduce this.

**Comment by emenslin** [comment] 2024-05-31 14:20
This specific issue is fixed but there is still some weird behavior, see #4808

**Closed by emenslin** 2024-05-31 14:20 UTC
Labels: 1 - Bug, 2 - Forms
