### ISSUE TITLE
`xml-editor`: Dialog sizing are experiencing issues allover Sp

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4385] opened 2024-01-10 18:59 UTC
**Describe the bug**
The new app resource name dialog should be appropriately sized when you create a new app resource. It has been quite jarring as I've used `xml-editor` more and more. 

Initially I thought it was because I resized it on a specific database but I have been able to recreate this on most databases. _Even if it typically remembers your dialog position/size,_ it should not in this case.

**To Reproduce**
1. Create a new app resource that can be given a name
2. See that the 'New App Resource' dialog is larger than it should be

**Expected behavior**

The behavior on `edge` (`v7.9.2`) is desired. See below:

https://github.com/specify/specify7/assets/37256050/e5c51f59-b022-4fe6-a89a-53cf80d0e227

**Screenshots:**
<img width="1072" alt="Screenshot 2024-01-10 at 12 59 11 PM" src="https://github.com/specify/specify7/assets/37256050/c76da0c5-b876-43cb-bd2d-69bd6654348a">

macOS, Arc

**Comment by CarolineDenis** [comment] 2024-01-10 21:02
Notes: 
- due to dimesionKey

**Comment by maxpatiiuk** [comment] 2024-01-19 04:36
I don't think this is caused by useDialogSize
i.e in useDialogSize set a logpoint to see the value of initialSize
at least on my machine, the bug is reproducable despite `initialSize` being undefined all the time

This could be caused by the Loading skeleton temporary increasing the dialog size, and then `useFreezeDialogSize` getting activated to prevent the dialog from shrinking back

can you verify if that's the case?
if so, one possible solution may be to modify useFreezeDialogSize to ignore dialog size shrinking during the first 1s of dialog existence to account for possibility of dialog resizing while content is loading
(a bit hacky, as 1s timeout is not a silver bullet - it might not be enough on slower servers)
another solution might be to modify the loading skeleton for this table to be smaller (or to make loading skeletons in tables smaller), or to disable loading skeleton for this particular dialog, or to modify loading skeleton styling so that it takes all the space available, but does not force expand the available space

**Comment by CarolineDenis** [comment] 2024-01-19 15:23
@maxpatiiuk, verified that the skeleton is not the cause of the size issue

**Comment by CarolineDenis** [comment] 2024-02-12 22:25
Related issue that should be fixed at the same time: https://github.com/specify/specify7/issues/4519

**Comment by CarolineDenis** [comment] 2024-02-13 16:13
Related issue that should be fixed at the same time (2): https://github.com/specify/specify7/issues/4511

**Closed** 2024-02-19 18:05 UTC
Labels: 1 - Bug, 2 - App Resources
