### ISSUE TITLE
api call in rank field with 'Add' function used in taxon record creation

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4437] opened 2024-01-19 17:59 UTC
**Describe the bug**

Series data entry of taxon records with Clone and Add leads to API call issue in the rank field. Specifically when you clone a newly added taxon record followed by using the Add button to add another new taxon record. The taxon from `Add` has a bad tree structure.

Firefox: save is prohibited with API call in the rank field. Filling the rank field with the expected rank and saving causes an infinite loading dialog. 

Chrome: allows for the user to save the record with the API call in the rank field. 

**To Reproduce**
1. Go to Data Entry > Taxon
2. Fill out parent, name, rank
3. Save
4. Clone the record
5. Save new cloned record
6. Click `Add`
7. Add parent
8. See rank field with api call
9. See error

**Expected behavior**

Should auto-fill rank field with next available rank instead of api call info. 

**Screenshots**

Chrome allowing saving with bad tree structure: 

<img width="1427" alt="Screenshot 2024-01-19 at 11 44 00 AM" src="https://github.com/specify/specify7/assets/135047322/e7097567-def1-4f7a-8a59-3bf27f57d3e7">

Workflow demo: 

https://github.com/specify/specify7/assets/135047322/f4918a62-cdd1-40a7-a3ec-0825ef856aa2

**Desktop:**
 - OS: macOS
 - Browser: Chrome and Firefox
 - Specify 7 Version: `edge`

**Database Name:** `fwri`

**Comment by melton-jason** [comment] 2024-01-19 18:26
Could be a duplicate of #2637

**Comment by CarolineDenis** [comment] 2024-01-25 21:13
> Could be a duplicate of #2637

yes I would say so

**Comment by grantfitzsimmons** [comment] 2024-02-08 16:11
Duplicate of https://github.com/specify/specify7/issues/2637

**Closed by grantfitzsimmons** 2024-02-08 16:11 UTC
Labels: 1 - Bug, 2 - Trees
