### ISSUE TITLE
Unchecking "Show conflicting fields" does not work in the address viewer

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2882] opened 2023-01-25 19:37 UTC
<img width="588" alt="Screenshot 2023-01-25 at 1 37 07 PM" src="https://user-images.githubusercontent.com/37256050/214670100-9c5efe20-9561-4dc8-a8b7-0f08e32d3964.png">

It only changes the agent merge dialog

**Comment by maxxxxxdlp** [comment] 2023-01-30 15:57
It's a bit confusing and I welcome suggestions on how to make it less so, but this is not a bug.

Here is why:
Since you only have one Address resource in each row (excluding the merged one), there are no conflicts.

When there are no conflicts, the "Show conflicting fields only" behaves as if it is not checked (otherwise, it wouldn't show any fields at all - which would be less helpful).

To see "Show conflicting fields only" in action for addresses, move one of the addresses from the 2nd resource to the same row as an address from 1st resource. Now that they are side by side, "Show conflicting fields only" would work like expected

**Closed** 2023-02-22 22:34 UTC
Labels: type:bug, pri:unknown
