### ISSUE TITLE
False success message when WB upload fails with no error cells

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2865] opened 2023-01-21 14:25 UTC
See https://github.com/specify/specify7/pull/1857#issuecomment-1385696750 and https://github.com/specify/specify7/pull/1857#issuecomment-1399261342

**Comment by maxxxxxdlp** [comment] 2023-03-22 00:39
@grantfitzsimmons 

It's funny that this is the opposite of https://github.com/specify/specify7/issues/1835

WB is so big that it simultaneously has two bugs that are opposites of each other

**Comment by emenslin** [comment] 2024-07-24 18:22
Cannot recreate specific issue mentioned in https://github.com/specify/specify7/pull/1857#issuecomment-1385696750 so I'm closing this as a duplicate of #3633

**Closed by emenslin** 2024-07-24 18:22 UTC
Labels: 1 - Bug, todo:verify, 2 - WorkBench
