### ISSUE TITLE
[a11y] Scroll bars appear if preparations subview overflows

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1425] opened 2022-05-06 20:16 UTC
![msedge_g9sSHtDsMr](https://user-images.githubusercontent.com/37256050/167210617-2626d851-3754-41ca-bccf-e78dd329bab5.gif)

If you scroll the Preparations subview (while collapsed) all the way to the right, the unnecessary scrollbars disappear

`saiab`, collection is the username

**Comment by maxxxxxdlp** [comment] 2022-05-20 02:07
Duplicate of [1342](https://github.com/specify/specify7/issues/1342)

**Closed by maxxxxxdlp** 2022-05-20 02:07 UTC
Labels: type:bug, pri:unknown
