### ISSUE TITLE
Automatically put cursor in first field of password popup

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1671] opened 2022-05-19 22:31 UTC
Currently when you click to add password, you have to click the field to start typing the password.  If you're opening the set password dialog, you are likely doing it to enter a password.  It would save time and effort to make it so the cursor is in the field automatically
![image](https://user-images.githubusercontent.com/12532430/169415066-7d68b4d8-53b5-43c5-9a78-ef5e450f11a6.png)

**Comment by maxxxxxdlp** [comment] 2022-05-19 22:48
For this and any other dialogs, as well as forms, press `Tab` once to move focus to the first field.
Here is why it doesn't focus first field automatically: https://github.com/specify/specify7/issues/1543#issuecomment-1125218567
And like I mentioned there, if you think it is important, I can add a pref to change that behavior (instead of requiring just one extra `Tab` click)

**Comment by maxxxxxdlp** [comment] 2023-03-14 00:58
Duplicate of #1543

**Closed by maxxxxxdlp** 2023-03-14 00:58 UTC
Labels: type:enhance, pri:unknown
