### ISSUE TITLE
`xml-editor`: Agent type not displayed as expected in qcbx

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3222] opened 2023-03-20 18:58 UTC
Agent type not displayed as expected in qcbx search results.

https://user-images.githubusercontent.com/103299204/226439293-9af62fdd-119b-4736-8a21-f4c9237eeda3.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/view/collectionobject/61610/

**Comment by maxxxxxdlp** [comment] 2023-03-21 00:17
This is because when the back-end does formatting, it uses pick list item value, rather than the title - not sure how simple that would be to fix (because it constructs a SQL query to do the formatting - it's very performant, but also very feature limited)

In the preview, front-end formatting is used, which supports more features.

**Comment by maxxxxxdlp** [comment] 2023-03-22 00:43
I will close this as a duplicate of #2814 as it's the same back-end issue, manifesting itself in two places (query combo box uses query builder API behind the scenes)

**Closed by maxxxxxdlp** 2023-03-22 00:43 UTC
Labels: type:bug, pri:unknown
