### ISSUE TITLE
Implement "icon" view type

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2432] opened 2022-11-11 02:31 UTC
Sp6 allows viewing attachments subview as a grid of squares. Sp7 does not support that. The closest thing in sp7 is displaying attachments subview as a form table:

![image](https://user-images.githubusercontent.com/40512816/201249638-56834a84-7e29-48e7-9a61-a0f2b3066be9.png)

**Comment by grantfitzsimmons** [comment] 2023-04-03 18:36
> ![image](https://user-images.githubusercontent.com/37256050/229597061-f4e1f08c-c251-484b-8693-125e8dbc18bc.png)
> ![image](https://user-images.githubusercontent.com/37256050/229597070-432fff17-b00d-4462-a572-88d685a59ebb.png)
> 
>  Is it possible to display the icon view in Specify 7? If not, how can the Attachment form be configured to choose the fields to display and their layout?

**Requested By:** [@sorovi on the Speciforum](https://discourse.specifysoftware.org/t/attachment-icon-and-form-views-in-specify-7/1130)

**Comment by specifysoftware** [comment] 2023-04-03 18:43
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/attachment-icon-and-form-views-in-specify-7/1130/2

**Comment by maxxxxxdlp** [comment] 2023-06-09 04:57
It actually seems like this issue is a duplicate of #1048. @grantfitzsimmons do you agree? If so close one of them

**Comment by grantfitzsimmons** [comment] 2023-08-06 20:09
Duplicate of https://github.com/specify/specify7/issues/1048

**Closed by grantfitzsimmons** 2023-08-06 20:09 UTC
Labels: 1 - Request, todo:verify, 2 - Forms
