### ISSUE TITLE
Private Attachments

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3717] opened 2023-07-03 19:27 UTC
**Is your feature request related to a problem? Please describe.**
After Discussing with a Theresa. It was noted that some users would like a way to make certain attachments private so that not everyone with read access can just see all the collection's Attachments bare and exposed.

**Describe the solution you'd like**

Checkboxes in attachments 
- [ ] Is Private 
**OR MAYBE** 
- [ ] Is Sensitive

They should prevent people lacking certain permissions from seeing said attachment. Or maybe it prevents people with a specific role from seeing it. 

The second checkbox (is sensitive) seems ideal if for example they have a visiting professional and they give them a custom role that is limited to what the Collection Manager wants them to see.

For more info, I'd recommend talking to  Theresa.

**Comment by maxxxxxdlp** [comment] 2023-07-04 02:38
Duplicate of #1957

I don't think this feature should be implemented just for attachments - we need to think it though, and make it work for all tables (Locality, Taxon)

**Closed by maxxxxxdlp** 2023-07-04 02:38 UTC
Labels: Request, Users & Permissions, Attachments
