### ISSUE TITLE
Window drag&drop positioning issues

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#569] opened 2020-01-17 17:41 UTC
When I try to move the window, its position changes instantly to a position south of that

Video:
[https://youtu.be/OAoXnRS2vWw](https://youtu.be/OAoXnRS2vWw)

Seems to happen for all of the windows

**Comment by maxxxxxdlp** [comment] 2020-02-07 22:21
Seems to happen only for the `Storage` form when it is a child window
Initially discovered on a local server with Vertebrate Paleontology
Replicated on [http://db1.biwebdbtest.nhm.ku.edu/](http://db1.biwebdbtest.nhm.ku.edu/)

**Comment by maxxxxxdlp** [comment] 2020-02-11 18:54
Also happens with the `Save blocked` window when try to move it

![Screenshot from 2020-02-11 12-53-24](https://user-images.githubusercontent.com/40512816/74268483-8b761600-4ccd-11ea-9696-3fbd2d7bc74f.png)

Found in `TestBiology2` on [http://db2.biwebdbtest.nhm.ku.edu/](http://db2.biwebdbtest.nhm.ku.edu/)

**Comment by benanhalt** [comment] 2021-05-04 20:57
Yes, I believe this is a duplicate of #768

**Closed by benanhalt** 2021-05-04 20:57 UTC
Labels: type:bug
