### ISSUE TITLE
Synonymy in trees breaks associated collection objects in query

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#4718] opened 2024-04-01 21:35 UTC
**Describe the bug**
When clicking on query in the tree using the right-hand menu item, it does not pick up any synonymized lots even though the number indicates that they are now repositioned there.  I suspect this has to do with how the query is structured to search on ID.

**To Reproduce**

1. Go to 'KU_Fish_Tissue' database
2. Search for Bathygobius soporator
3. Note that there are three collection objects associated with this node - one of which is a synonym of Gobius uranoscopius
4. Run a query to show the collection objects.  Note that only two are returned and it excludes the synonym.
5. Search for Gobius uranoscopius.  Note zero collection objects
6. Run a query to show collection objects.  Note one record returned but this is now Bathygobius soporator

**Expected behavior**
All records including synonyms should be returned from the query

**Screenshots**
![image](https://github.com/specify/specify7/assets/7501989/8b70244e-9364-4481-89d3-1c8d2c986503)
![image](https://github.com/specify/specify7/assets/7501989/6a4d4d5b-f056-470d-a1b7-3b4f50b57a69)
![image](https://github.com/specify/specify7/assets/7501989/5ac28e60-131d-4e00-a5fd-951e325b4df6)
![image](https://github.com/specify/specify7/assets/7501989/7003cc80-1dba-459c-ab7b-4f20cebb9392)

Please, also fill out the following information manually:

- OS: Windows 10
- Browser: Chrome
- Specify 7 Version: 7.9.3
- Database Name: KU_Fish_Tissue
- Collection name: Fish Voucher
- User Name: abentley

**Reported By**
BI Ichthyology

**Additional context**
Database name or any other context about the problem here.

**Comment by melton-jason** [comment] 2024-04-01 21:46
Possibly related to or duplicate of #4677

**Comment by acbentley** [comment] 2024-04-01 21:54
Thanks.  I looked to see if it had been reported already but didn't find anything.

Andy

    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V

**Comment by emenslin** [comment] 2024-08-06 19:16
Duplicate of #4677

**Closed by emenslin** 2024-08-06 19:16 UTC
Labels: 1 - Bug
