### ISSUE TITLE
Non Read Only Pick lists showing repeat values

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1199] opened 2022-03-21 16:35 UTC
Discovered by Vims Fish.
In their WaterBody pick list, the value Atlantic Ocean is repeated in the pick list.  According to MySQL, there are only two unique values with "Atlantic" in them, "Atlantic" and "Atlantic Ocean" so the pick list is not showing a variation of Atlantic Ocean, such as a value with an extra space or capitalization.  It is showing the same value multiple times.

**Comment by maxxxxxdlp** [comment] 2022-03-21 16:43
Needs to be tested on a11y to see if it is already fixed

**Comment by grantfitzsimmons** [comment] 2022-03-22 15:40
![image](https://user-images.githubusercontent.com/37256050/159518349-57c341b6-1184-4678-afc5-4539239cb8ed.png)

The issue is present on `edge`

On a11y the Locality details subview does not appear.

![image](https://user-images.githubusercontent.com/37256050/159521158-9ec67f88-ca6d-4149-8635-d5681704e1fb.png)

@maxxxxxdlp

**Comment by maxxxxxdlp** [comment] 2022-03-22 15:51
This error would also be present on the a11y branch (once I fix the subview problem).
Picklists should not contain duplicate values. It has a duplicate in this case because of a separate bug.
I don't think we need special provisions for when a pick list gets duplicate value, as that would never normally happen

**Comment by maxxxxxdlp** [comment] 2022-03-30 20:29
The issue original issue was probably caused by the sizelimit parameter.
In sp6 it deletes older picklist items when adding a new one if total picklistitem count is over the sizeLimit.
In sp7 it fetches only sizelimit items from the back-end. If there more items than the sizelimit, the UI would allow adding new item even though it is already in the database.

I can change the front-end to ignore front-end to ignore the sizeLimit options, but that would picklists with lots of items to take long to load

**Comment by grantfitzsimmons** [comment] 2023-08-07 02:43
Reopen if this is discovered again. It should be fixed?

**Closed by grantfitzsimmons** 2023-08-07 02:43 UTC
Labels: 1 - Bug, 2 - Forms
