### ISSUE TITLE
Going to notifications triggers lots of console errors in edge

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#4060] opened 2023-10-04 02:52 UTC
To reproduce:
1. Go to notifications (do any action which will create it)
2. See the console gets flooded with console errors (Future dates are not supported)

Likely infinite re-render issue.

Not in 7.9, so introduced recently.

Needs to be fixed before v7.9.1 gets released.

![image](https://github.com/specify/specify7/assets/61122018/b423ced4-780c-449d-89a5-ad8deb875d7f)

**Comment by maxxxxxdlp** [comment] 2023-10-04 03:59
Duplicate of issue created 5 days ago by Grant:
Duplicate of #4051

**Comment by maxxxxxdlp** [comment] 2023-10-04 04:00
> Not in 7.9, so introduced recently.

This behavior has been there since at least 7.7

**Comment by realVinayak** [comment] 2023-10-04 12:32
Infinite console logs? I can't reproduce that in v7.9.

**Comment by maxxxxxdlp** [comment] 2023-10-05 02:39
Oh, infinite console errors might mean that there is constant re-rendering happening

**Comment by maxxxxxdlp** [comment] 2023-10-05 02:40
@CarolineDenis can you take a look at what might be causing that? i.e see what states you have used in that component, and set breakpoint in all the places were state is being modified and see if of those states is being constantly modified.

Alternatively, you can use the react profiler - it will tell you which state caused the re-render - https://legacy.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html

**Closed** 2023-10-06 13:51 UTC
Labels: 1 - Bug
