### ISSUE TITLE
Support static values in query builder

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2665] opened 2022-12-15 00:38 UTC
This would be extremely useful for reports and exports

Requested by CSIRO and many others

**Comment by maxxxxxdlp** [comment] 2023-01-04 22:26
Potentially a duplicate of #1145

**Comment by grantfitzsimmons** [comment] 2023-01-11 15:27
> So, just found a use case for static fields in queries.  In mapping our data model to the new GBIF unified model, there are a number of static fields that are not accommodated in our data model that it would be nice to be able to include in a query as static fields.  Any idea when this will be implemented?

From @acbentley

**Comment by grantfitzsimmons** [comment] 2023-02-14 03:49
Looks like a duplicate of https://github.com/specify/specify7/issues/1145

**Closed** 2023-11-08 18:29 UTC
Labels: 1 - Request, 2 - Queries
