### ISSUE TITLE
[a11y] Genbank query returning different results

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1493] opened 2022-05-10 16:34 UTC
![image](https://user-images.githubusercontent.com/37256050/167677471-a03ac080-884d-412e-9d4f-ea71e74ec155.png)
![image](https://user-images.githubusercontent.com/37256050/167677530-a32082d3-0270-4963-af5f-1427e2864cfb.png)

![image](https://user-images.githubusercontent.com/37256050/167677501-ae777c37-9c79-44dc-85cb-0aa6c4d14c74.png)

It seems that Edge is returning the correct results. Specify 6 returns the same results as `a11y`, but the field being queried (text2) is populated many times in each DNA sequences record attached to the CO. Maybe a duplicate of earlier issue or intended

db: `oldfish`
user: abentley
`/specify/query/118/`

**Comment by maxxxxxdlp** [comment] 2022-05-10 20:53
Duplicate of #1349

**Closed by maxxxxxdlp** 2022-05-10 20:53 UTC
Labels: type:bug, pri:unknown
