### ISSUE TITLE
[a11y] Value up and down buttons appear on forms with integers

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1536] opened 2022-05-11 16:53 UTC
![image](https://user-images.githubusercontent.com/37256050/167904599-ea093d5c-80b1-410f-bc5c-43b592c4cdb3.png)

On Safari, there are value up and down buttons that control (seemingly randomly) the integer fields on screen. If you hide one integer field, another one is controlled by these buttons.

Safari, macOS

**Comment by maxxxxxdlp** [comment] 2022-05-11 17:13
Duplicate of #1475
Please don't open duplicate issues

**Closed by maxxxxxdlp** 2022-05-11 17:13 UTC
Labels: type:bug, pri:unknown

**Comment by grantfitzsimmons** [comment] 2022-05-11 17:14
Sorry, GitHub search is very bad & my terminology changes day to day.
