### ISSUE TITLE
Error when attaching xlsx files

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1755] opened 2022-06-15 23:29 UTC
reported by New Brunswick

When attaching files with an xlsx extension, the record appears fine until you click save then you get the following message:
[message1.docx](https://github.com/specify/specify7/files/8914139/message1.docx)

**Comment by maxxxxxdlp** [comment] 2022-06-16 02:29
Duplicate of #1141

**Closed by maxxxxxdlp** 2022-06-16 02:29 UTC
Labels: type:bug, pri:unknown
