### ISSUE TITLE
Business Rules Alert Dialog

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3966] opened 2023-09-01 19:54 UTC
Most of the 7.9 Errors I've found so far in basic features are just Business Rules exceptions. They aren't even that bad. However, if an end user sees them out of nowhere, they seem more severe and scary than they actually are.

A very possible and emotionally heartbreaking  side effect these Business Rules exceptions could cause is that end users will start saying 7.9 is more buggy than previous versions when in reality it's relatively one of our most tested and worked on versions.

For example, this error below does not deserve to have an error message this large and intimidating. 

<img width="896" alt="Screenshot 2023-09-01 at 2 50 00 PM" src="https://github.com/specify/specify7/assets/53784701/d190cdb0-951a-45be-9ef5-5f44f98e6f0c">

**Comment by melton-jason** [comment] 2023-09-01 22:09
This is actually a known issue already.

https://github.com/specify/specify7/issues/3343

In production instances, the error messages are formatted correctly.
In development instances, Django should be supplying html to the frontend, which can then render it appropriately.
The problem is this has stopped working somewhere down the line, and the frontend is instead rendering/accepting it as plain text rather than html.

For now, I will close this as a duplicate.

**Closed by melton-jason** 2023-09-01 22:09 UTC
Labels: 1 - Request

**Comment by maxxxxxdlp** [comment] 2023-09-02 04:19
One could say this is a duplicate of the OG issue created back in 2015 - https://github.com/specify/specify7/issues/108
