### ISSUE TITLE
Mask leading zeroes in numeric catalog number in query results and forms

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1766] opened 2022-06-21 22:30 UTC
Currently, in a database where the default format of numeric catalog number is chosen, a catalog number of 1001 is displayed as 000001001 instead of 1001.
We've always masked those leading zeroes because when it is numeric catalog number, the leading zeroes aren't actually part of the number, they are added in order to properly allow auto numbering

**Comment by maxxxxxdlp** [comment] 2022-06-22 01:46
Duplicate of #1707

**Closed by maxxxxxdlp** 2022-06-22 01:46 UTC
Labels: type:enhance, pri:unknown
