### ISSUE TITLE
QCBX results drop down is cut off by browser when it contains a large number of items

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3458] opened 2023-05-05 16:35 UTC
The query combo box search works when in the actual CO form but not in "Browse in Forms" in the querybuilder. Was able to replicate in `iowaento` and `sdnhmpaleo`. Was not able to replicate in `coldFish`.

https://user-images.githubusercontent.com/103299204/236515632-6c7ef61b-10fe-4f9f-a0a4-fa27ec822493.mp4

https://iowaento-edge.test.specifysystems.org/specify/query/new/collectionobject/

**Comment by maxxxxxdlp** [comment] 2023-05-14 01:39
Can confirm front-end correctly retrieved the search results
Also, other query combo boxes on the form work correctly - thus it's not an issue with form being displayed in a dialog
Someone should take a deeper look at this when they have time

**Comment by CarolineDenis** [comment] 2023-07-07 19:02
@bronwyncombs @carlosmbe 
Could you test this on 7.9-dev please? I couldn't recreate it.

**Comment by bronwyncombs** [comment] 2023-07-07 20:22
I actually came across this earlier on `herb_rbge_3_31_23`

This issue is now also in the form. It is specific to Agent still. Hitting the enter key will auto-fill a seemingly arbitrary term from the list (shown with recording and image of list).

Can't recreate in `NHMD_Test` or `ufwc_3_28_23`

**_Browse in Forms_**

https://github.com/specify/specify7/assets/135047322/eae9bbce-b3ff-4f91-80c6-86fc8ee09bd5

_**Regular form**_

https://github.com/specify/specify7/assets/135047322/427e4be4-363e-49e1-b06d-f445f9fa5197

_**Agent list**_
![Screen Shot 2023-07-07 at 2 56 16 PM](https://github.com/specify/specify7/assets/135047322/bab1c4d3-492a-41f2-8c61-93ed0814f549)

**Comment by CarolineDenis** [comment] 2023-07-07 21:40
So it seems that the results are actually there. There are for some reason displayed outside our frame.


https://github.com/specify/specify7/assets/108160931/59878e00-28ee-47e5-aa46-d73431170762
![Screenshot 2023-07-07 at 2 36 50 PM](https://github.com/specify/specify7/assets/108160931/252fcacc-9076-4058-9df6-033a699700ed)

**Comment by CarolineDenis** [comment] 2023-07-07 21:40
So it seems that the results are actually there. There are for some reason displayed outside our frame.

https://github.com/specify/specify7/assets/108160931/9094b897-2832-42b4-9bc5-216da71c9141

**Comment by CarolineDenis** [comment] 2023-07-07 21:41
![Screenshot 2023-07-07 at 2 36 50 PM](https://github.com/specify/specify7/assets/108160931/9d5d211c-0dc7-4e93-8127-c2c271fda7f6)

**Comment by maxxxxxdlp** [comment] 2023-07-09 03:20
I am pretty sure this used to work - feel free to test earlier versions

possible cause:
- when calculating position, it calculates relative to wrong container (relative to body instead of dialog)
- position is calculated correctly, but styles are applied incorrectly
- `top` CSS style is not applied at all even though it should be

**Comment by CarolineDenis** [comment] 2023-07-10 13:49
@maxxxxxdlp, just tested the oldest version of Sp7 present on the test panel and same issue.

**Comment by grantfitzsimmons** [comment] 2023-07-10 14:13
You just need to scroll since it has such long subviews. It's just outside the page.

**Comment by CarolineDenis** [comment] 2023-07-10 14:26
@grantfitzsimmons let me know if you want to close this issue or if we try to fix it

**Comment by grantfitzsimmons** [comment] 2023-07-10 14:32
I think we should try to fix it, but it should not take priority over large issues. It may be a while unless a member mentions it as something worth prioritizing. I'll remove it from a milestone and add it to the backlog.

**Comment by CarolineDenis** [comment] 2023-07-10 14:35
> I am pretty sure this used to work - feel free to test earlier versions
> 
> possible cause:
> 
> * when calculating position, it calculates relative to wrong container (relative to body instead of dialog)
> * position is calculated correctly, but styles are applied incorrectly
> * `top` CSS style is not applied at all even though it should be

Top is not apply, bottom is. All the other ones seem to have top and not bottom.

**Comment by maxxxxxdlp** [comment] 2023-07-13 01:13
ah, I think I remembered - either top or bottom is applied selectively depending on which is applicable (whether the auto complete should be rendered below or above the input field)

**Comment by CarolineDenis** [comment] 2023-11-07 22:10
The inputTop from `const { bottom: inputBottom, top: inputTop } =
        input.getBoundingClientRect();` doesn't return the correct value.

**Comment by CarolineDenis** [comment] 2023-11-07 22:28
@maxxxxxdlp , 
we have in AutoComplete.tsx this: 
`      /*
       * Hide the list for non screen reader users when it goes below the
       * container so as not to cause content overflow
       */
      const shouldHide = inputTop > parentBottom || inputBottom < parentTop;
      if (shouldHide) dataList.classList.add('sr-only');`
      
Are you ok if, only for this case, I remove the sr-only class as it prevents the lists to be displayed in many cases?

**Comment by maxxxxxdlp** [comment] 2023-11-12 21:57
That code was added to fix a bug - when you scroll the form so that input is below the screen, input remaining rendered made extra scroll bars appear in the browser window.
This code made it hide the input when it goes off-screen

---

based on https://github.com/specify/specify7/issues/3458#issuecomment-1626188723, it seems like we are not adjusting the max height of the input to match the max space available at the top of the container.
I belive that was intentional as otherwise the autocomplete was forced to be vary short in some cases (i.e in form tables), which created UX issues worse than autocomplete overflowing outside the container

if however the input is taller than the space available till the top of the browser window, we could consider limiting it's height in that case - and hope that it doesn't add new complexity&bugs.

---

> Are you ok if, only for this case, I remove the sr-only class as it prevents the lists to be displayed in many cases?

just removing code that seems to misbehave is not a solution

that reminds me of https://github.com/munificent/vigil 🤣

> [But isn't a language that deletes code crazy?](https://github.com/munificent/vigil#but-isnt-a-language-that-deletes-code-crazy)
> No, wanting to keep code that demonstrably has bugs according to its own specifications is crazy. What good could it > possibly serve? It is corrupted and must be cleansed from your codebase.
> 
> Vigil will do this for you automatically.

Instead, please investigate what that code was there for, and see if it can be modified to still accomplish the original purpose, while also fixing the issue you discovered

---

also, @CarolineDenis, when sending code blocks, you can use a special markdown syntax to provide proper code highlighting, and thus make it much easier to read the comments you sent - https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by CarolineDenis** [comment] 2024-01-09 14:59
A duplicate of this issue existed: https://github.com/specify/specify7/issues/3373
See link for other info

**Comment by emenslin** [comment] 2024-05-31 20:25
Duplicate of #3373

**Closed by emenslin** 2024-05-31 20:25 UTC
Labels: 1 - Bug, 2 - Forms
