### ISSUE TITLE
Query result ordering not being preserved when creating a record set

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4547] opened 2024-02-15 16:24 UTC
**Describe the bug**
Query result sort ordering not being preserved when creating a record set.

If individual records are selected, ordering is preserved. Seems to be on the back-end.

**To Reproduce**

1. In the `ciscollections_2_15_24` test panel database, go to the query `/specify/query/31/` (2/14/2024 Anthropology Query for NAGPRA)
2. See that the ordering has the catalog number sorted in ascending order
3. Create a record set from the query
4. See that the order is not preserved

**Screenshots**
The query:
![image](https://github.com/specify/specify7/assets/37256050/1ba37254-5190-4a01-a6b5-403c02b006af)

`ciscollections`, `v7.9.2`

[Specify 7 System Information - 2024-02-15T16_23_48.347Z.txt](https://github.com/specify/specify7/files/14299403/Specify.7.System.Information.-.2024-02-15T16_23_48.347Z.txt)

**Reported by:** @`CWood` from Cranbrook on the [Speciforum](https://discourse.specifysoftware.org/t/select-all-entries-from-a-query-for-record-set-and-csv/1556/4)

**Comment by specifysoftware** [comment] 2024-02-15 16:28
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/select-all-entries-from-a-query-for-record-set-and-csv/1556/6

**Comment by maxpatiiuk** [comment] 2024-02-17 04:09
Duplicate of https://github.com/specify/specify7/issues/601 (that issue also has some explanations from Ben and Tim)

**Closed by maxpatiiuk** 2024-02-17 04:09 UTC
Labels: 1 - Bug, 2 - Queries
