### ISSUE TITLE
`xml-editor`: Editing a pick list clears the `Name` value

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4152] opened 2023-10-24 01:53 UTC
https://github.com/specify/specify7/assets/37256050/04b0086d-a3e8-4ab3-b9cd-accb1edecb49

It looks like the `Title` of the first pick list item may also be affected, but would need to test further to find out. Pretty bad bug.

**Comment by realVinayak** [comment] 2023-10-24 02:01
Should be fixed in https://github.com/specify/specify7/pull/4143

**Comment by realVinayak** [comment] 2023-10-24 02:09
Duplicate of https://github.com/specify/specify7/issues/4142, but keeping it open since this component is also affected by the changes

**Comment by CarolineDenis** [comment] 2023-10-24 20:45
Just tested the fix in https://github.com/specify/specify7/pull/4143, confirm the issue of lost name is not happening anymore. thanks @realVinayak

**Closed** 2023-10-26 17:27 UTC
Labels: 1 - Bug, 2 - App Resources
