### ISSUE TITLE
Add the ability to add selected query results to an existing record set

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3609] opened 2023-06-09 21:04 UTC
When trying to print a group of collection object records at one time, it is not possible to add a selected group of items based on an **existing query** to a record set that already exists. 

In Specify 6, this is solved by merging record sets together. This is not supported in Specify 7.

**Requested By:** Geneva

**Comment by maxxxxxdlp** [comment] 2023-06-10 16:28
Duplicate of #2119

**Closed by maxxxxxdlp** 2023-06-10 16:28 UTC
Labels: type:enhance, pri:unknown
