### ISSUE TITLE
Support label/reports in workbench.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#765] opened 2020-12-17 20:50 UTC

**Comment by maxxxxxdlp** [comment] 2022-06-15 02:54
Possible duplicate of #765

**Comment by grantfitzsimmons** [comment] 2023-02-14 03:50
> Possible duplicate of #765

This actually _is_ #765

**Comment by grantfitzsimmons** [comment] 2023-02-14 03:51
Duplicate of #372

**Closed** 2023-02-14 03:51 UTC
Labels: type:enhance, pri:unknown, back-end
