### ISSUE TITLE
Uploading data from Excel with formatted dates gives an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2027] opened 2022-08-24 13:23 UTC
![](https://global.discourse-cdn.com/standard17/uploads/specifysoftware/original/1X/c1a9c616c252b9953828910a6298480006c78d68.jpeg)

![](https://global.discourse-cdn.com/standard17/uploads/specifysoftware/original/1X/1f9f1e9c239305fc2ba572d57f4062026e3b68d5.jpeg)

I've experienced this many times, and Mandi has reported the same yesterday. 

If a cell is formatted as a date, the WorkBench ignores its configuration when its uploaded and the dates are read as invalid. I have had to convert cells to text to workaround this issue in the past.

**Comment by maxxxxxdlp** [comment] 2022-08-26 13:52
@grantfitzsimmons Please attach a spreadsheet that can reproduce this error.

I was not able to make this happen (though, I was using Google Sheets)

**Comment by grantfitzsimmons** [comment] 2022-08-26 14:20
@maxxxxxdlp I can't make it happen right now, but I know it will happen in the future. I will update as soon as I can recreate. I think dates with more complexity than just a year, month, and date will trigger it (timestamps?)

**Comment by maxxxxxdlp** [comment] 2022-09-13 03:21
@grantfitzsimmons I don't remember, but were you able to find a spreadsheet that reproduces this issue?

**Comment by grantfitzsimmons** [comment] 2022-09-13 16:37
Not since we discussed it. We can close this issue but I suspect we will have another incident before long

**Comment by danb213** [comment] 2022-12-15 23:23
I can recreate this issue on your demo site - see screenshots of the file and the import preview - as well as the file used. It seems to be changing the format from dd/mm/yyyy to mm/dd/yy
![image](https://user-images.githubusercontent.com/110948439/207987623-f5ddd2fe-8bf4-49b2-bc47-1c06a773f3ee.png)
![image](http
[date format testing.xlsx](https://github.com/specify/specify7/files/10241394/date.format.testing.xlsx)
s://user-images.githubusercontent.com/110948439/207987656-a714465d-8c2f-47d1-a915-8c791b0065b9.png)

**Comment by danb213** [comment] 2022-12-15 23:32
![image](https://user-images.githubusercontent.com/110948439/207988652-103fbc11-5b36-4a92-898e-aeb4203c0729.png)

The bug is not there if I save the Excel spreadsheet as a csv and do the upload

**Comment by grantfitzsimmons** [comment] 2023-01-19 02:09
Heather Cole at DAO also liked the report, indicating that she too likely experienced this issue

**Comment by specifysoftware** [comment] 2023-02-22 18:35
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1

**Comment by melton-jason** [comment] 2024-03-07 15:27
@specify/ux-testing can this issue be verified? 
Is it fixed on `edge`?

**Comment by emenslin** [comment] 2024-07-26 20:00
Fixed

**Closed by emenslin** 2024-07-26 20:00 UTC
Labels: 1 - Bug, todo:verify
