### ISSUE TITLE
SQL syntax error when removing collection access from a user for Specify 6

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2544] opened 2022-12-05 16:03 UTC
<img width="900" alt="image" src="https://user-images.githubusercontent.com/37256050/205683781-eeeb2328-6605-4108-af8c-28ac6f46bb3e.png">

```
Error occurred fetching from https://herbrbge6802-testability.test.specifysystems.org/context/user_collection_access_for_sp6/19/

Invalid response code 500. Expected 200.
```

```
ProgrammingError at /context/user_collection_access_for_sp6/19/
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1")
```

https://herbrbge6802-testability.test.specifysystems.org/specify/security/user/19/

Navigate to the user `hatkins` and go to **Set Collections** under the Specify 6 Permissions heading.

Uncheck "Herbarium" and save. See SQL syntax error.

Can recreate in `edge` and `testability`

**Comment by maxxxxxdlp** [comment] 2022-12-05 16:04
Duplicate of https://github.com/specify/specify7/issues/1174. I will merge them

**Closed by maxxxxxdlp** 2022-12-05 16:04 UTC
Labels: type:bug, pri:unknown
