### ISSUE TITLE
Error when attempting to open a views file

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2346] opened 2022-10-24 00:22 UTC
**Describe the bug**
Error message occurs when attempting to open the "Common" views file in the `herbrgbe` database.

**To Reproduce**
1. Go to app resources
2. Click on the "Common" views file under Global Resources
3. See error: 
[Specify 7 Crash Report - 2022-10-24T00_11_59.948Z.txt](https://github.com/specify/specify7/files/9847891/Specify.7.Crash.Report.-.2022-10-24T00_11_59.948Z.txt)

Link: https://herbrbge-testability.test.specifysystems.org/specify/resources/

**Expected behavior**
Expected to be able to view the file.

**Screenshots**
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/197425254-a772be84-1c71-4f45-99a8-f9faae254087.png">
<a href="https://user-images.githubusercontent.com/103299204/197425581-b10922b0-c110-4636-8c94-b12523fbadec.png">Console</a>

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: `testability`

**Database Name:** `herbrgbe`
User: `britchie`

**Comment by maxxxxxdlp** [comment] 2022-10-24 00:25
Duplicate of #1202

**Closed by maxxxxxdlp** 2022-10-24 00:25 UTC
Labels: type:bug, pri:unknown
