### ISSUE TITLE
404 in background when notifications are open with a deleted agent referenced

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3887] opened 2023-08-02 14:22 UTC
**Describe the bug**
After merging an agent and opening the notifications dialog from the navigation menu, the query page in the background changes to 404. 

**To Reproduce**
1. Merge agent
2. Click on Notifications
5. See error

**Expected behavior**
Should remain on query builder page 

**Screenshots**

https://github.com/specify/specify7/assets/135047322/8262902a-3f92-407c-b7a8-b581b1ac149f

**Desktop:**
 - macOS, chrome, v7.9

**Database Name:** `herb_rbge_3_31_23`

**Comment by bronwyncombs** [comment] 2023-08-02 17:18
To clarify, this issue occurs whenever notifications are opened while a merge is in process - not just directly after a merge is initiated or only from the query page


https://github.com/specify/specify7/assets/135047322/9b0a0b14-82b2-499a-b9d5-1c61b6b28c36

**Comment by CarolineDenis** [comment] 2023-08-02 21:19
@bronwyncombs, can you reproduce with the last version of v7.9-dev? Can you reproduce with other db?

**Comment by bronwyncombs** [comment] 2023-08-03 14:42
@CarolineDenis, working as expected in `umichmollusks`! I don't know what's causing it this in `herb_rbge`.

**Comment by CarolineDenis** [comment] 2023-08-03 14:50
I can't reproduce 
![Screenshot 2023-08-03 at 7 49 53 AM](https://github.com/specify/specify7/assets/108160931/599c8b1d-ba15-461f-9c27-2e3ceccfeadf)
![Screenshot 2023-08-03 at 7 50 07 AM](https://github.com/specify/specify7/assets/108160931/6feb530c-a65f-4bb9-8767-1bf1e42df3d6)

**Comment by CarolineDenis** [comment] 2023-08-03 14:56
I couldn't reproduce with herb_rbge 71423 and herb_rbge 31323 but can with herb_rbge 33123
What is the difference?

**Comment by CarolineDenis** [comment] 2023-08-03 14:59
Probably same cause as: https://github.com/specify/specify7/issues/3892

**Comment by grantfitzsimmons** [comment] 2023-08-04 16:13
@bronwyncombs believes this is something that **must** be fixed before release

**Comment by CarolineDenis** [comment] 2023-08-04 17:24
NOTES: 
Issue + steps to reproduce
- merge 2 agents 
- keep in the notification component the 'has started' and the 'has succeeded' 
- merge the newly created agent with another one
- open the notifications. 
See=> 
- first 'succeeded' notification has now a pending link 
- in the console we have an error "No Agent matches the given query" 
- Pop up toast error because error when fetching agent 

Conclusion, we are trying to fetch an agent that doesn't exist anymore to create the link. 
(Just for the test, if we delete the notification with stale/invalid link the error disappear)

**Comment by CarolineDenis** [comment] 2023-08-04 20:45
Decision made by the group: 
Change the FormattedResource link to a NewTab link.

**Comment by melton-jason** [comment] 2023-08-14 14:17
Fixed in #3906

**Closed by melton-jason** 2023-08-14 14:17 UTC
Labels: 1 - Bug, 2 - User Interface
