### ISSUE TITLE
Notification dates use UTC time

### ISSUE THREAD

**Issue by ianengelbrecht** [specify/specify7#5194] opened 2024-08-06 11:01 UTC
See the pic below. We're two hours ahead of UTC time so it's presumably telling me the time these files were created using UTC time. Just needs to be adjusted to local time. 

![image](https://github.com/user-attachments/assets/a0b7cfab-42d8-4b80-ad7a-a41189ebac7b)

**Comment by maxpatiiuk** [comment] 2024-08-07 02:43
Unfortunately, this is a known issue, and fixing it has been a bit trickier then it would seem

Duplicate of https://github.com/specify/specify7/issues/641

**Closed by maxpatiiuk** 2024-08-07 02:43 UTC
Labels: 1 - Bug
