### ISSUE TITLE
Geography Query Crash

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3398] opened 2023-04-24 16:00 UTC
**Describe the bug**
Saved Geography query crashes in Specify 7 (Pre Release 7.8.10 as of 24 April 2023 with no stats page) but not Specify 6.

**To Reproduce**
1. Go to Queries 
2. Click on Geography (https://pripaleo-v7810-prerelease.test.specifysystems.org/specify/query/41/)
3. Run Query

**Expected behavior**
Results shown like in Specify 6

**Screen Recoding and Error Report**

https://user-images.githubusercontent.com/53784701/234052226-806affff-90cf-4ce9-ad52-119fea11eb2c.mp4

[Specify 7 Crash Report - 2023-04-24T15_55_19.202Z (1).txt](https://github.com/specify/specify7/files/11312257/Specify.7.Crash.Report.-.2023-04-24T15_55_19.202Z.1.txt)
[Specify 7 Crash Report - 2023-04-24T15_55_19.202Z.txt](https://github.com/specify/specify7/files/11312258/Specify.7.Crash.Report.-.2023-04-24T15_55_19.202Z.txt)
[Specify 7 Crash Report - 2023-04-24T15_55_11.735Z (1).txt](https://github.com/specify/specify7/files/11312259/Specify.7.Crash.Report.-.2023-04-24T15_55_11.735Z.1.txt)
[Specify 7 Crash Report - 2023-04-24T15_55_11.735Z.txt](https://github.com/specify/specify7/files/11312260/Specify.7.Crash.Report.-.2023-04-24T15_55_11.735Z.txt)

Desktop:
OS: Mac OSx Ventura 
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

Database Name: pripaleo

Reported By
Carlos @carlosmbe

**Comment by melton-jason** [comment] 2023-04-24 17:31
> @realVinayak @melton-jason do you know why there are so many query builder back-end exceptions all of a sudden? can either of you take a look?

The query builder issues in #3399, #3396, and #3395 I believe are only reproducible on the `pripaleo` database on the test panel (@carlosmbe, feel free to correct me if i'm wrong). 

I have done a little looking into the issue, which is probably due to an error during the schema update process to 6.8.01. From https://github.com/specify/specify7/issues/3396#issuecomment-1518368867

> Specify 6.8.01 should be on schema version 2.9. In the 2.9 schema ([schema 2.9 changelog](https://www.specifysoftware.org/wp-content/uploads/2021/09/Specify-Schema-Update-v2.9-15-Sep-2021.pdf)), we added `determinationcitation.figurenumber` and `taxoncitation.figurenumber`, so they _should_ be supported in Specify 6.8.01. I wonder if the original update to Specify 6.8.01 for this database encountered some issues and could not update the database completely.

--- 

This issue _seems_ different from #3399, #3396, and #3395, but I am unable to recreate it on `coldfish`. Does this issue occur in all other paleo databases, or just this one? If this can not be reproduced in other paleo databases, then I am inclined to believe it is caused by the same problem causing #3399, #3396, and #3395. 

Updating `pripaleo` to 6.8.03 has resolved #3399, #3396, and #3395 (https://github.com/specify/specify7/issues/3399#issuecomment-1520516417), but I am unsure if this issue is resolved by the update.

**Comment by carlosmbe** [comment] 2023-04-24 19:38
@melton-jason 
As far as I can tell, this issue is not related to #3399, #3396 and #3395
It occurs in both the original paleo and updated schema.

**Comment by maxxxxxdlp** [comment] 2023-04-24 20:31
@melton-jason thank you for the explanation! I was at a loss for this sudden in flux of query builder issues.

It would be good to have a warning in sp7.8 saying it's no longer compatible with older schema versions.
Of course, it's way more complicated than it sounds:
- We don't know for sure which versions are supported at any point (we don't have capacity to manually test older version or automated tests to tell us). And even if we do know which versions of sp6 schema work with 7.8.10, that may change at any point with new release
- Even if something is not working in older version, it's likely that a lot of features are still working, so for some users that subset of features might be enough (depending on their use case)

**Comment by emenslin** [comment] 2024-07-11 17:18
Fixed

**Closed by emenslin** 2024-07-11 17:18 UTC
Labels: 1 - Bug, 2 - Queries
