### ISSUE TITLE
[a11y] Items that are added to picklists that exceed the limit throw an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1502] opened 2022-05-10 17:56 UTC
![image](https://user-images.githubusercontent.com/37256050/167692181-285e5ad1-ace5-44af-bd87-a552098c2ff7.png)

The option to add an item to a picklist should not appear if there is no room to add. If this behavior is not correctable, then there should be a dismissible error or check before allowing the user to lose all progress and send them to the homepage.

**Comment by maxxxxxdlp** [comment] 2022-05-11 03:02
Duplicate of #108

**Closed by maxxxxxdlp** 2022-05-11 03:02 UTC
Labels: type:bug, pri:unknown
