### ISSUE TITLE
Don't show error for `TypeError: failed to fetch` or `TypeError: NetworkError when attempting to fetch resource.`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3121] opened 2023-03-08 17:35 UTC
![image](https://user-images.githubusercontent.com/37256050/223787408-9e911306-5717-4377-9cb9-508df609e8e1.png)

This is alarming and supposedly harmless, why alert the user with this?

![unnamed](https://user-images.githubusercontent.com/37256050/223787670-04e3bd57-ad48-4786-9b0d-74331f351929.png)

Maybe it would be better as a toast with a friendly message?

**Comment by grantfitzsimmons** [comment] 2023-03-08 21:06
<img width="885" alt="image" src="https://user-images.githubusercontent.com/37256050/223849945-ff5e84dd-2406-4605-9d08-84ecfcddfdd1.png">

```
TypeError: NetworkError when attempting to fetch resource.
```

I just have to shrink this error so that I can watch my data set validation

**Comment by maxxxxxdlp** [comment] 2023-03-08 21:07
what was the url in this error dialog?

**Comment by maxxxxxdlp** [comment] 2023-03-08 21:08
and once again, this error would be dismissible soon (fixed on `agent-merging` branch)

We REALLY must merge `xml-editing` and `agent-merging` soon. There are way too many bug fixes and cool features on them.

**Comment by grantfitzsimmons** [comment] 2023-03-08 21:44
https://nbmfishcollectionimport-edge.test.specifysystems.org/specify/workbench/18/

<img width="774" alt="image" src="https://user-images.githubusercontent.com/37256050/223857272-d46b7458-a015-4968-931f-56681fe2494d.png">
[Uploading Specify 7 Crash Report - 2023-03-08T21 44 18.764Z.txt…]()

**Comment by maxxxxxdlp** [comment] 2023-03-08 21:45
that fix was made because it was required for `agent-merging` (if an error occurs in a process of saving a merged resource)

> Can we separate bug fixes from those branches? 

it's going to be a wasted effort. Rather just focus on getting agent-merging as soon as possible (which we should)

**Comment by grantfitzsimmons** [comment] 2023-03-08 21:45
Unfortunately we have no way of knowing when agent-merging will be done

**Comment by grantfitzsimmons** [comment] 2023-03-08 21:56
This is just about guaranteed after about ~2-3 minutes during an upload

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/37256050/223859672-401c904d-af65-4da9-a1d0-184998db92e0.png">

**Comment by grantfitzsimmons** [comment] 2023-03-09 17:02
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/37256050/224100888-8dff746f-8683-45c3-bfad-683a59c417f4.png">

Fun again rolling back

**Comment by grantfitzsimmons** [comment] 2024-01-22 15:35
<img width="1136" alt="Screenshot 2024-01-22 at 9 35 05 AM" src="https://github.com/specify/specify7/assets/37256050/63e0d5ba-49a7-4a15-bb18-ea5eef31c7ce">

Still very, very annoying :joy:

**Comment by emenslin** [comment] 2024-07-18 20:28
Same as #2199?

**Comment by maxpatiiuk** [comment] 2024-07-18 23:51
yes, seems so - could you please close one of these as "not planned" with label "res:duplicate" and on the other issue put a link to this issue?

**Comment by emenslin** [comment] 2024-07-19 13:37
Duplicate of #2199

**Closed by emenslin** 2024-07-19 13:37 UTC
Labels: 1 - Request, 2 - User Interface
