### ISSUE TITLE
"Add" button does not create app resource of same type

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3359] opened 2023-04-17 18:22 UTC
https://user-images.githubusercontent.com/103299204/232575918-65f0df47-69ab-472e-8490-90132b11fab3.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/190/formatter/

**Comment by maxxxxxdlp** [comment] 2023-05-01 16:05
Duplicate of #3358

**Closed by maxxxxxdlp** 2023-05-01 16:05 UTC
Labels: type:bug, pri:unknown
