### ISSUE TITLE
Web link button not displaying

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2413] opened 2022-11-04 19:32 UTC
<img width="2486" alt="image" src="https://user-images.githubusercontent.com/37256050/200059922-68a659e6-57d3-4ddf-8eaf-c79bdb53b583.png">

Left is `edge`, right is `testability`

https://herbrbge-testability.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178
https://herbrbge-edge.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178

user: `britchie`
db: `herb_rbge`

macOS, Chrome

**Comment by maxxxxxdlp** [comment] 2022-11-21 15:08
Likely a duplicate of https://github.com/specify/specify7/issues/2404
Please reopen if it is not

**Closed by maxxxxxdlp** 2022-11-21 15:08 UTC
Labels: type:bug, pri:unknown
