### ISSUE TITLE
BusinessRuleException when saving new data with an existing value

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4564] opened 2024-02-19 21:23 UTC
**Describe the bug**
When entering new data, a BusinessRuleException error message appears because **Save** is allowed when existing values are inputted into a field that only accepts unique values. 

**To Reproduce**
1. Go to Loans (https://lsumzmammals9823-edge-2.test.specifysystems.org/specify/view/loan/new/)
2. Type in a Loan number that already exists ("12" in video)
3. See that Save is not allowed
4. Click off the field and see that Save is allowed. 
5. Click Save and see error

**Expected behavior**
Save button should stay disabled when an inputted value is not unique.

**Evidence**
`edge`: issue | `v7.9.3.1`: expected behavior

https://github.com/specify/specify7/assets/118556884/ef1c0f1a-9131-40f9-8446-e8190f4efc17

**Crash Report**
[Specify 7 Crash Report - 2024-02-19T20_56_52.751Z.txt](https://github.com/specify/specify7/files/14336871/Specify.7.Crash.Report.-.2024-02-19T20_56_52.751Z.txt)

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `lsumz_mammals_9_8_23`

**Additional context**
Also happens in Data Entry when entering a catalog number that already exists.

**Comment by realVinayak** [comment] 2024-02-19 21:25
duplicate of https://github.com/specify/specify7/issues/4501. side effect of it.

**Closed by realVinayak** 2024-02-19 21:25 UTC
Labels: 1 - Bug, 2 - Interactions
