### ISSUE TITLE
Emojis Cause a crash in Agent Data Entry

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3429] opened 2023-04-27 21:37 UTC
**Describe the bug**
If an Emoji is present in an Agent's First, Last Name or Middle Initial. Specify will crash

[Agent Email is fair game though](https://github.com/specify/specify7/issues/3428)

**To Reproduce**
1. Go to `Data Entry -> Agents`
2. Click on any of the fields stated above
3.  Add Emoji and Save
[Specify 7 Crash Report - 2023-04-27T21_26_02.395Z (1).txt](https://github.com/specify/specify7/files/11348133/Specify.7.Crash.Report.-.2023-04-27T21_26_02.395Z.1.txt)
[Specify 7 Crash Report - 2023-04-27T21_26_02.395Z.txt](https://github.com/specify/specify7/files/11348135/Specify.7.Crash.Report.-.2023-04-27T21_26_02.395Z.txt)

**Expected behavior**
Not a crash or at least a request to remove UTF-8 Characters and only have ASII characters

**Screenshots**
<img width="1792" alt="Screenshot 2023-04-27 at 4 25 09 PM" src="https://user-images.githubusercontent.com/53784701/234995242-7d1776a8-0ab6-4661-ac02-6186970650cd.png">
<img width="1792" alt="Screenshot 2023-04-27 at 4 25 57 PM" src="https://user-images.githubusercontent.com/53784701/234995243-14771b9f-4099-463d-9cea-9c113c6b0b4f.png">
<img width="1790" alt="Screenshot 2023-04-27 at 4 26 14 PM" src="https://user-images.githubusercontent.com/53784701/234995244-cc4a86d4-f30a-4c6b-b8ca-fa45396b5e21.png">

Desktop:
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

Database Name: morpaleo

Reported By
@carlosmbe

**Comment by grantfitzsimmons** [comment] 2023-04-28 01:48
Duplicate of https://github.com/specify/specify7/issues/3429

**Closed by grantfitzsimmons** 2023-04-28 01:48 UTC
Labels: type:bug, pri:unknown

**Comment by melton-jason** [comment] 2023-04-28 13:16
> Duplicate of #3429

@grantfitzsimmons I believe you may have referenced the incorrect issue. This issue _is_ #3429. 
I think you meant #2495 😅

**Comment by grantfitzsimmons** [comment] 2023-04-28 14:06
Yes! Thanks @melton-jason 💪💪
